OneKeyHQ/electrum

- electrum_gui/android/console.py
解决失败交易时间显示错误问题
https://github.com/OneKeyHQ/TaskHub/issues/464
> Solve the problem of wrong time display

- electrum/wallet.py
- electrum_gui/android/console.py
1.Fix the problem of failure to create wallet by importing private key
2.No time information saved for transaction sending failure after disconnection
https://github.com/OneKeyHQ/TaskHub/issues/538
No
> Fix the problem of failure to create wallet by importing private key

- ios/CustomCode/Modules/PassWord/Validation/OKValidationPwdController.m
- ios/CustomCode/Modules/PassWord/View/CLPasswordInputView.h
- ios/CustomCode/Modules/PassWord/View/CLPasswordInputView.m
fix 对于需要身份校验的敏感流程，校验通过后若用户再次返回到校验主密码页，输入框应该清空 #467
Clear the passcode field when input finished
https://github.com/OneKeyHQ/TaskHub/issues/467
iPhone xs max iOS 14.2
…
> iOS: fix Clear the passcode field when input finished

- ios/CustomCode/Modules/PassWord/Validation/OKValidationPwdController.m
Clear the long passcode field after submit.
修复前：长短密码输入错误，弹出提示，密码框中仍是错误密码 ；需手动删除重新填写
修复后：长短密码输入错误，弹出提示，且密码框清空
https://github.com/OneKeyHQ/TaskHub/issues/575
…
…
> iOS: fix Clear the long passcode field after submit

- electrum/pywalib.py
- electrum_gui/android/console.py
1. ~~原本 sign_eth_tx 的参数 value 的单位在 ETH 下是 `ether`，ERC20 下是 `wei`。~~ 建议将单位统一成 `wei`，避免小数传递丢失精度，而且 python 运行时对整型处理比较友好。因此 sign_eth_tx 的参数 value 应该是**字符串格式化后的整型，精确到 wei**
2. ~~相同的 sign_eth_tx 的参数 gasprice 从 `gwei` 改成 `wei`。~~ 目前也就 ETH 达到了 gwei 的水平，其实 ETC 以及其他类 ETH 链还没达到 gwei 水平，建议把单位改成 wei 更加通用
3. 去除不必要的 toChecksumAddress 转换并健全判断
4. 广播交易后不建议轮训等待，因为上链时间不可知
**变更**
经过讨论，保持 value 和 gasprice 的单位不变，方便前端调用
N/A
1. 收发 ETH/ERC20
@shuaiLiWang 辛苦帮忙 review 下
> ETH - Adjust sign_eth_tx

- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/ReceiveHDActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/IBaseView.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/PassWordViewModel.java
- android/app/src/main/res/layout/dialog_warning.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
身份校验页面添加viewModel，修复部分机型Toast 弹框会携带OneKey
no issue
…
…
> Optimize the password check page and fix toast show OneKey

- electrum/eth_wallet.py
- electrum/exchange_rate.py
- electrum/util.py
- electrum_gui/android/console.py
1. 初始化 AndroidCommands 可指定 chain_type
2. 修改 DecimalEncoder，将 Decimal 序列化成字符串
3. 调整 select_wallet 和 get_all_wallet_balance 接口，统一不同币种的返回值，向后兼容
Nope
1. 调用 select_wallet 和 get_all_wallet_balance 接口，获取 ETH 和 BTC 下的返回值
@shuaiLiWang 帮忙 review，多谢
> ETH - Adjust APIs

- electrum/eth_wallet.py
The eth wallet created with the private key and keystore generates the checksum address
https://github.com/OneKeyHQ/TaskHub/issues/733
python
…
> The eth wallet created with the private key and keystore generates the checksum address

- android/app/src/main/java/org/haobtc/onekey/adapter/WalletListTypeAdapter.java
+ 偶现的钱包列表页硬件钱包的硬件的类型 logo 不展示。
None
…
…
> Android:Wallet occasional wallet list page type flag is not displayed

- android/app/src/main/java/org/haobtc/onekey/activities/settings/OneKeyManageActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/HardwareUpgradeActivity.java
硬件升级重启后，点击按钮「升级固件」，显示旧版本，没有更新成新版本
单独升级蓝牙，升级成功之后，页面再次打开也更新为新版本
OneKeyHQ/TaskHub#695
…
…
> Successful hardware upgrades show older versions

- android/app/src/main/java/org/haobtc/onekey/ui/activity/HardwareUpgradeActivity.java
bootLoader 模式升级完成页面未刷新
OneKeyHQ/TaskHub#799
…
…
> The bootLoader mode upgrade page is not refreshed

- electrum_gui/android/console.py
验证keystore时 提示信息不正确
https://github.com/OneKeyHQ/TaskHub/issues/800
Python
…
> Inaccurate error message when verifying keystore

- electrum/eth_wallet.py
- electrum/keystore.py
- electrum/plugins/trezor/clientbase.py
- electrum/plugins/trezor/trezor.py
- electrum/util.py
- electrum/wallet.py
- electrum_gui/android/console.py
1.ETH/BTC增加签名消息和验证消息接口
2.整理eth_wallet删除 一些不使用的代码
https://github.com/OneKeyHQ/TaskHub/issues/184
Python
…
> Add sign_message and verify_message for eth and btc wallet

- android/app/src/main/java/org/haobtc/onekey/adapter/HdWalletAssetAdapter.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/AllAssetsActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/res/layout/fragment_choose_import_mode.xml
资产页面点击账户进入详情页，和首页点击详情流程一样
导入私钥 英文环境时，文字与图表重叠
OneKeyHQ/TaskHub#822
OneKeyHQ/TaskHub#530
…
…
> Click on the details page for all assets

- electrum/eth_wallet.py
- electrum/keystore.py
- electrum/plugins/trezor/clientbase.py
- electrum/plugins/trezor/trezor.py
- electrum/wallet.py
- electrum/wallet_db.py
- electrum_gui/android/console.py
1.针对eth专门提取签名和验签接口
2.修复从第二个派生钱包开始核验地址错误的问题
https://github.com/OneKeyHQ/TaskHub/issues/848
Python
…
> Separate signature and verification interface for eth

- electrum/plugins/trezor/clientbase.py
- electrum_gui/android/console.py
- electrum_gui/android/hardware.py
拆分console.py中的硬件相关的部分
- 第一个commit是将console.py中硬件交互相关的内容拆分成独立文件，尽可能保持原样（包括潜在的错误）方便review
- 第二、五个commit是前一个文件改动到相关的文件就做代码风格的改动，标准是通过flake8
- 第三个commit为独立出来的硬件交互模块的方法加上annotation
- 第四、六、七个commit是将trezorlib的直接引用移动到trezor plugin中去，目标是将所有需要与trezor交互的内容都放到plugin中，将plugin作为lib使用，上层这个模块只关注业务相关的内容，接收app上层的请求，通过一个client访问底下的lib完成和硬件相关的工作。目前存在无业务代码只是直接转发请求到插件中的情况（且大多如此），原因是需要统一定义接口，以及上层命令调用没有做统一的异常处理/消息返回。一旦完成上层的异常处理/消息返回，也可以把单纯的转发删除掉，不过要看是否要保留函数定义从而通过docstring提供接口说明（后者较可能）。
No
N/A
No
> Hardware split

- electrum/eth_wallet.py
- electrum/pywalib.py
- electrum_gui/android/console.py
1. 因为 ETH/BSC/HECO 的所有钱包都共用了 PyWalib 实例，所以必须确保在调用 PyWalib 实例的方法前都切换到正确的网络下
2. 原来 hard code 的 ETH 文案也改成当前的 symbol
…
…
…
> Fix supporting of BSC/HECO

- electrum_gui/android/console.py
- electrum_gui/android/wallet_context.py
分离出来console.py代码中原来的`local_wallet_info`、`backup_info`、`derived_info`。这些信息既可作为钱包属性，也可以另外存储但作为和钱包的关联属性存在（类比关系型数据库的关联表）。
N/A
N/A
@shuaiLiWang  第一个commit（分离local_wallet_info那个）里面几个关于检查类型的辅助方法需要额外关注。现在保持了原来的逻辑，但是原来的判断对什么时候需要判断是否硬件('-hw-')的要求不是很明确，要看看原来的判断是否已经有问题了。
> Console.py分拆 - 分离运行时钱包信息的缓存

- electrum_gui/common/provider/exceptions.py
- electrum_gui/common/provider/manager.py
调整 get_provider_by_chain 的实现，支持获得特定类的实例。
目前 BlockBook，Etherscan 和 Geth 各有优劣，在使用过程中都可能要用到。
例如 ETH 在使用过程中会用默认的实例做获取价格，获取交易记录这种常规操作，
然后用 Geth 实例获取合约信息操作，还有通过 Etherscan 获取合约代码的信息
…
…
…
> adjust get_provider_by_chain

- ios/CustomCode/Modules/Token/Model/OKTokenManager.m
- ios/CustomCode/Modules/WalletList/ChangeWallet/OKChangeWalletController.m
iOS fix: reload tokens cache while wallet changed.
https://github.com/OneKeyHQ/TaskHub/issues/1012
…
…
> iOS fix: reload tokens cache while wallet changed.

- electrum_gui/android/console.py
经跟ios和android讨论 统一switch_wallet接口返回的数据中wallets字段为token的信息
…
…
…
> Unify the switch wallet interface to return only the token address

- electrum/wallet.py
- electrum_gui/android/console.py
现象：相同的助记词导入不同的钱包 余额会不一致
原因：因为我们是fork的electrum 他会预先生成20的收款地址和10个找零地址 并且会维持这个未使用的地址个数（就是使用一个后会增加一个 这样就保证 我当前地址之后的20个地址的余额我都汇总在内了）。 我们现在的版本因为用户体验把这个20和10的限制修改成了1（因为创建钱包如果一下生成30个地址还是很耗时的，用户体验不是很好，而且恢复钱包的流程会更明显），这就导致了 如果用户使用过其他钱包 并且 其他钱包里边有间隔两个地址没有使用的情况 第三个地址的余额我们是统计不到的 所以 就有必要增加一个预先生成的地址池 这样就保证 统计到的余额是相对准确 但是 也不能保证一定准确 因为 如果用户自定义了一个间隔100+地址之后的地址 我们还是会统计不到 
为什么这么修改
1.没有在wallet.py中直接修改self.gap_limit值 是因为 创建钱包时候的速度要限制下来 所以选择在select_wallet的时候修改这个限制，去创建钱包
2.为什么要改成100 
昨天改这里的时候 只是看bitcoin是默认的keypool是100 具体为什么要设置成100 后来他又提升到1000 这个我没找到相关的官方文档介绍 只是从字面意思自己判断的 觉得他是因为没有HD钱包的时候 一下会生成100个地址 还允许用户导出地址对应的私钥 这样就保证用户使用的地址都是备份过的 不至于出现钱丢失的现象  我们这个目前使用的都是HD钱包 不要提前生成那么多（这个有时间可以去跟踪具体原因）
今天早上跟奥峰老师商量了一下 觉得我们这里只要维护20个的地址池就能保证大部分的情况了 没必要为了特别个例去维护100个或者1000个地址  所以 我会修改100为20
If it fixes a bug or resolves a feature …
> Fix the problem that the balance of wallets created with the same mnemonic will be different

- electrum/pywalib.py
- electrum_gui/android/console.py
- electrum_gui/common/basic/ticker/__init__.py
- electrum_gui/common/the_begging.py
- start_debug_env.py
- tox.ini
使用tox+virtualenv快速启动一个python开发环境
- 放在virtualenv里和本地的python环境隔离模拟实际运行时的情况（我甚至想能不能装chaquopy）
- 洁癖患者福音，不干扰开发者本地的文件系统（所有相关内容都在.tox/debug里）
- 方便快速修改代码和进入调试环境
- 用monkey patch解决加载设备的问题（或者还有其他问题待遇到时处理），除了开发的代码，其它都不需要改动
1. 确保安装了tox（使用`pip3 install tox`）
2. 使用`tox -edebug`启动默认调试环境（不实例化`AndroidCommands`）
3. 使用`AUTOSTART="" tox -edebug`启动实例化`AndroidCommands`的调试环境，默认使用`"debug"`作为`android_id`字符串
4. 使用`ANDROID_ID`环境变量选择用于实例化`AndroidCommands`的`android_id`字符串
5. 使用`USE_NETWORK`环境变量选择使用的网络，默认主网，可选值为`"sim"/"test"/"reg"`
6. 例子如下（连接硬件之后`get_feature`和擦除设备）
```bash
$ AUTOSTART="" ANDROID_ID=myid tox -edebug
debug create: /Users/bixin/work/electrum/.tox/debug
debug installdeps: aiohttp, aiohttp-socks, aiorpcX, bitstring, cryptography, dnspython, eth_utils, eth-account, ipython, libusb, mnemonic, peewee, …
```
> python开发环境快速启动

- electrum/pywalib.py
- electrum_gui/android/console.py
- electrum_gui/common/provider/clients/eth/blockbook.py
- electrum_gui/common/provider/clients/eth/etherscan.py
- electrum_gui/common/provider/clients/eth/geth.py
- electrum_gui/common/provider/data.py
filter_wallet 方法，会请求节点查询恢复地址的交易信息，和地址余额。
改动后使用 get_address 接口，来判断地址是否存在。
#https://github.com/OneKeyHQ/TaskHub/issues/802
python and App for android
测试代码
```
for i in range(20):
a = time()
self.filter_wallet_before()
a_time = time() - a
b = time()
self.filter_wallet()
b_time = time() - b
print("|", i+1, "|", a_time, "|", b_time, "|")
```
|  seq | before  | after  |
|---|---|---|
|1 | 11.016926050186157 | 9.206606149673462|
|2 | 10.029989004135132 | 9.575931072235107|
|3 | 10.155919075012207 | 8.379886865615845|
|4 | 9.439301013946533 | 8.257841110229492|
|5 | 11.142247200012207 | 9.520052909851074|
|6 | 9.949625730514526 | 9.098222255706787|
|7 | 10.417425155639648 | …
> [pref] reduced http requests during recovery process

- electrum/wallet.py
- electrum_gui/android/console.py
问题描述：
之前android端传递给python的android_id为写死的值，正常情况下应该传递设备的唯一id给python。客户端如果现在直接更改这个值，这个版本之前的app创建的钱包就不能正确的被加载，此pr就是为了解决此问题
解决方法：
用户传递正确的android_id，加载钱包时如果加载失败会尝试用之前错误的android_id进行加载
…
Python
…
> Pre-compativility issue with loading old wallets due to incorrect android_id passing

- electrum/eth_wallet.py
- electrum/plugins/hw_wallet/plugin.py
- electrum/util.py
- electrum_gui/android/console.py
减少对pywalib的依赖，去掉多余的wrap
- 整理eth_wallet.py，这个文件是我们添加的非electrum项目原生的内容，所以整体代码风格可以调整方便之后进一步做迁移。（包括flake8，black，isort，根据google python code style完成imports的调整）
- 简化eth_wallet中的两个调用
- 清理掉通过pywalib/web3的wrap，可以直接使用底层的eth_keys和eth_utils（web3默认需要提供一个http endpoint了，但新增在electrum_gui/common下的逻辑完成了RPC的工作）
OneKeyHQ/TaskHub#1181 的一部分工作
N/A
无
> Chainlist支持1 - 减少对pywalib的依赖

- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/testnet_chains.json
- electrum_gui/common/provider/chains/eth/clients/blockbook.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
- electrum_gui/common/provider/interfaces.py
- electrum_gui/common/provider/loader.py
- electrum_gui/common/provider/manager.py
1. 从 ClientInterface 中提取出 SearchTransactionMixin，eth 相关的请求优先走 Geth，交易历史相关的才走 trezor blockbook
2. 修复 geth 获取 erc20 余额，不知是不是 bsc 改了节点的原因还是其他的，返回的数据跟 eth 有些不同，在某些情况下末尾多了一个32字节格式的 0 （可能这也是导致 trezor blockbook 无法获取某些代币余额的原因）
3. 将 Geth rpc 换成咱自己 trezor blockbook 暴露的 rpc
…
…
…
> Extract SearchTransactionMixin

- electrum_gui/android/console.py
- electrum_gui/common/provider/chains/btc/provider.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
- electrum_gui/common/provider/chains/eth/provider.py
- electrum_gui/common/provider/chains/eth/test_provider.py
- electrum_gui/common/provider/data.py
- electrum_gui/common/provider/interfaces.py
- electrum_gui/common/provider/manager.py
- electrum_gui/common/secret/interfaces.py
1. 将 AddressValidation 的 format 重命名成 encoding，更加表意，跟后面的接口保持一致（ @liuzjalex @QuincySx  这个会影响 parse_qr 接口，帮忙检查下是否会影响 app）
2. 预先给 secret 模块加上后续实现需要用到的接口
3. 填充 ProviderInterface, 新增多个方法
4. 实现 ETHProvider, 并加上测试用例
5. 填充 BTCProvider，后续再实现（不填充就无法构建实例，影响正常业务）
6. 填充 UTXO 相关接口
…
…
…
> Filling ProviderInterface

- electrum/eth_servers.json
- electrum/pywalib.py
- electrum_gui/common/coin/configs/chains.json
更新RPC endpoint为代理缓存的节点。
另外清理掉pywalib残留的无用属性，历史记录已经用新的逻辑用blockbook或者etherscan的实现来获取了。
No
N/A
No
> EVM networks: update RPC endpoints

- electrum_gui/common/provider/chains/eth/clients/etherscan.py
commit1：
现象：修复eth钱包显示金额不准确问题
原因：因为etherscan获取到的金额是10进制，代码中却进行了16进制的转换
…
Python and Android
…
> Fixing an inaccurate amount displayed in eth wallet

- electrum_gui/android/console.py
前端需要展示当前钱包(地址)的派生路径
https://github.com/OneKeyHQ/TaskHub/issues/1287#issuecomment-823813772
python
…
> Get the derivation path of the current wallet

- electrum/eth_servers.json
- electrum/eth_wallet.py
- electrum/pywalib.py
- electrum_gui/android/console.py
- electrum_gui/common/provider/chains/eth/clients/blockbook.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
- electrum_gui/common/provider/data.py
- electrum_gui/common/provider/interfaces.py
- electrum_gui/common/provider/manager.py
- 清理原来eth_servers.json配置文件中的一些无用内容，方便后续合并
- 逐步清理console.py中对pywalib的依赖，目前这些内容还不涉及将原来的功能用provider去实现，预计下一个/几个PR来完成这个，也就能清理掉pywalib，从而所有和链交互的都会使用新的逻辑了
OneKeyHQ/TaskHub#1181 的一部分工作
N/A
剩余gas相关，transaction相关，contract相关需要把相关的逻辑移动到electrum_gui/common底下。预计下一个PR会更大，所以先review这一部分吧。
> Chainlist 支持2 - 清理pywalib以合并配置文件

- electrum_gui/android/console.py
commit1:BTC每种地址类型都可以派生20个钱包(软件支持)
commit2：BTC根据地址类型派生钱包（硬件支持）
commit3：根据review意见做了一些修复
commit4：解决新逻辑跟已创建钱包的兼容性问题
https://github.com/OneKeyHQ/TaskHub/issues/1253
Python
…
> Support for BTC type wallets derived from address types

- electrum/eth_servers.json
- electrum/eth_wallet.py
- electrum/pywalib.py
- electrum_gui/android/console.py
- electrum_gui/common/provider/chains/eth/clients/blockbook.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
- electrum_gui/common/provider/data.py
- electrum_gui/common/provider/interfaces.py
- electrum_gui/common/provider/manager.py
#708 合并之后我们又合并了 #725，但是 #708 合并得不是时候，所以这两个PR都回滚掉然后重新提交了 #727 作为 #725 的替代先合并进去。现在重新提交一次 #708 中的内容。
与 #725 合并之后的代码diff结果如下（改了一处变量名，#727 比 #725 多了一处小改动），所以整体代码仍一致
```diff
$ git diff 8f5370cde94fce918fbf6a966da1c55b84ad8aa4
diff --git a/electrum_gui/android/console.py b/electrum_gui/android/console.py
index e55383c33..09c6d8e93 100755
--- a/electrum_gui/android/console.py
+++ b/electrum_gui/android/console.py
@@ -1060,7 +1060,7 @@ class AndroidCommands(commands.Commands):
except Exception as e:
raise BaseException(e)
-        ret_data = {"tx": str(self.tx)}
+        ret_data = {"tx": str(tx)}
try:
if self.label_flag and self.wallet.wallet_type != "standard":
self.label_plugin.push_tx(self.wallet, "createtx", tx.txid(), str(self.tx))
@@ -4235,18 +4235,14 @@ class …
```
> Rework of #708

- electrum_gui/android/console.py
commit 1: 修复 #714 引入的恢复钱包失败的问题 (OneKeyHQ/TaskHub/issues/1349)
commit 2: 修复 #714 引入的删除HD钱包失败的问题
~commit 3: 整理代码中将evm对应的cointype当作bip43 purpose的问题 (@shuaiLiWang 我不确定是之前是有意这么设计的还是就是个错误一直没注意到...)~
OneKeyHQ/TaskHub/issues/1349
Android 测试包
No
> 修复 #714 引入的问题

- electrum_gui/android/console.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
- electrum_gui/common/provider/interfaces.py
- electrum_gui/common/provider/manager.py
#恢复钱包，耗时分两步，推导 BTC 地址（大概10-20s），eth 和 eth fork 币种通过网络请求获取币种信息(80个网络请求，每个30S超时，可能会耗费45分钟时间才会返回结果)。
改进后，只会产生4个网络请求，每个设置10s超时，最坏情况，40s 能得到结果。
https://github.com/OneKeyHQ/TaskHub/issues/802
… python console
…
> add batch to get address info feature

- electrum_gui/android/console.py
In wallet db of a recovered EVM network based wallet, the wallet_type
was always "eth_standard". This is incorrect so this commit fixes it.
修复恢复钱包时wallet_type没有正确写入数据库导致后续的问题。
OneKeyHQ/TaskHub#1424
Android手打测试包
No
> console: fix wallet type when recovering wallets

- electrum_gui/android/console.py
commit1：恢复时，btc的path是不对的，导致创建的地址也是不对的
commit2：.恢复的时候清除上一次恢复的数据（之前的产品设计是有个取消恢复按钮，点击取消恢复会调用recovery_comfirmed并传入空list 此时进行清除缓存，后来取消按钮删除后修改为左上角返回按钮 此时 客户端没有调用此接口，就出现当用户恢复了一个助记词 但是没有确认创建 而是 返回 又重新输入一个新的助记词 就会有问题） 
https://github.com/OneKeyHQ/TaskHub/issues/1539
https://github.com/OneKeyHQ/TaskHub/issues/1526
https://github.com/OneKeyHQ/TaskHub/issues/1524
python
…
> Fix recovery issue

- electrum/eth_wallet.py
serializable_unsigned_transaction_from_dict 内部需要 to address 是 checksum address
…
…
…
> Fix - use checksum address in web3

- electrum_gui/android/console.py
eth fee 计算有误差，需要确保 gas_price * gas_limit = fee
https://github.com/OneKeyHQ/TaskHub/issues/1564
…
…
> fix eth fee calculation

- electrum_gui/android/console.py
- electrum_gui/common/provider/data.py
- electrum_gui/common/provider/manager.py
swap现在要native化，经过跟ios/android端讨论 python需要增加四个接口支持
1.获取erc20中approve接口需要的field data
2.获取erc20中allowance接口的结果
3.获取erc20中balanceof接口的结果
4.通过txid获取交易状态
https://github.com/OneKeyHQ/TaskHub/issues/1600
Python
…
> Support swap

- electrum_gui/common/basic/request/interfaces.py
- electrum_gui/common/basic/request/json_rpc.py
- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/data.py
- electrum_gui/common/price/channels/uniswap.py
- electrum_gui/common/price/data.py
- electrum_gui/common/price/manager.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
从去中心化交易所获取代币价格，目前添加Uniswap Router合约的支持，从而支持ETH(使用Uniswap)、BSC(使用pancake)，HECO(使用mdex)链上的代币价格获取。
OneKeyHQ/TaskHub#1487
Android Mainnet App
- 合约地址和相关中间代币地址以及基础代币(WETH/WBNB/WHT)地址都在配置文件里，因为考虑后面转成动态
- json不好写注释所以没法在文件中直接注明合约地址对应的代币，可能以后考虑用yaml...
> Get token prices from Uniswap-based decentralized exchanges

- electrum_gui/android/console.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
etherscan下发币失败问题：因为获取fee的时候转换报错
https://github.com/OneKeyHQ/TaskHub/issues/1736
python
…
> Solve the problem of failing to get the default fee information under etherscan

- electrum_gui/android/console.py
回退get_default_fee_info的异常统一 （问题引入在https://github.com/OneKeyHQ/electrum/pull/779）
…
…
> Recover the return value of the get_default_fee_info interface

- electrum_gui/android/console.py
- electrum_gui/common/provider/data.py
跟前端讨论后 获取交易历史中的tx_status字段以dict的方式返回 类似{“status”：2， “other_info:”}
…
…
…
> Modify the tx_status field in the get_all_tx_list return value

- electrum_gui/android/wallet_context.py
上周五公司有部手机复现了wallet_type这个错误 就借机修复了 具体原因是由于本地存在一个.tmp.文件 并且这个文件的类型是unknown
我解决这个问题修改了两个地方：
第一个是load_wallet使用的时候 如果解析异常就会直接return（不会添加到self.deamon中）
第二个是list_wallets的时候不返回这类钱包信息
这个修复相当于是workaround，具体的原因还要查找为啥会出现.tmp.文件 这个会再继续跟踪  
…
iOS
…
> Fix wallet_type error

- electrum_gui/common/basic/exceptions.py
python端使用的key(以msg_开头) 跟lokalise端定义的key不一致(以msg__开头) 导致前端解析不到正确翻译信息
https://github.com/OneKeyHQ/TaskHub/issues/1868
…
…
> The definition of key on the python is not consistent with the definition of lokalise

- electrum_gui/android/console.py
当获取不到法币价格时， 正确显示 coin_asset 值。
https://github.com/OneKeyHQ/TaskHub/issues/1904#issuecomment-863046505
…
…
> fix: adjust the calculation of coin_assets

- electrum_gui/common/wallet/daos/account.py
- electrum_gui/common/wallet/manager.py
目前 wallet_manager 默认相同地址可以导入创建多次，所以这里需要应该用 wallet_id 来搜索
https://github.com/OneKeyHQ/TaskHub/issues/1904#issuecomment-863797949
…
…
> Fix query_accounts_by_addresses

- electrum_gui/android/console.py
跟ios联调 发现btc有确认数时获取不到已确认数量 目前流程需要显示 
…
ios
…
> Fix BTC wallet cannot get the confirmed number

- electrum_gui/common/provider/chains/stc/provider.py
- electrum_gui/common/tests/unit/provider/chains/stc/test_provider.py
判断 `ReceiptIdentifier` 是否在链上已存在，存在情况下，自动转换成 `0x` 地址发送，可以降低 gasUsed。此改动前端不受影响。
…
…
> check the receiptIdentifier activation status

- electrum_gui/android/console.py
- electrum_gui/common/basic/exceptions.py
- electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
- electrum_gui/common/provider/chains/stc/provider.py
- electrum_gui/common/provider/data.py
- electrum_gui/common/tests/unit/provider/chains/stc/test_provider.py
- electrum_gui/common/wallet/handlers/account.py
- 使用 [`contract.dry_run`](https://playground.open-rpc.org/?schemaUrl=https://developer.starcoin.org/rpc/schema/contract.json) 预估手续费
- 验证地址合法性的时候，stc 会单独判断地址是否存在。
- 增加 msg__the_address_has_not_been_activated_please_enter_receipt_identifier i18n key。 @reepig
…
gas_limit 返回的接口预估值， 没有做类似数值扩大的操作。
> stc: support estimate_gas_limit

- electrum/util.py
- electrum_gui/android/console.py
- electrum_gui/common/basic/api.py
- electrum_gui/common/basic/dataclass/dataclass.py
- electrum_gui/common/basic/exceptions.py
- electrum_gui/common/basic/functional/json_encoders.py
- 整理了API和exceptions，将两者分开
- json的DecimalEncoder放到该放的地方
- import和一些命名的整理，非引入新框架的内容暂时没管
- import 看[这里](https://google.github.io/styleguide/pyguide.html#22-imports)
- 命名根据上一条的逻辑，可以把模块名认为命名的一部分。比如`api.py`里起名`Version`那么使用时就是`api.Version`，而如果按原来的命名`ApiVersion`就是`api.ApiVersion`，后者就显得有些重复了
OneKeyHQ/TaskHub#1448
No
把`api_entry`拿出来主要目的是以后加上参数验证，前后端分离之后会有个大的params参数，考虑加上jsonschema就可以做参数基础格式的验证。
> reorganize api & exceptions

- electrum_gui/android/console.py
原本 settings.ENABLED_CHAIN_COINS 是为了做切换币种启用状态用的，但现在在加载时候就已经确认启用哪些币种了，所以这里就不需要检查 only_enabled 了
https://github.com/OneKeyHQ/TaskHub/issues/1904#issuecomment-869367659
…
…
> parse_address_v2: Fetch all chains without enabled check

- electrum_gui/android/console.py
- electrum_gui/common/provider/chains/eth/clients/blockbook.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/provider/data.py
- electrum_gui/common/provider/manager.py
- electrum_gui/common/tests/unit/transaction/test_manager.py
- electrum_gui/common/the_begging.py
- electrum_gui/common/transaction/daos.py
- electrum_gui/common/transaction/data.py
- electrum_gui/common/transaction/manager.py
- electrum_gui/common/transaction/migrations/0002_txaction_delete_symbol_and_decimals.py
- electrum_gui/common/transaction/migrations/0003_txaction_add_archived_id.py
- electrum_gui/common/transaction/models.py
1. 更新 transaction 模块实现，更好地处理同步
2. 迁移 get_general_coin_tx_list 实现
3. get_tx_info 适配 GeneralWallet
4. 自动刷新 Pending 交易
以下简单解释下 query_actions_by_address 的实现：
1. 每次获取第一页数据时都会为地址分配一个 `归档 ID`。同一个归档 ID 标记的交易记录可认为是连续的（即该区块段里的交易是完全同步的）
2. 现在搜索地址 A 的交易记录，先为它分配个归档 ID（目前用当前时间戳做归档 ID）
3. 因为本地没有交易记录，所以会去链上获取前200个交易，然后保存到 DB，并为他们设置相同的归档 ID（假设交易的区块号从 10000 - 11000）
4. 目前分页是 20 一页，所以用户在后续的 9 页都不会请求网络，而是直接从 DB 获取
5. 当用户滑到最底部后，因为本地没有更多记录了，又需要去请求链上，此时会从最后区块开始请求，即请求 10000 以前的200条交易记录
6. 假设又获取到从 800 到 1000 区块的交易记录，此时保存到数据库时依然为他们设置跟上面一样的归档 ID 。此时就有地址 A 从 800 - 11000 区块共 400 条连续的交易记录了
7. 如果用户继续往下翻页，依然可以按照上面的做法继续新增
8. 而如果用户过了一段时间后又产生了 300 条数据，想刷新下最新的数据
9. 因为是重新获取第一页，所以又用户分配个新的 `归档 ID`
10. 此时因为还没有任何一笔交易被这个新的归档 ID 标记过，但我们知道此前有 400 笔交易记录被之前的归档 ID 标记过了，而之前那个归档 ID 的最后一条记录在 1100 区块，所以会尝试获取从最新到 1099（1100 - 1，为了确保最终会出现交集） …
> Transaction related

- electrum_gui/android/console.py
- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/testnet_chains.json
- electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
- electrum_gui/common/provider/chains/stc/provider.py
- electrum_gui/common/provider/chains/stc/sdk/starcoin_stdlib/__init__.py
- electrum_gui/common/provider/manager.py
- electrum_gui/common/tests/unit/provider/chains/stc/test_provider.py
导入观察地址，需要将  receipt_identifier 转换为 hex格式地址
https://github.com/OneKeyHQ/TaskHub/issues/2149#issuecomment-871146646
主网转账协议有更新，使用v2协议， 不再检查地址是否激活。 去掉之前激活相关判断。
…
…
…
> adjust  stc mainnet upgrade

- electrum_gui/android/console.py
修复了ios下存在只读钱包的时候 升级密码提示“raising by require”的问题
https://onekeyhq.atlassian.net/browse/OK-2694
Python
…
> OK-2694 Solve the problem of stc's read only wallet that reports an error when upgrading the password

- electrum_gui/common/provider/chains/sol/clients/solana.py
1. replace `getConfirmedSignaturesForAddress2` with `getSignaturesForAddress` 
2.  fix transaction parse bug
[OK-2603]
local
nil
[OK-2603]: https://onekeyhq.atlassian.net/browse/OK-2603
>  fix sol transaction parse bug

- electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
- electrum_gui/common/provider/chains/stc/sdk/starcoin_stdlib/__init__.py
官方浏览器插件仍然继续使用的 ScriptFunctionCall__PeerToPeerV1。
decode 交易信息， 也需要支持。 避免解析不出完整数据。
应该不太紧急，可以放到下周发布。
…
python console
…
> stc: support ScriptFunctionCall__PeerToPeerV1

- electrum/mnemonic.py
清掉一个idna的import，idna新版本里没这个unicode的对象了，所以导致跑coverage的时候自动装上的是最新的idna的话就会报错。而这个unicode的import实际上又没被用到所以去掉就好。
P.S.: 在tox.ini里加上idna指定版本也能解决。
No
Python
No
> mnemonic: remove unneeded import

- electrum_gui/android/console.py
不能清除 hw_info, create_hw_derived_wallet 会调用两次 get_xpub_from_hw，self.hw_info 需要缓存第一次调用获取到的 xpub
…
…
…
> self.hw_info should not be cleared before creation

- electrum_gui/common/provider/chains/eth/clients/blockbook.py
https://onekeygroup.slack.com/archives/C02207B6FNC/p1627390593198900?thread_ts=1627373315.177900&cid=C02207B6FNC
blockbook 只要未同步完就会把 inSync 设置为 False，不建议使用
…
…
…
> Ignore value of 'inSync' on BlockBook.get_info

- electrum/wallet.py
如果一个transaction没能拿到时间信息（未确认之类的情况），就返回空的`status_str`。原因是我们将这个`status_str`认为是时间信息直接展示了，原来electrum不是这么考虑，所以抛弃掉其它额外的其它情况。
[OK-331]
No
No
[OK-331]: https://onekeyhq.atlassian.net/browse/OK-331
> OK-331 wallet: only return time string for confirmed transaction

- electrum_gui/android/console.py
将BTC的费率提升成5/2/1个区块的费率，对应 [OK-238] 的改动。
排序和其它币种的返回保持一致，从慢到快。
[OK-3097]
No
No
[OK-238]: https://onekeyhq.atlassian.net/browse/OK-238
[OK-3097]: https://onekeyhq.atlassian.net/browse/OK-3097
> OK-3097: btc: return faster fees

- electrum_gui/android/console.py
- electrum_gui/common/transaction/daos.py
- electrum_gui/common/transaction/manager.py
如果交易被 transaction manager 记录过，直接通过 transaction manager 获取
https://onekeyhq.atlassian.net/browse/OK-3159
…
…
> OK-2875: get transaction from transaction manager

- electrum_gui/android/console.py
获取硬件派生钱包之前清空hw_info，否则创建失败会有残留数据
[OK-3397]
iOS
硬件创建这里的流程需要大改，具体见 [OK-3397] 中的讨论
[OK-3397]: https://onekeyhq.atlassian.net/browse/OK-3397
[OK-3397]: https://onekeyhq.atlassian.net/browse/OK-3397
> OK-3397 Clear hw_info before getting xpub for hw derived wallets

- electrum_gui/android/console.py
- electrum_gui/common/coin/data.py
- electrum_gui/common/conf/chains.py
小改善，用shortname而非处理过后的chain code来命名账户，原因是很多时候chain code不一定和shortname保持一致，前者不好改动，后者可能变化。典型的例子是`okt`->`OEC`。
[OK-3304] 相关
No
No
[OK-3304]: https://onekeyhq.atlassian.net/browse/OK-3304
> use chain shortname instead of chain code to name accounts

- electrum/eth_wallet.py
用decimal.Decimal(0)作为main_balance的默认值
[OK-3799]
No
No
[OK-3799]: https://onekeyhq.atlassian.net/browse/OK-3799
> OK-3799 eth_wallet: use decimal.Decimal(0) as default main balance
