OneKeyHQ/electrum

- contrib/requirements/requirements.txt
- electrum/abi.json
- electrum/constants.py
- electrum/eth_contract.py
- electrum/eth_transaction.py
- electrum/eth_wallet.py
- electrum/keystore.py
- electrum/pywalib.py
- electrum/wallet_db.py
- electrum_gui/android/console.py
> Support create multiple account

- android/app/src/main/java/org/haobtc/onekey/utils/Daemon.java
- electrum/keystore.py
- electrum/util.py
- electrum_gui/android/console.py
- electrum_gui/android/custom_objc.py
- electrum_gui/android/ioscallback.py
- electrum_gui/android/test.py
- electrum_gui/android/uikit_bindings/__init__.py
- electrum_gui/android/uikit_bindings/foundation.py
- electrum_gui/android/uikit_bindings/uikit.py
2.Support serialize privkey and standard privkey when create wallet by import privkey
3.Unified callback method
> 1.Support no name was set when creating the wallet

- electrum/keystore.py
- electrum/wallet.py
- electrum_gui/android/console.py
2.Fixbug when update wallet password
> 1.Password verification required to delete wallet

- electrum_gui/android/console.py
- electrum_gui/android/ioscallback.py
- electrum_gui/android/utils.py
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/make_ios_project.sh
> 1. optimize python ticker code

- electrum_gui/android/console.py
2.Fix the bug of recovery wallet
> 1.Modify the return value for get_all_wallet_balance_api

- electrum/MutiBase.py
- electrum/constants.py
- electrum/eth_servers.json
- electrum/eth_wallet.py
- electrum/pywalib.py
- electrum/util.py
- electrum_gui/android/DerivedInfo.py
- electrum_gui/android/console.py
- electrum_gui/android/utils.py
2.Fix bugs
3.Rewrite delete wallet api
> 1.Support bsc and eth through config

- electrum/eth_servers.json
- electrum/eth_wallet.py
- electrum/keystore.py
- electrum/pywalib.py
- electrum_gui/android/DerivedInfo.py
- electrum_gui/android/console.py
2.Solve the problem that assets can't be synchronized
3.Add mnemonic verify api
4.FixBug for ETH
5.FixBug when send is max
6.Add server connect when set sync host server
> 1.FixBug for BTC

- electrum_gui/android/console.py
merge create_btc and create_eth api
> Support specified name when get backup status

- electrum/MutiBase.py
- electrum/daemon.py
- electrum/eth_wallet.py
- electrum/storage.py
- electrum/wallet.py
- electrum_gui/android/console.py
1.Support save file to os as sha256(address)
2.Add verify_legality api
> FixBug for BTC

- ios/CustomCode/Modules/Base/OKButton.m
- ios/CustomCode/Modules/Manager/OKWalletManager.h
- ios/CustomCode/Modules/Manager/OKWalletManager.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKDeleteBackUpTipsController.h
- ios/CustomCode/Modules/Tab_Mine/Controller/OKDeleteWalletTipsViewController.h
- ios/CustomCode/Modules/Tab_Mine/Controller/OKDeleteWalletTipsViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKHDWalletViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKManagerHDViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKExportTipsViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxListViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletDetailViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tab_Wallet/Tab_Wallet.storyboard
- ios/CustomCode/Modules/Third/MLMSegmentPageView/MLMSegmentScroll.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
Fix stuck bugs ， Delete  separate wallet UI
> Fix stuck bugs ， Delete  separate wallet UI

- electrum/wallet.py
- electrum_gui/android/DerivedInfo.py
- electrum_gui/android/console.py
这个PR主要做了两个工作
1.对硬件部分代码进行详细测试
2.整理代码，针对软件只保存一个HD钱包信息（之前针对每种币都保存了一个钱包信息，配置文件中派生信息的key是每个钱包的xpub，现在改成了BTC account_id=0对应的钱包的加密seed）
3.创建钱包的时候 增加返回值（用于select_wallet查找文件的key值）
> 整理代码 并修改部分bug

- electrum_gui/android/console.py
> Unified return format of wallet creation

- ios/CustomCode/Modules/PassWord/Controller/OKBiologicalViewController.h
- ios/CustomCode/Modules/PassWord/Controller/OKBiologicalViewController.m
- ios/CustomCode/Modules/PassWord/Controller/OKPwdViewController.m
- ios/CustomCode/Modules/PassWord/View/CLPasswordInputView.m
- ios/CustomCode/Modules/Restore/Controller/OKWordImportVC.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKAllAssetsViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKHDWalletViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKMineViewController.m
- ios/CustomCode/Modules/Tab_Mine/View/OKMineTableViewCell.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tools/OKTools.h
- ios/CustomCode/Modules/Tools/OKTools.m
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.m
Search for all assets, fix bugs
> Search for all assets, fix bugs

- ios/CustomCode/Modules/Tab_Mine/Controller/OKMineViewController.m
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
No Wallet，Please go to create a wallet first
> No Wallet，Please go to create a wallet first

- ios/CustomCode/Modules/Restore/Controller/OKWordImportVC.m
- ios/CustomCode/Modules/Tab_Wallet/Model/OKSendTxPreModel.h
- ios/CustomCode/Modules/Tab_Wallet/Model/OKSendTxPreModel.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendTxPreInfoViewController.h
- ios/CustomCode/Modules/Tab_Wallet/OKSendTxPreInfoViewController.m
- ios/CustomCode/Modules/Tab_Wallet/Tab_Wallet.storyboard
- ios/CustomCode/Modules/Tab_Wallet/View/OKAssetTableViewCell.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
> Trade preview interface

- electrum/simple_config.py
- electrum/util.py
- electrum_gui/android/console.py
1.不输入output和value的情况下获取fee信息
2.修改群里提的 恢复时报错问题
3.修改给用户的报错信息
> Add get fee interface without entering the output and value

- electrum_gui/android/console.py
> Update translation information

- ios/CustomCode/Modules/PassWord/YZAuthID/YZAuthID.h
- ios/CustomCode/Modules/Restore/Controller/OKBackUpViewController.m
- ios/CustomCode/Modules/Restore/Controller/OKWordImportVC.m
- ios/CustomCode/Modules/Restore/Controller/OKYouareDoneViewController.m
- ios/CustomCode/Modules/Restore/Model/OKFindWalletTableViewCellModel.h
- ios/CustomCode/Modules/Restore/View/OKFindWalletTableViewCell.m
- ios/CustomCode/Modules/Restore/View/OKWordImportView.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKDeleteWalletTipsViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKHDWalletViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKManagerHDViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKPrivateKeyExportViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxListViewController.h
- ios/CustomCode/Modules/Tab_Wallet/OKTxListViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletDetailViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/WalletList/ViewController/OKSetWalletNameViewController.m
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.m
- ios/CustomCode/OneKeyImport.h
- ios/Resources/zh-Hans.lproj/Localizable.strings
> Face to create

- electrum/network.py
- electrum/util.py
- electrum_gui/android/console.py
主要解决两个问题：
1.当发送金额太小时 提醒用户
2.本地代码已经支持根据设置语言切换中英文用户提醒
> Too small a balance to alert the user

- electrum/MutiBase.py
- electrum_gui/android/console.py
> Solve the problem of inconsistent verification addresses

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/SetHDWalletPassActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/SetLongPassActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/FindBackupOnlyDeviceActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/RecoveryHardwareOnceWallet.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
- android/app/src/main/res/layout/active_successful_fragment.xml
- android/app/src/main/res/layout/looking_for_once_wallet.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
> add extra limits when recovery local hd from hardware

- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/View/OKWalletInputFeeView.h
- ios/CustomCode/Modules/Tab_Wallet/View/OKWalletInputFeeView.m
- ios/CustomCode/Modules/Tab_Wallet/View/OKWalletInputFeeView.xib
Custom rate   OneKeyHQ/TaskHub#379
> Custom rate

- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Restore/Controller/OKFindFollowingWalletController.m
- ios/CustomCode/Modules/Restore/Controller/OKTakeCareMnemonicViewController.h
- ios/CustomCode/Modules/Restore/Controller/OKTakeCareMnemonicViewController.m
- ios/CustomCode/Modules/Restore/Controller/OKWordImportVC.m
- ios/CustomCode/Modules/Restore/Controller/importWords.storyboard
- ios/CustomCode/Modules/Tab_Wallet/OKReceiveCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxDetailViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tab_Wallet/Tab_Wallet.storyboard
- ios/CustomCode/Modules/Tab_Wallet/View/OKTxTableViewCell.m
- ios/CustomCode/Modules/Tools/OKTools.h
- ios/CustomCode/Modules/Tools/OKTools.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
popup prompts the user to make a backup  OneKeyHQ/TaskHub#362
> popup prompts the user to make a backup

- electrum_gui/android/console.py
1.硬件恢复的时候增加device_Id信息
2.去掉list_wallets 返回的信息里边device_id多的一对双引号（因为获取设备ID的接口之前是提供给客户端使用的，我给客户端返回的是json格式，现在onekey已经不在使用这个接口了，只有内部函数使用，所以 把格式化的操作去掉了）
https://github.com/OneKeyHQ/TaskHub/issues/409
> Supports hardware recovery wallet when returning device id

- android/app/src/main/java/org/haobtc/onekey/activities/ResetAppActivity.java
- android/app/src/main/java/org/haobtc/onekey/constant/ApiService.java
- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/constant/PyConstant.java
- android/app/src/main/java/org/haobtc/onekey/event/NameSettedEvent.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/ChooseImportMethodActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateDeriveChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateWalletChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SoftWalletNameSettingActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/CustomBackupDialog.java
- android/app/src/main/java/org/haobtc/onekey/utils/NavUtils.java
- android/app/src/main/res/layout/activity_hd_wallet_detail.xml
> add select wallet type

- electrum/MutiBase.py
- electrum/plugins/trezor/clientbase.py
- electrum_gui/android/console.py
> Solve the problem of hardware creation wallet error after adding the selected address type

- android/app/src/main/java/org/haobtc/onekey/activities/ResetAppActivity.java
- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/constant/PyConstant.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/DeleteWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/HDWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateDeriveChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateWalletChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseDialogFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/ReStartDialog.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/CustomReSetBottomPopup.java
- android/app/src/main/java/org/haobtc/onekey/utils/NavUtils.java
- android/app/src/main/res/layout/dialog_restart.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/strings.xml
- android/zxinglibrary/src/main/java/com/yzq/zxinglibrary/android/CaptureActivity.java
- android/zxinglibrary/src/main/java/com/yzq/zxinglibrary/android/CaptureActivityHandler.java
- android/zxinglibrary/src/main/java/com/yzq/zxinglibrary/common/Constant.java
OneKeyHQ/TaskHub#431,OneKeyHQ/TaskHub#354
> add new function and fix bug

- electrum/coinchooser.py
- electrum/util.py
- electrum_gui/android/console.py
1.修复本地有一个未确认的交易就不能正常发币问题
2.修复重置app内存清除不干净问题
3.修复小bugs
https://github.com/OneKeyHQ/TaskHub/issues/450
> Solve the problem of coin issuance failure with unconfirmed transactions

- android/app/src/main/java/org/haobtc/onekey/activities/settings/HardwareDetailsActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
- android/app/src/main/java/org/haobtc/onekey/adapter/BixinkeyManagerAdapter.java
- android/app/src/main/java/org/haobtc/onekey/manager/BleManager.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/MindFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/ActivateColdWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/ConfirmOnHardWareActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/CreatePersonalWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/FindBackupOnlyDeviceActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/HardwareUpgradeActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/InputPinOnHardware.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/RecoveryHardwareOnceWallet.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/RequestLocationPermissionsDialog.java
- android/app/src/main/res/layout/check_xpub.xml
- android/app/src/main/res/layout/hardware_upgrade_fragment.xml
- android/app/src/main/res/values-zh/strings.xml
> 1. add new feature deal with pin on device 2.fix display logic error

- android/app/src/main/java/org/haobtc/onekey/adapter/OnekeyTxListAdapter.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/RecoverHdWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/ReceiveHDActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/RecoveryWalletFromHdFragment.java
- android/app/src/main/java/org/haobtc/onekey/utils/MyDialog.java
- android/app/src/main/res/layout/activity_recovery_choose_wallet.xml
- android/app/src/main/res/layout/choose_hd_wallet_item.xml
- android/app/src/main/res/layout/fragment_mind.xml
- android/app/src/main/res/layout/fragment_wallet.xml
- android/app/src/main/res/layout/looking_for_once_wallet.xml
OneKeyHQ/TaskHub#491
OneKeyHQ/TaskHub#476
OneKeyHQ/TaskHub#473
OneKeyHQ/TaskHub#468
OneKeyHQ/TaskHub#464
OneKeyHQ/TaskHub#458
OneKeyHQ/TaskHub#445
> 1.Optimized recovery HD Wallet 2.Modify recovery hardware Wallet

- android/app/src/main/java/org/haobtc/onekey/activities/transaction/CheckChainDetailWebActivity.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/RecoverHdWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/FindBackupOnlyDeviceActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/RecoveryHardwareOnceWallet.java
- android/app/src/main/java/org/haobtc/onekey/utils/MyDialog.java
OneKeyHQ/TaskHub#491
OneKeyHQ/TaskHub#487
OneKeyHQ/TaskHub#473
> Backup wallet status modification

- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassActivity.java
> fix 部分机型：输密码到钱包备份页面键盘会再次弹起在落下

- electrum_gui/android/console.py
https://github.com/OneKeyHQ/TaskHub/issues/484
增加返回类型 方便app展示icon
> Add number to facilitate app display icon

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/RecoveryWalletFromHdFragment.java
- android/app/src/main/res/layout/choose_hd_wallet_item.xml
- android/app/src/main/res/layout/looking_for_once_wallet.xml
> fix some display error

- android/app/src/main/java/org/haobtc/onekey/activities/LanguageSettingActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/ResetAppActivity.java
- android/app/src/main/java/org/haobtc/onekey/event/GotPassEvent.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/ChooseImportMethodActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/importmethod/ImportMnemonicActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/importmethod/ImportPrivateKeyActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/importmethod/ImportWalletSetNameActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateDeriveChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateWalletChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/SelectWalletTypeDialog.java
- android/app/src/main/java/org/haobtc/onekey/utils/NavUtils.java
- android/app/src/main/res/layout/activity_hd_wallet_detail.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
OneKeyHQ/TaskHub#431(添加私钥导入和助记词导入选择类型功能),OneKeyHQ/TaskHub#372,OneKeyHQ/TaskHub#354(删除HD子钱包这一版先隐藏入口),OneKeyHQ/TaskHub#358
> fix bug and add function

- android/app/src/main/java/org/haobtc/onekey/constant/PyConstant.java
- electrum_gui/android/tx_db.py
> optimize sqllite use

- android/app/src/main/java/org/haobtc/onekey/MainActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/Send2ManyActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/SendOne2OneMainPageActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/settings/recovery_set/RecoveryActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/sign/CheckSignActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/importmethod/WatchWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/widget/PointLengthFilter.java
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
…
OneKeyHQ/TaskHub#504,OneKeyHQ/TaskHub#431
- [x ] Bugfix
- [ x] Feature
…
…
> fix transfer bug，add create hdWallet select type

- electrum_gui/android/console.py
Support bip72 QR code decode
OneKeyHQ/TaskHub#502
OneKeyHQ/electrum#190
test demo https://bitpay.com/demos/
None
> server:support bip72 QR code decode

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/haobtc/onekey/activities/AboutActivity.java
- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/AppUpdateDialog.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/HardwareUpgradeFragment.java
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
- electrum_gui/android/tx_db.py
- fix update dialog description can't scroll bug
OneKeyHQ/TaskHub#507,
OneKeyHQ/TaskHub#506
local
> fix update dialog description can't scroll bug

- electrum/plugins/trezor/clientbase.py
Slove the problem that hardware wallets with address type p2pkh cannot send
No
No
> Slove the problem that hardware wallets with address type p2pkh cannot send

- android/app/src/main/java/org/haobtc/onekey/activities/AboutActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/transaction/CheckChainDetailWebActivity.java
- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/importmethod/ImportPrivateKeyActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/importmethod/WatchWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/DetailTransactionActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/ReceiveHDActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/CustomizeFeeDialog.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/UnBackupTipDialog.java
- android/app/src/main/res/layout/custom_fee.xml
- android/app/src/main/res/layout/unbackup_tip.xml
- android/app/src/main/res/values/strings.xml
1.Optimize custom rates 2.Modify the error prompt 3.Interface adaptation in English
OneKeyHQ/TaskHub#510
OneKeyHQ/TaskHub#505
OneKeyHQ/TaskHub#445
OneKeyHQ/TaskHub#145
OneKeyHQ/TaskHub#507
local
> 1.Optimize custom rates 2.Modify the error prompt

- android/app/src/main/java/org/haobtc/onekey/business/qrdecode/QRDecode.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/res/layout/activity_send_hd.xml
+ add scan code on transfer page
+ main page scan code transfer add amount
OneKeyHQ/TaskHub#502
#190
Local test
None
> Add scan code on transfer page

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionDetailWalletActivity.java
+ Optimize trading list weak network jam problem
OneKeyHQ/TaskHub#489
Local Test
None
> Optimize trading list weak network jam problem

- android/app/src/main/java/org/haobtc/onekey/activities/jointwallet/MultiSigWalletCreator.java
- android/app/src/main/java/org/haobtc/onekey/activities/settings/CurrencyActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/sign/CheckSignActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/ReceiveHDActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/CreatePersonalWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/SelectAddressTypeDialog.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/CustomWatchWalletDialog.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/SelectWalletTypeDialog.java
- android/app/src/main/java/org/haobtc/onekey/utils/CoinUtils.java
- android/app/src/main/res/layout/dialog_watch_wallet_qr.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
fix transfer accounts bug and fix watch wallet ui bug
OneKeyHQ/TaskHub#518,OneKeyHQ/TaskHub#517,OneKeyHQ/TaskHub#382
- [ x] Bugfix
…
…
> fix transfer accounts bug

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
…tomatically calculate the handling fee
+ 修复主页扫码，如果二维码带金额，转账页面转账按钮不可点按。
+ 修复主页扫码、转账页面扫码，手续费不更新。
OneKeyHQ/TaskHub#531
Local test
修改完之后，如果二维码中包含的金额是 1 BTC，账户余额只有 0.5BTC ，扫码跳转后金额输入框的金额将变成 0.5BTC。
> Fix main page with scan code transfer button disabled

- android/app/src/main/java/org/haobtc/onekey/activities/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/manager/BleManager.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseActivity.java
- android/app/src/main/res/layout/vervify_hardware_fragment.xml
1.  fix display error
2. move bluetooth connect operation to independent thread instead of main
OneKeyHQ/TaskHub#507,
OneKeyHQ/TaskHub#529,
OneKeyHQ/TaskHub#532,
optimize bluetooth connect operation 
local
> 1. fix display error 2. move bl connect operation to independent thread

- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassActivity.java
- android/app/src/main/java/org/haobtc/onekey/utils/ViewHeightStatusDetector.java
- android/app/src/main/res/layout/activity_search_devices.xml
+ fix the password page space is insufficient View overlap
+ fix device search page view overlap
OneKeyHQ/TaskHub#515
Local test
None
> Fix part of the page views overlap

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/MindFragment.java
+ fix mind page clicks repeatedly
OneKeyHQ/TaskHub#533
Local test
None
> Fix mind page clicks repeatedly

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
+ fix transfer to confirm popup account name
OneKeyHQ/TaskHub#537
Local test
None
> Fix transfer to confirm popup account name

- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/ReceiveHDActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseFragment.java
- android/app/src/main/java/org/haobtc/onekey/utils/LanguageUtils.java
- android/app/src/main/res/layout/reset_app_confirm_dialog.xml
fix reset language bug and some ui bug
no link，self testing
- [ x] Bugfix
…
…
> fix reset language bug and some ui bug

- electrum/util.py
- electrum/wallet.py
- electrum_gui/android/console.py
Support for undoing the restore wallet process
no
App for android 
no
> Support for undoing the restore wallet process

- android/app/src/main/java/org/haobtc/onekey/ui/dialog/OpenLocationServiceDialog.java
- android/app/src/main/res/layout/need_location_tip.xml
fix dialog displays incomplete on Samsung device
OneKeyHQ/TaskHub#544
Local test
None
> Fix dialog displays incomplete

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/ReceiveHDActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/res/layout/activity_receive_h_d.xml
1.Optimize sharing function 2.Modify home page UI
OneKeyHQ/TaskHub#534
OneKeyHQ/TaskHub#525
local
no
> 1.Optimize sharing function 2.Modify home page UI

- android/app/src/main/java/org/haobtc/onekey/manager/BleManager.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/RecoveryHardwareOnceWallet.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/adapter/BleDeviceAdapter.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/ConnectingDialog.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/OpenLocationServiceDialog.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/RequestLocationPermissionsDialog.java
- android/app/src/main/res/drawable/ble_item_bk_selector.xml
- android/app/src/main/res/layout/bluetooth_device_list_item.xml
- android/app/src/main/res/layout/connecting_dialog.xml
1.  optimize ble connect process
2.  fix location service and location permission request process
- [] Bugfix
local
> 1. optimize ble connect process 2. fix location service and location

- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassActivity.java
- android/app/src/main/java/org/haobtc/onekey/utils/ViewHeightStatusDetector.java
- android/app/src/main/res/layout/soft_pass_activity.xml
+ optimize password page prompt to show animation
OneKeyHQ/TaskHub#515
Local test
None
> Optimize password page prompt to show animation

- electrum_gui/android/tx_db.py
Organize the code about db 
No
No
> Organize the code

- android/app/src/main/java/org/haobtc/onekey/manager/BleManager.java
+ fix permission dialog bounces multiple times when looking for the device
OneKeyHQ/TaskHub#507
Local test
None
> Fix permission dialog bounces multiple times

- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
+ fix aliyun cloud test error
OneKeyHQ/TaskHub#549
No test
有两项 log 不全无法定位异常位置。
> Fix aliyun cloud test error

- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassActivity.java
+ fix long password mode enters password authentication crash
+ fix verification password error message error
OneKeyHQ/TaskHub#554
OneKeyHQ/TaskHub#505
Local test
None
> Fix long password crash

- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/RequestLocationPermissionsDialog.java
+ Optimize no permissions to find device pages return before
OneKeyHQ/TaskHub#507
Local test
None
> Optimize no permissions to find device pages return before

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/haobtc/onekey/activities/service/BleService.java
- android/app/src/main/java/org/haobtc/onekey/utils/CustomerUsbManager.java
+ fix component leakage problems
+ delete xutils library
OneKeyHQ/TaskHub#550
+ 剩余的三个组件暴漏问题为第三方库以及 Android library 内的行为。
+ 关于此次修改是否影响蓝牙硬件配对，需测试，目前手头没有硬件设备。
> Fix component leakage problems

- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ modify password page change long password hint content
OneKeyHQ/TaskHub#515
Local test
None
> Modify password page change long password hint content

- android/app/src/main/res/layout/activity_check_mnemonic.xml
- android/app/src/main/res/layout/activity_export_private.xml
- android/app/src/main/res/layout/activity_hd_root_mnemonics.xml
- android/app/src/main/res/layout/activity_import_keystore.xml
- android/app/src/main/res/layout/activity_import_mnemonic.xml
- android/app/src/main/res/layout/activity_import_private_key.xml
- android/app/src/main/res/layout/activity_recover_hd_wallet.xml
- android/app/src/main/res/layout/fragment_import_mnemonic_to_device.xml
fix ui adapter bug
OneKeyHQ/TaskHub#532
…
…
> fix ui adapter bug

- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
> update submodule index

- android/app/build.gradle
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassActivity.java
- android/app/src/main/res/layout/soft_pass_activity.xml
- electrum_gui/android/console.py
fix cancel error when recovery wallet  by hardware
OneKeyHQ/TaskHub#495
local
> fix cancel error when recovery wallet  by hardware

- android/app/src/main/java/org/haobtc/onekey/activities/settings/HardwareDetailsActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/backup/CheckMnemonicActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/ReceiveHDActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/VerifyHardwareActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/DeleteLocalDeviceDialog.java
- android/app/src/main/res/layout/active_successful_fragment.xml
- android/app/src/main/res/layout/activity_choose_import_method.xml
- android/app/src/main/res/layout/activity_serviceonline.xml
- android/app/src/main/res/layout/activity_somemore.xml
- android/app/src/main/res/layout/app_upgrade_dialog.xml
- android/app/src/main/res/layout/confirm_on_hardware_activity.xml
- android/app/src/main/res/layout/delete_device_dialog.xml
- android/app/src/main/res/layout/fragment_update_pin_confirm.xml
- android/app/src/main/res/layout/fragment_verify_result.xml
- android/app/src/main/res/layout/fragment_wallet.xml
- android/app/src/main/res/layout/hardware_upgrade_fragment.xml
- android/app/src/main/res/layout/title_layout.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
Some pages are suitable in English state
OneKeyHQ/TaskHub#529
local
no
> Some pages are suitable in English state

- android/app/build.gradle
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- electrum_gui/android/console.py
fix recovery canel bug in python
OneKeyHQ/TaskHub#495
local
> fix recovery canel bug in python

- android/app/src/main/java/org/haobtc/onekey/activities/base/ActivityLifeCycleCallback.java
- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/bean/CreateWalletBean.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/RecoverHdWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/importmethod/ImportMnemonicActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/utils/BleUtils.java
- android/zxinglibrary/src/main/java/com/yzq/zxinglibrary/camera/CameraManager.java
fix connect hardwear transfer crash,fix bugly report bug
OneKeyHQ/TaskHub#556,OneKeyHQ/TaskHub#557
…
…
> fix connect hardwear transfer crash,fix bugly report bug

- android/app/build.gradle
- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/activities/settings/HardwareDetailsActivity.java
- android/app/src/main/java/org/haobtc/onekey/asynctask/BusinessAsyncTask.java
- android/app/src/main/java/org/haobtc/onekey/bean/CurrentFeeDetails.java
- android/app/src/main/java/org/haobtc/onekey/bean/CustomFeeInfo.java
- android/app/src/main/java/org/haobtc/onekey/bean/HardwareVerifyResponse.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/HomeOneKeyActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/RecoverHdWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/ChooseImportMethodActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/HardwareRecoveryActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateDeriveChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateWalletChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/HardwareUpgradeActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/HardwareUpgradeFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/HardwareUpgradingFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/VerifyConnFragment.java
- android/app/src/main/res/layout/hardware_upgrade_fragment.xml
- android/app/src/main/res/layout/hardware_upgrading_fragment.xml
1. optimize get hardware features process from Sync to Async
2. clean code
3. add nice android log framework
none
local
> optimize get hardware features process from Sync to Async

- android/app/src/main/java/org/haobtc/onekey/activities/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseFragment.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/NetworkViewModel.java
+ optimize refresh the wallet balance according to the network status
OneKeyHQ/TaskHub#489
Local test
None
> Optimize refresh the wallet balance according to the network status

- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/manager/MySPManager.java
- android/app/src/main/java/org/haobtc/onekey/manager/PreferencesManager.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/CustomizeFeeDialog.java
- android/app/src/main/res/values/strings.xml
…rate;
optimize the custom feerate dialog
OneKeyHQ/TaskHub#528
…
…
> optimize the custom feerate dialog

- android/app/src/main/java/org/haobtc/onekey/onekeys/HomeOneKeyActivity.java
Fix software upgrade crash
OneKeyHQ/TaskHub#567
Local test
None
> Fix software upgrade failed

- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/importmethod/ImportPrivateKeyActivity.java
+ fix private key repeats the import hint
OneKeyHQ/TaskHub#538
Local test
None
> Fix private key repeats the import hint

- electrum_gui/android/console.py
1.Not support crete dust tx
https://github.com/OneKeyHQ/TaskHub/issues/552
…
> Not support crete dust tx

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/DetailTransactionActivity.java
Fix no online transaction details ANR
OneKeyHQ/TaskHub#489
Local test
None
> Fix no online transaction details ANR

- android/app/src/main/java/org/haobtc/onekey/ui/adapter/OnceWalletAdapter.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/RecoveryWalletFromHdFragment.java
+ Optimize the recovery wallet experience from hardware
OneKeyHQ/TaskHub#465
Local test
None
> Optimize the recovery wallet experience from hardware

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/haobtc/onekey/activities/base/ApplicationObserver.java
- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/activities/sign/CheckSignActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
- android/app/src/main/res/layout/activity_check_sign.xml
- android/app/src/main/res/layout/hardware_upgrade_fragment.xml
- electrum/plugins/trezor/trezor.py
- electrum_gui/android/console.py
1. modify ble disconnect logic 
2. fix sign page dispaly error
OneKeyHQ/TaskHub#571,
OneKeyHQ/TaskHub#566,
OneKeyHQ/TaskHub#563,
OneKeyHQ/TaskHub#562
local
> 1.modify ble disconnect logic 2. fix sign page dispaly error

- android/app/src/main/java/org/haobtc/onekey/adapter/WalletListAdapter.java
- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/constant/PyConstant.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/DeleteWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/HDWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/WalletManageActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/BackupRequireDialog.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/DeleteWalletTipsDialog.java
- electrum_gui/android/console.py
Support for delete HD wallet with account_id is 0
https://github.com/OneKeyHQ/TaskHub/issues/354
App for andorid
…
> Support for delete HD wallet with account_id is 0

- electrum_gui/android/console.py
Clicking on the details page immediately after send successful shows incorrect data
https://github.com/OneKeyHQ/TaskHub/issues/519
…
> Clicking on the details page immediately after send successful shows incorrect data

- android/build.gradle
1. update chaquo version from 8.0.1 to 9.1.0 
2.  gradle version from 4.0.1 to 4.0.2
local
> update chaquo version from 8.0.1 to 9.1.0 and gradle from 4.0.1 to 4.0.2

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/haobtc/onekey/activities/AboutActivity.java
+ Fix some models failed to upgrade
OneKeyHQ/TaskHub#567
OneKeyHQ/TaskHub#550
Local test
紧急更新，影响线上版本。
> Fix some models failed to upgrade

- android/app/src/main/java/org/haobtc/onekey/onekeys/backup/CheckMnemonicActivity.java
fix check mnemonic bug
OneKeyHQ/TaskHub#572
…
…
> fix check mnemonic bug

- electrum/eth_wallet.py
- electrum_gui/android/console.py
1. Abstract_Eth_Wallet.contacts 建议用合约地址作为 key，保持唯一
2. Imported_Eth_Wallet.import_addresses 方法采用 isAddress 判断地址是否合法
N/A
1. 导入多个不同地址但相同 symbol 的合约，并测试发币
2. 只读钱包导入全小写地址
@shuaiLiWang 有空帮忙看下
> ETH - Fix Bugs

- android/app/src/main/java/org/haobtc/onekey/activities/settings/OneKeyManageActivity.java
- android/app/src/main/java/org/haobtc/onekey/bean/HardwareFeatures.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/HardwareUpgradeActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
> modify force update logic

- electrum/locale/messages.pot
> Updated translation

- android/app/src/main/java/org/haobtc/onekey/activities/base/ActivityLifeCycleCallback.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/backup/BackupGuideActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/HDWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/WalletManageActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
Add the name parameter to fix the problem of obtaining mnemonic
OneKeyHQ/TaskHub#592
…
…
> Add the name parameter to fix the problem of obtaining mnemonic

- android/app/src/main/java/org/haobtc/onekey/business/wallet/AccountManager.java
- android/app/src/main/java/org/haobtc/onekey/business/wallet/BalanceManager.java
- android/app/src/main/java/org/haobtc/onekey/business/wallet/SystemConfigManager.java
- android/app/src/main/java/org/haobtc/onekey/event/BackupCompleteEvent.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/HomeOneKeyActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/backup/CheckMnemonicActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateWalletChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/BackupDialog.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
+ Optimize wallet homepage logic
None
Local test
None
> Optimize wallet homepage logic

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/HDWalletActivity.java
Add Create HD and Restore Wallet in My Page
OneKeyHQ/TaskHub#580
…
…
> Add Create HD and Restore Wallet in My Page

- android/app/src/main/java/org/haobtc/onekey/activities/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/business/wallet/BalanceManager.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/DetailTransactionActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionDetailWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
1. Fixed transfer record page, weak network crash.
2. Optimize the amount of money display on the home page is not timely.
3. Optimize the transfer record page, and the amount will change according to the actual balance.
OneKeyHQ/TaskHub#581
Local test
None
> Optimize trading details for weak net conditions

- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
+ Optimized hardware signature error message in English only
OneKeyHQ/TaskHub#577
Local test
None
> Optimize hardware signature error hint

- ios/make_ios_project.sh
fix status bar appearance. 首页的 StatusBarStyle 应该设置成 Light.
https://github.com/OneKeyHQ/TaskHub/issues/319
iPhone xs Max iOS 14.2
…
> iOS fix: status bar appearance.

- android/app/src/main/java/org/haobtc/onekey/adapter/FragmentMainAdapter.java
- android/app/src/main/java/org/haobtc/onekey/bean/TabEntity.java
- android/app/src/main/java/org/haobtc/onekey/manager/MainFragmentFactory.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/HomeOneKeyActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/widget/MsgView.java
- android/app/src/main/java/org/haobtc/onekey/ui/widget/NoScrollViewPager.java
- android/app/src/main/java/org/haobtc/onekey/ui/widget/tablayout/CommonTabLayout.java
- android/app/src/main/java/org/haobtc/onekey/ui/widget/tablayout/CustomTabEntity.java
- android/app/src/main/java/org/haobtc/onekey/ui/widget/tablayout/FragmentChangeManager.java
- android/app/src/main/java/org/haobtc/onekey/ui/widget/tablayout/OnTabSelectListener.java
- android/app/src/main/java/org/haobtc/onekey/utils/UnreadMsgUtils.java
- android/app/src/main/res/layout/activity_home_onekey.xml
- android/app/src/main/res/layout/flyco_layout_tab_bottom.xml
- android/app/src/main/res/layout/flyco_layout_tab_left.xml
- android/app/src/main/res/layout/flyco_layout_tab_right.xml
- android/app/src/main/res/layout/flyco_layout_tab_top.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/styles.xml
Optimize the homepage frame
OneKeyHQ/TaskHub#564
…
…
> Optimize the homepage frame

- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
+ Optimize balance ViewModel filters duplicate values
#277
Local test
None
> Android:Wallet optimize balance ViewModel filters duplicate values

- android/app/src/main/java/org/haobtc/onekey/bean/FiatUnitSymbolBean.java
- android/app/src/main/java/org/haobtc/onekey/bean/WalletBalanceFiatVo.java
- android/app/src/main/java/org/haobtc/onekey/bean/WalletBalanceVo.java
- android/app/src/main/java/org/haobtc/onekey/business/wallet/SystemConfigManager.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionDetailWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
+ Modify AppWalletViewModel escrow amount unit
None
Local test
None
> Modify appWalletViewModel escrow amount unit

- electrum_gui/android/console.py
+ Fix watch wallet prompt backup
OneKeyHQ/TaskHub#601
Local test
@shuaiLiWang 帮忙 review 一下。
> Fix watch wallet prompt backup

- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/ChooseImportMethodActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/importmethod/WatchWalletActivity.java
+ Optimize the observation wallet page scanning function
OneKeyHQ/TaskHub#601
Local test
None
> Optimize the observation wallet page scanning function

- electrum/eth_servers.json
- electrum/pywalib.py
- electrum/util.py
- electrum/wallet.py
- electrum_gui/android/console.py
1.Support for non-watch-only wallets with the same address to overwrite an existing watch-only wallet
2.Add eth recovery feature
…
python platform
…
> Adding new features

- android/app/src/main/res/layout/fragment_wallet.xml
+ Optimize the homepage slide
OneKeyHQ/TaskHub#610
Local test
None
> Optimize the homepage slide

- android/app/src/main/java/org/haobtc/onekey/activities/TransactionDetailsActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/settings/CurrencyActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
- android/app/src/main/java/org/haobtc/onekey/bean/FiatUnitSymbolBean.java
- android/app/src/main/java/org/haobtc/onekey/business/wallet/BalanceManager.java
- android/app/src/main/java/org/haobtc/onekey/business/wallet/SystemConfigManager.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/AllAssetsActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionDetailWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/CustomizeFeeDialog.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/TransactionConfirmDialog.java
+ 将「法币单位以及符号」和「数字货币单位」设置与获取的统一到 SystemConfigManager.java，默认值也可以方便管理。
+ 有几个页面看着不像我们的页面，没有改，后边可能会删掉。
None
Local test
None
> Optimize unit storage

- electrum_gui/android/console.py
+ 修复无法导入 SortWalletList 模块，引起的创建钱包失败。
OneKeyHQ/TaskHub#612
Local test
@shuaiLiWang 帮忙 review
> Fix import the error

- android/app/src/main/java/org/haobtc/onekey/constant/PyConstant.java
- android/app/src/main/java/org/haobtc/onekey/constant/StringConstant.java
- android/app/src/main/java/org/haobtc/onekey/event/ExitEvent.java
- android/app/src/main/java/org/haobtc/onekey/exception/HardWareExceptions.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/ChooseImportMethodActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/CustomCoverWatchPopup.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/CustomReSetBottomPopup.java
- android/app/src/main/res/layout/activity_hd_wallet_detail.xml
- android/app/src/main/res/layout/app_confirm_dialog_green.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
- electrum_gui/android/console.py
覆盖观察钱包Feature
OneKeyHQ/TaskHub#618，OneKeyHQ/TaskHub#599
…
…
> Covering observation wallet and modify translation

- electrum/pywalib.py
1. 请求 etherscan 需要带上 user-agent
2. get_coin_price 建议找不到价格返回 0
3. 补充缺失的 `@staticmethod` 
N/A
1. 获取自定义币种价格
2. 通过 etherscan 获取交易历史
@shuaiLiWang 麻烦帅姐啦
> ETH - Fix getting transactions from etherscan

- android/app/src/main/java/org/haobtc/onekey/onekeys/HomeOneKeyActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/RecoveryChooseWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/ActivateColdWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
+ Fix import wallet name error
+ Fix there is also a prompt after the hardware backup
OneKeyHQ/TaskHub#611
OneKeyHQ/TaskHub#613
Local test
None
> Fix import backup related functionality

- android/app/src/main/java/org/haobtc/onekey/activities/settings/AnyskServerSetActivity.java
+ Fixed sync server setup ANR
OneKeyHQ/TaskHub#621
Local test
None
> Fixed sync server setup ANR

- android/app/src/main/java/org/haobtc/onekey/activities/LanguageSettingActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/HomeOneKeyActivity.java
- android/app/src/main/java/org/haobtc/onekey/utils/NavUtils.java
+ Optimize to restart App without checking for updates
OneKeyHQ/TaskHub#616
Local test
None
> Optimize to restart App without checking for updates

- android/app/src/main/java/org/haobtc/onekey/activities/settings/BlockChooseActivity.java
- android/app/src/main/java/org/haobtc/onekey/adapter/QuetationChooseAdapter.java
- android/app/src/main/res/layout/activity_block_choose.xml
- android/app/src/main/res/layout/view_block_browser_hint.xml
+ Optimize set up the blockchain browser ui
None
Local test
None
> Optimize set up the blockchain browser ui

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/HDWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassActivity.java
- android/app/src/main/java/org/haobtc/onekey/utils/NavUtils.java
修复主密码已经设置完成还出现再次设置的问题
OneKeyHQ/TaskHub#614
…
…
> Fixed setting master password mode error

- android/app/src/main/java/org/haobtc/onekey/adapter/WalletListAdapter.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
Optimize walletlist hardware type content
OneKeyHQ/TaskHub#624
Local test
None
> Android:Wallet optimize walletlist hardware type content

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/haobtc/onekey/activities/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/business/language/LanguageManager.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseFragment.java
+ 优化 UI 适配的大小，与 UI 设计稿 1:1 等比。
+ 添加 App 不跟随系统字体大小。
+ 优化多语言实现方案，方便其他系统属性的托管。
None
Local test
None
> Optimize UI font size

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
Fixed error with maximum amount of transfer displayed
OneKeyHQ/TaskHub#623
…
…
> Fixed error with maximum amount of transfer displayed

- ios/CustomCode/Modules/Bluetooth/OKBlueManager.h
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Hardware/Model/OKDeviceInfoModel.h
- ios/CustomCode/Modules/Hardware/Model/OKDeviceInfoModel.m
- ios/CustomCode/Modules/ImportWallet/ViewController/OKObserveImportViewController.m
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.m
- ios/Support/OneKey.xcodeproj/project.pbxproj
Get hardware device information
> 1.Get hardware device information

- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/ChooseImportMethodActivity.java
- android/app/src/main/res/layout/fragment_mind.xml
- android/app/src/main/res/layout/fragment_wallet.xml
- electrum_gui/android/console.py
修复覆盖观察钱包时取消之后再次导入报文件已存在
OneKeyHQ/TaskHub#599
…
…
> Fixed overlay observation wallet bug

- android/app/src/main/java/org/haobtc/onekey/ui/activity/HardwareUpgradeActivity.java
- electrum_gui/android/console.py
- electrum_gui/android/tx_db.py
1. fix nrf dfu update bug and cancelabel feature
2. change tx db code style
3. fix transaction broadcast bug
OneKeyHQ/TaskHub#625
local
> fix nrf dfu update bug and cancelabel feature

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionDetailWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionListFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseLazyFragment.java
- android/app/src/main/java/org/haobtc/onekey/utils/MyDialog.java
- android/app/src/main/res/layout/activity_transaction_detail_wallet.xml
- android/app/src/main/res/layout/fragment_transaction_list.xml
+ 修改页面结构，为分页做准备。
OneKeyHQ/TaskHub#581
OneKeyHQ/TaskHub#629
Local test
None
> Optimize the deal details page

- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
+ Handle creating HD wallet display name
+ Fix wallet home page BTC name
Local test
None
> Handle creating HD wallet display name

- android/app/src/main/java/org/haobtc/onekey/activities/base/LunchActivity.java
- android/app/src/main/java/org/haobtc/onekey/adapter/WalletListTypeAdapter.java
- android/app/src/main/java/org/haobtc/onekey/bean/WalletAsset.java
- android/app/src/main/java/org/haobtc/onekey/bean/WalletInfo.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/HDWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/ReceiveHDActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/WalletListViewModel.java
- android/app/src/main/res/layout/ac_base_not_fit_layout.xml
- android/app/src/main/res/layout/activity_receive_h_d.xml
- android/app/src/main/res/layout/activity_wallet_list.xml
- android/app/src/main/res/layout/base_ui_toolbar.xml
- android/app/src/main/res/layout/fragment_mind.xml
- android/app/src/main/res/layout/fragment_wallet.xml
- android/app/src/main/res/layout/item_add_wallet.xml
- android/app/src/main/res/layout/item_no_wallet.xml
- android/app/src/main/res/values/strings.xml
- electrum_gui/android/sort_wallet_list.py
重构钱包列表页面并添加资产排序，更新翻译
OneKeyHQ/TaskHub#347
…
…
> Refactoring the asset list page to add asset sorting

- android/app/src/main/java/org/haobtc/onekey/activities/base/ActivityLifeCycleCallback.java
- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/event/NameSettedEvent.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/ChooseImportMethodActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/importmethod/ImportWalletSetNameActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateDeriveChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateWalletChooseTypeActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SoftWalletNameSettingActivity.java
- android/app/src/main/java/org/haobtc/onekey/utils/NavUtils.java
fixed creating ETH will also create BTC
test myself
…
…
> fixed creating ETH will also create BTC

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionListFragment.java
+ Fix closed page crashes when the transaction record loads
OneKeyHQ/TaskHub#636
Local test
None
> Fix closed page crashes when the transaction record loads

- electrum/locale/messages.pot
Upgrade translation
https://github.com/OneKeyHQ/TaskHub/issues/597
Chinese translation completed before testing
…
> Upgrade translation

- android/app/src/main/java/org/haobtc/onekey/adapter/RecoveryWalletAdapter.java
- android/app/src/main/java/org/haobtc/onekey/adapter/WalletListTypeAdapter.java
- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/IBaseView.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/WalletListViewModel.java
修复恢复钱包时含有eth crash
OneKeyHQ/TaskHub#642
…
…
> fixed  recovery wallet crash when has eth wallet

- android/app/src/main/AndroidManifest.xml
+ Fixed phone landscape screen crashed
None
Local test
None
> Fixed phone landscape screen crashed

- electrum/logging.py
redirect python log to stderr in debug mode, this can make locating the problems easy when developing
local
> redirect python log to stderr in debug mode

- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createfasthd/CreateFastHDSoftWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/importsoft/ImportSoftWalletActivity.java
+ Fixed ETH import issues
OneKeyHQ/TaskHub#663
Local test
None
> Fixed ETH import issues

- electrum_gui/android/console.py
1. 经 Android 客户端提醒，将 `select_wallet` 和 `get_all_wallet_balance ` 返回 wallets 由对象改成数组形式，方便解析
Nope
…
…
> ETH - Adjust APIs

- android/app/src/main/res/layout/fragment_set_wallet_name.xml
+ hardware set wallet name ui
None
Local test
None
> Modify hardware set wallet name ui

- electrum_gui/android/console.py
1.Delete redundant logs
2.Modify return values about create_hd_wallet
No
…
> Modify return values about create_hd_wallet

- android/app/src/main/java/org/haobtc/onekey/manager/BleManager.java
- android/app/src/main/java/org/haobtc/onekey/manager/HardwareCallbackHandler.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
修复低版本蓝牙升级在应该在App上输入Pin码
no issue
…
…
> Low Version Bluetooth Upgrade Enter the PIN code in the App

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/widget/PasteEditText.java
- android/app/src/main/res/layout/activity_send_hd.xml
修复转账地址栏粘贴地址发送按钮未改变
OneKeyHQ/TaskHub#677
…
…
> Fixed transfer address bar paste not refreshing

- electrum/pywalib.py
- electrum_gui/android/console.py
1. 调整 get_default_fee_info, 支持预估 ETH 费率
2. 调整 sign_eth_tx, 支持自定义 gas_limit 和 data
Nope
…
…
> ETH - Enhance sign_eth_tx and get_default_fee_info

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/haobtc/onekey/activities/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/constant/PyConstant.java
- android/app/src/main/java/org/haobtc/onekey/constant/StringConstant.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/ExportKeystoreActivity.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/importsoft/ChooseImportModeFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/importsoft/ImportKeystoreFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/importsoft/ImportPrivateKeyFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/importsoft/ImportSoftWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/importsoft/ImportWatchWalletFragment.java
- android/app/src/main/res/layout/activity_export_keystore.xml
- android/app/src/main/res/layout/activity_hd_wallet_detail.xml
- android/app/src/main/res/layout/fragment_import_keystore.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ Add Keystore import
+ Add Keystore export
+ The account details page supports ETH
OneKeyHQ/TaskHub#618
Local test
None
> Add Keystore import & export

- ios/Support/OneKey-Info.plist
> iOS improvement: Disable "Dark Mode".

- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/RecoverHdWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/RecoveryChooseWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/FindBackupOnlyDeviceActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/RecoveryHardwareOnceWallet.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/RecoveryWalletFromHdFragment.java
+ Fix software hd import
+ Fix hardware hd import
OneKeyHQ/TaskHub#689
Local test
None
> Fix software hd import

- electrum/locale/zh_CN/LC_MESSAGES/electrum.po
- electrum/pywalib.py
- electrum/util.py
- electrum_gui/android/console.py
- electrum_gui/common/basic/dataclass/dataclass.py
- electrum_gui/common/basic/functional/decimal_encoder.py
- electrum_gui/common/basic/functional/require.py
- electrum_gui/common/basic/functional/text.py
- electrum_gui/common/basic/request/enums.py
- electrum_gui/common/basic/request/exceptions.py
- electrum_gui/common/basic/request/interfaces.py
- electrum_gui/common/basic/request/restful.py
- electrum_gui/common/explorer/clients/__init__.py
- electrum_gui/common/explorer/clients/etherscan.py
- electrum_gui/common/explorer/clients/trezor_eth.py
- electrum_gui/common/explorer/data/enums.py
- electrum_gui/common/explorer/data/exceptions.py
- electrum_gui/common/explorer/data/interfaces.py
- electrum_gui/common/explorer/data/objects.py
1. 修复 ETH 无法获取交易历史问题，返回数据格式跟 BTC 完全一样 
2. 在这基础上，感觉原 electrum 项目缺少分层结构化的思想。我根据之前的实践，在 electrum_gui 下新建了 common 目录，目前封装好了 dataclass，restful request 并实现 TrezorETH 和 Etherscan 这两个浏览器实例来获取交易历史等链上数据，后续还会继续扩展。
Nope
1. 获取 ETH 交易记录
后续我会继续扩展 electrum_gui.common， 最终目标是达到添加新币只需要实现指定几个接口即可
> ETH - Fix tx history

- android/app/src/main/java/org/haobtc/onekey/bean/LocalWalletInfo.java
- android/app/src/main/java/org/haobtc/onekey/constant/Vm.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/HDWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
+ Support main wallet list supports ETH
Local test
None
> Support main wallet list supports ETH

- android/app/src/main/res/layout/activity_currency.xml
- android/app/src/main/res/values/strings.xml
+ Add ETH unit setting
Local test
None
> Add ETH unit setting

- .github/workflows/android-lint.yml
- android/app/build.gradle
- android/app/src/GooglePlay/java/org.haobtc.onekey.business.update/AutoCheckUpdate.java
- android/app/src/Onekey/java/org/haobtc/onekey/business/update/AutoCheckUpdate.java
- android/app/src/Onekey/java/org/haobtc/onekey/ui/dialog/AppUpdateDialog.java
- android/app/src/main/java/org/haobtc/onekey/MainActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/AboutActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/SettingActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/HomeOneKeyActivity.java
- android/app/src/main/res/layout/hardware_upgrade_fragment.xml
- android/app/src/main/res/layout/hardware_upgrading_fragment.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ Add the Google Play Channel Pack
+ Optimize and upgrade experience
OneKeyHQ/TaskHub#686
Local test
None
> Add the Google Play Channel Pack

- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.h
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
> iOS: Python-Native communication improvement.

- android/app/src/main/java/org/haobtc/onekey/adapter/WalletListAdapter.java
- android/app/src/main/java/org/haobtc/onekey/business/chain/bitcoin/BitcoinService.kt
- android/app/src/main/java/org/haobtc/onekey/business/chain/ethereum/EthService.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/DetailTransactionActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionListFragment.java
+ Transaction records support ETH
+ Fixed main wallet page not showing HD
Local test
None
> Transaction records support ETH

- android/app/src/main/java/org/haobtc/onekey/ui/fragment/NormalActiveSuccessfulFragment.java
- android/app/src/main/res/layout/active_successful_fragment.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ Optimize hardware init
OneKeyHQ/TaskHub#680
Local test
None
> Optimize hardware init

- electrum_gui/android/console.py
1.BTC支持分页显示
2.修复ETH导出keystore的返回格式
3.验证keystore错误问题
4.导入keystorey创建wallet/watch-only钱包不显示备份提示
https://github.com/OneKeyHQ/TaskHub/issues/629
App for android
…
> Transaction history support partial access

- ios/CustomCode/Modules/Bluetooth/OKBlueManager.h
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Hardware/Controller/Hardware.storyboard
- ios/CustomCode/Modules/Hardware/Controller/OKHWRestoreViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKSpecialEquipmentViewController.h
- ios/CustomCode/Modules/Hardware/Controller/OKSpecialEquipmentViewController.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.h
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Manager/OKWalletManager.h
- ios/CustomCode/Modules/Restore/Controller/OKFindFollowingWalletController.m
- ios/CustomCode/Modules/Restore/Controller/OKWordImportVC.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/WalletList/ViewController/OKSetWalletNameViewController.m
- ios/CustomCode/OneKeyImport.h
- ios/Resources/zh-Hans.lproj/Localizable.strings
1.Bluetooth connects to old devices 
2.Recovering the wallet from the special device
> 1.Bluetooth connects to old devices 2.Recovering the wallet from the special device

- android/app/src/main/java/org/haobtc/onekey/activities/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/DeleteWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/importsoft/ImportKeystoreFragment.java
- electrum_gui/android/console.py
+ 修复随便删除主钱包，所有主钱包均被删除。
+ 修复已经备份的钱包，删除钱包还是提醒去备份。偶现。
+ 修复导入 Keystore 文件验证失败。
None
Local test
None
> Fix delete wallet

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
+ Optimize the speed of homepage presentation
None
Local test
None
> Optimize the speed of homepage presentation

- electrum_gui/android/console.py
Repair the problem of password modification failure
https://github.com/OneKeyHQ/TaskHub/issues/664
local
…
> Repair the problem of password modification failure

- android/app/src/main/res/layout/fragment_mind.xml
+ Disable the hardware connection selection
OneKeyHQ/TaskHub#713
Local test
None
> Android:Wallet disable the hardware connection selection

- android/app/src/main/java/org/haobtc/onekey/ui/activity/ActivateColdWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/BackUpActiveSuccessfulFragment.java
- android/app/src/main/res/layout/fragment_backup_active_successful_fragment.xml
+ Fixed hardware backup activation prompt to create new wallet
OneKeyHQ/TaskHub#680
Local test
None
> Fixed hardware backup activation prompt to create new wallet

- android/app/src/main/java/org/haobtc/onekey/asynctask/BusinessAsyncTask.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/res/layout/communication_way.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
完善部分修改文案
暂时屏蔽掉 USB 和 NFC 连接方式
OneKeyHQ/TaskHub#672
…
…
> modify document

- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
+ Fixed initialization without wallet selected
+ Fixed hardware signature cancels empty prompt
OneKeyHQ/TaskHub#704
Local test
None
> Fixed initialization without wallet selected

- android/app/src/main/java/org/haobtc/onekey/ui/activity/FindNormalDeviceActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/NormalActiveSuccessfulFragment.java
+ Initialize the hardware creation wallet name to null
OneKeyHQ/TaskHub#680
Local test
None
> Android:Wallet initialize the hardware creation wallet name to null

- ios/Support/OneKey.xcodeproj/project.pbxproj
> iOS bug: fix project.pbxproj

- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/importsoft/ImportSoftWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
+ Fixed covering observation wallet
+ Fixed delete wallet does not brush the amount
OneKeyHQ/TaskHub#719
Local test
None
> Fix cover watch

- android/app/src/main/java/org/haobtc/onekey/adapter/OnekeyTxListAdapter.java
- android/app/src/main/java/org/haobtc/onekey/extensions/String.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
+ Optimize list amount decimal display bits
OneKeyHQ/TaskHub#629
Local test
None
> Optimize list amount decimal display bits

- electrum/pywalib.py
> ETH - fill tx status

- android/app/src/main/java/org/haobtc/onekey/activities/ServerSettingActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/TransactionDetailsActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/settings/BlockChooseActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/transaction/CheckChainDetailWebActivity.java
- android/app/src/main/java/org/haobtc/onekey/adapter/BlockBrowserChooseAdapter.java
- android/app/src/main/java/org/haobtc/onekey/business/blockBrowser/BlockBrowser.kt
- android/app/src/main/java/org/haobtc/onekey/business/blockBrowser/BlockBrowserBTCMain.kt
- android/app/src/main/java/org/haobtc/onekey/business/blockBrowser/BlockBrowserBTCTest.kt
- android/app/src/main/java/org/haobtc/onekey/business/blockBrowser/BlockBrowserEthMain.kt
- android/app/src/main/java/org/haobtc/onekey/business/blockBrowser/BlockBrowserEthRopsten.kt
- android/app/src/main/java/org/haobtc/onekey/business/blockBrowser/BlockBrowserManager.kt
- android/app/src/main/java/org/haobtc/onekey/constant/Vm.java
- android/app/src/main/java/org/haobtc/onekey/event/FirstEvent.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/DetailETHTransactionActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/DetailTransactionActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionListFragment.java
- android/app/src/main/res/layout/server_setting.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ Add block browser support ETH
+ Fixed block browser support block height、address details
Local test
None
> Add block browser support ETH

- ios/CustomCode/Modules/Tab_Mine/Controller/OKAboutViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKFirstUseViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Web/Proxy/OKURLSchemeHandler.h
- ios/CustomCode/Modules/Web/Proxy/OKURLSchemeHandler.m
- ios/CustomCode/Modules/Web/Proxy/WKWebView+Bypass.h
- ios/CustomCode/Modules/Web/Proxy/WKWebView+Bypass.m
- ios/CustomCode/Modules/Web/WebViewVC.h
- ios/CustomCode/Modules/Web/WebViewVC.m
- ios/CustomCode/OneKeyDefine.h
- ios/Support/OneKey.xcodeproj/project.pbxproj
WKWebview HTTP proxy support.
WKWebview 支持通过 HTTP proxy 访问。
…
…
…
> iOS feature: webview proxy support.

- android/app/src/main/java/org/haobtc/onekey/activities/settings/HardwareDetailsActivity.java
- android/app/src/main/java/org/haobtc/onekey/asynctask/BusinessAsyncTask.java
- android/app/src/main/java/org/haobtc/onekey/manager/BleManager.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/HardwareUpgradeActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/InputPinOnHardware.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/IBaseView.java
- electrum/plugins/trezor/trezor.py
- electrum_gui/android/console.py
1. optimize ble connecting process 2. fix display bug about pin
2. update submodule python-trezor index
OneKeyHQ/TaskHub#710,
OneKeyHQ/TaskHub#658
local
> optimize ble connecting process 2. fix display bug about pin

- android/app/src/main/java/org/haobtc/onekey/business/chain/bitcoin/BitcoinService.kt
- android/app/src/main/java/org/haobtc/onekey/business/chain/ethereum/EthService.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/DetailETHTransactionActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionDetailWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
+ Optimize the ETH decimal display of transaction records
OneKeyHQ/TaskHub/issues/629
Local test
None
> Optimize the ETH decimal display of transaction records

- electrum/MutiBase.py
- electrum/eth_transaction.py
- electrum/eth_wallet.py
- electrum/plugins/hw_wallet/plugin.py
- electrum/plugins/trezor/clientbase.py
- electrum/plugins/trezor/trezor.py
- electrum_gui/android/console.py
1.解决HD钱包删除时失败问题
2.修复ETH验证私钥失败问题
3.增加通过硬件创建ETH钱包、验证地址、签名功能
https://github.com/OneKeyHQ/TaskHub/issues/717
https://github.com/OneKeyHQ/TaskHub/issues/714
https://github.com/OneKeyHQ/TaskHub/issues/184
Local
…
> Add the function of creating wallet, verifying address and signature via hardware

- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendEthActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionCompletion.java
+ Fix the transfer to view ETH transaction details
OneKeyHQ/TaskHub#727
Local test
None
> Android:Wallet fix the transfer to view ETH transaction details

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendEthActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/CustomizeFeeDialog.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/CustomEthFeeDialog.java
- android/app/src/main/java/org/haobtc/onekey/utils/ToastUtils.java
- android/app/src/main/res/layout/activity_send_hd.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
优化自定义费率展示提示
代理加速
OneKeyHQ/TaskHub#725
OneKeyHQ/TaskHub#720
OneKeyHQ/TaskHub#677
OneKeyHQ/TaskHub#447
…
…
> Optimize custom rate display

- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ Fix optimize hardware signature cancellation prompts
OneKeyHQ/TaskHub#704
Local test
None
> Fix optimize hardware signature cancellation prompts

- android/app/src/main/java/org/haobtc/onekey/business/wallet/AccountManager.java
- android/app/src/main/java/org/haobtc/onekey/exception/AccountException.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createfasthd/CreateFastHDSoftWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createsoft/CreateSoftWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/importsoft/ImportSoftWalletActivity.java
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ Fix the error message prompt
OneKeyHQ/TaskHub#722
Local test
None
> Fix the error message prompt

- electrum_gui/android/console.py
1.修改分页显示错误问题
2.提详细页面 ”查看详情“接口
https://github.com/OneKeyHQ/TaskHub/issues/629
https://github.com/OneKeyHQ/TaskHub/issues/727
https://github.com/OneKeyHQ/TaskHub/issues/724
App for android
…
> Fix pagination display error bug

- electrum/eth_transaction.py
- electrum/pywalib.py
- electrum_gui/common/explorer/clients/etherscan.py
- electrum_gui/common/explorer/clients/trezor_eth.py
- electrum_gui/common/explorer/data/enums.py
- electrum_gui/common/explorer/data/interfaces.py
- electrum_gui/common/explorer/data/objects.py
1. 尽可能将**直接 web3 调用**替换成**封装好的 Explorer 类**
2. 移除未使用代码
…
…
…
> ETH - Replace web3

- ios/CustomCode/Modules/Base/BaseViewController.h
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.h
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Hardware/Controller/OKActivateDeviceSelectViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Manager/OKWalletManager.m
- ios/CustomCode/Modules/Signature/Controller/OKSignatureViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKReceiveCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/WalletList/ViewController/OKSetWalletNameViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS feature：Create hardware wallet modal box，Hw Wallet Interface
> iOS feature：Create hardware wallet modal box，Hw Wallet Interface

- electrum/eth_wallet.py
- electrum/pywalib.py
- electrum_gui/android/console.py
- electrum_gui/common/explorer/clients/trezor_eth.py
1. 修复恢复 ETH HD 钱包时返回不符合前端需求数据的问题，保持跟原 BTC 一致
…
…
…
> ETH - Fix create_hd_wallet

- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/HardwareSetting.storyboard
- ios/Resources/zh-Hans.lproj/Localizable.strings
Fix hardware settings UI bugs.
适配小屏手机
https://github.com/OneKeyHQ/TaskHub/issues/729
…
…
> iOS fix: Hardware settings UI bugs.

- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/RecoveryChooseWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendEthActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/FindBackupOnlyDeviceActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/RecoveryHardwareOnceWallet.java
- android/app/src/main/java/org/haobtc/onekey/ui/adapter/RecoveryWalletDerivedInfoAdapter.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/RecoveryWalletFromHdFragment.java
- android/app/src/main/res/layout/activity_recovery_choose_wallet.xml
- android/app/src/main/res/layout/choose_hd_wallet_item.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
- electrum_gui/android/console.py
支持Eth恢复
修复BTC转账崩溃
OneKeyHQ/TaskHub#735
…
…
> Support ETH recovery

- electrum/eth_wallet.py
- electrum_gui/android/console.py
1. [PR397](https://github.com/OneKeyHQ/electrum/pull/397) 对 Eth_Wallet.get_all_balance 的修改影响了 select_wallet 的功能，修复
…
…
…
> ETH - Fix select_wallet

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/DeleteWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/WalletManageActivity.java
+ 修复钱包管理页面删除全部钱包，ETH 还存在的情况。
OneKeyHQ/TaskHub#726
…
…
> Android:Wallet fix wallet management page deletes all wallets

- ios/CustomCode/Categories/UIView+Helper.m
- ios/CustomCode/Modules/PassWord/Controller/OKPwdViewController.m
- ios/CustomCode/Modules/PassWord/Validation/OKValidationPwdController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateViewController.m
iOS improvement: iOS 13.0+ support corner curve continuous.
iOS 13.0+ 支持连续平滑圆角
…
…
…
> iOS improvement: iOS 13.0+ support corner curve continuous.

- ios/CustomCode/Modules/Hardware/Controller/Hardware.storyboard
- ios/CustomCode/Modules/PassWord/Validation/OKValidationPwdController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKHDWalletViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKMineViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxListViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
iOS fix：Mine page refresh bug
OneKeyHQ/TaskHub#656
OneKeyHQ/TaskHub#632
OneKeyHQ/TaskHub#456
OneKeyHQ/TaskHub#460
…
…
> iOS fix：Mine page refresh bug

- android/app/src/main/java/org/haobtc/onekey/activities/settings/HardwareDetailsActivity.java
- electrum_gui/android/console.py
move verify hardware interface form client to python backend
local
None
> move verify hardware interface form client to python backend

- android/app/src/main/java/org/haobtc/onekey/business/wallet/AccountManager.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/SelectChainCoinFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createfasthd/CreateFastHDSoftWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createfasthd/CreateFastHDSoftWalletProvider.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createsoft/CreateSoftWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createsoft/CreateSoftWalletProvider.java
+ ETH derivation restriction
None
Local test
None
> Android:Wallet ETH derivation restriction

- android/app/src/main/java/org/haobtc/onekey/business/wallet/BalanceManager.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/AllAssetsActivity.java
修复资产页面报错，无资产搜索崩溃
OneKeyHQ/TaskHub#738
…
…
> Fixed asset page search crash

- electrum/pywalib.py
- electrum/util.py
1. 获取余额报错返回 0
2. 把 Decimal 转成非科学技术法的字符串
…
…
…
> Handle error request & adjust DecimalEncoder

- android/app/src/GooglePlay/java/org.haobtc.onekey.business.update/AutoCheckUpdate.java
+ Fixed failure to upgrade hardware in Google Play
OneKeyHQ/TaskHub#757
Local test
紧急修复
> Android:Wallet fixed failure to upgrade hardware in Google Play

- android/app/src/main/java/org/haobtc/onekey/adapter/OnekeyTxListAdapter.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionListFragment.java
Optimize the roll-in record icon
OneKeyHQ/TaskHub#736
…
…
> Android:Wallet optimize the roll-in record icon

- ios/CustomCode/Categories/NSString+OKAdd.h
- ios/CustomCode/Categories/NSString+OKAdd.m
- ios/CustomCode/Modules/Hardware/Model/OKDeviceInfoModel.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceList/OKDeviceListViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceSettingHome/OKDeviceSettingsViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceSettingHome/OKHardwareListBaseCell.h
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceSettingHome/OKHardwareListBaseCell.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceVerify/OKDeviceVerifyController.h
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceVerify/OKDeviceVerifyController.m
- ios/CustomCode/Modules/WalletList/ViewController/OKAddBottomViewController.m
iOS fix: Hardware settings bugs.
修复硬件设置相关bug，包括 UI / 版本更新等
https://github.com/OneKeyHQ/TaskHub/issues/731
…
…
> iOS fix: Hardware settings bugs.

- ios/CustomCode/AppDelegate.m
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.h
- ios/CustomCode/Modules/Hardware/Controller/Hardware.storyboard
- ios/CustomCode/Modules/Hardware/Controller/OKHWCompleteCopyViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.h
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKPINCodeViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKSetDeviceNameViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKSetPINPreViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKVerifyOnTheDeviceController.h
- ios/CustomCode/Modules/Hardware/Controller/OKVerifyOnTheDeviceController.m
- ios/CustomCode/Modules/Restore/Controller/OKReadyToStartViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxListViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletDetailViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tab_Wallet/View/OKTxTableViewCell.m
- ios/CustomCode/Modules/Tab_Wallet/View/OKWalletInputFeeView.h
- ios/CustomCode/Modules/Tab_Wallet/View/OKWalletInputFeeView.m
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.m
- ios/CustomCode/Notification.h
- ios/Resources/zh-Hans.lproj/Localizable.strings
Activate wallet to add confirmation
OneKeyHQ/TaskHub#569
OneKeyHQ/TaskHub#619
OneKeyHQ/TaskHub#565
OneKeyHQ/TaskHub#741
OneKeyHQ/TaskHub#744
OneKeyHQ/TaskHub#739
> Activate wallet to add confirmation

- android/app/src/GooglePlay/java/org.haobtc.onekey.business.update/AutoCheckUpdate.java
- android/app/src/Onekey/java/org/haobtc/onekey/business/update/AutoCheckUpdate.java
- android/app/src/main/java/org/haobtc/onekey/activities/settings/HardwareDetailsActivity.java
- android/app/src/main/java/org/haobtc/onekey/business/version/VersionManager.kt
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
+ Optimize hardware update version
OneKeyHQ/TaskHub#710
…
…
> Android:Wallet optimize hardware update version

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/HardwareUpgradeActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/InputPinOnHardware.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/HardwareUpgradeFragment.java
修复硬件升级重启后，升级页面没有刷新
修复转账提示错误
OneKeyHQ/TaskHub#695
OneKeyHQ/TaskHub#749
…
…
> A successful firmware upgrade will show the old version

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionDetailWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
add device id check when use hw wallet
OneKeyHQ/TaskHub#747,
OneKeyHQ/TaskHub#773,
local
none
> add device id check when use hw wallet

- android/app/src/main/java/org/haobtc/onekey/activities/settings/HardwareDetailsActivity.java
- android/app/src/main/java/org/haobtc/onekey/event/PinInputComplete.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/ConfirmOnHardWareActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/InputPinOnHardware.java
- android/app/src/main/res/layout/input_on_hardware.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
APP和HW修改PIN码新UI
OneKeyHQ/TaskHub#706
…
…
> Modify the PIN new UI

- ios/CustomCode/Modules/Hardware/Controller/OKDeviceSuccessViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKSpecialEquipmentViewController.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Manager/OKWalletManager.h
- ios/CustomCode/Modules/Manager/OKWalletManager.m
- ios/CustomCode/Modules/Restore/Controller/OKWordImportVC.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKDeleteWalletTipsViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceList/OKDeviceModel.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletDetailViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/Resources/zh-Hans.lproj/Localizable.strings
IOS Fix: Hardware status update
OneKeyHQ/TaskHub#755
OneKeyHQ/TaskHub#760
OneKeyHQ/TaskHub#753
OneKeyHQ/TaskHub#750
OneKeyHQ/TaskHub#762
OneKeyHQ/TaskHub#759
OneKeyHQ/TaskHub#756
OneKeyHQ/TaskHub#748
> IOS Fix: Hardware status update

- .github/workflows/pre-commit.yml
1. 尝试重新让 github action pre-commit 可用
…
…
…
> Adjust github action pre-commit

- ios/CustomCode/Modules/Base/BaseViewController.h
- ios/CustomCode/Modules/Base/BaseViewController.m
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Manager/OKLocalizableManager.h
- ios/CustomCode/Modules/Manager/OKLocalizableManager.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceList/OKDeviceModel.h
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceList/OKDeviceModel.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceList/OKDevicesManager.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKDeviceChangePINController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKResetDeviceWarningViewController.m
fix hardware reset bugs.
https://github.com/OneKeyHQ/TaskHub/issues/732
…
…
> iOS fix: Hardware reset bugs.

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/importsoft/ImportKeystoreFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/ExportTipsDialog.java
+ Optimize keystore import and export load animation
+ 账户详情页去掉 GotPassEvent 事件，后面可参考。
OneKeyHQ/TaskHub#711
OneKeyHQ/TaskHub#564
…
…
> Android:Wallet optimize keystore import and export load animation

- android/app/build.gradle
- android/app/proguard-rules.pro
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/haobtc/onekey/activities/AboutActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/SupportActivity.java
- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/bean/CreateWalletBean.java
- android/app/src/main/java/org/haobtc/onekey/constant/StringConstant.java
- android/app/src/main/java/org/haobtc/onekey/manager/HardwareCallbackHandler.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/HomeOneKeyActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/adapter/RecoveryWalletInfoAdapter.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/RecoveryWalletFromHdFragment.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/PassWordViewModel.java
- android/app/src/main/res/layout/activity_about.xml
- android/app/src/main/res/layout/activity_supportctivity.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/values/styles.xml
- android/build.gradle
恢复创建Account 添加已存在状态
添加Zendesk 工单支持
Zendesk 语言跟随手机系统语言适配
OneKeyHQ/TaskHub#766
OneKeyHQ/TaskHub#668
…
…
> Restore create add existing state, add Zendesk work order support

- ios/CustomCode/Modules/ScanQR/OKWalletScanVC.m
- ios/CustomCode/Modules/ScanQR/Scan.storyboard
- ios/Resources/zh-Hans.lproj/Localizable.strings
Fix QRCode Scanner UI issues.
https://github.com/OneKeyHQ/TaskHub/issues/324
…
…
> iOS fix: QRCode Scanner UI issues.

- electrum/MutiBase.py
- electrum/eth_wallet.py
- electrum/keystore.py
- electrum/util.py
- electrum/wallet_db.py
- electrum_gui/android/console.py
- electrum_gui/android/create_wallet_info.py
1.修改eth/bsc/heco 钱包派生规则为派生address_index
2.恢复流程中 当没查找到要恢复的文件时 要创建默认钱包 如果默认钱包已存在 要显示已存在提示信息（支持）
3.修改恢复流程中关于eth部分
…
Python+Android
…
> ETH derivation rules for derivation address index

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/haobtc/onekey/activities/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/HDWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateLocalMainWalletActivity.kt
- android/app/src/main/java/org/haobtc/onekey/ui/activity/PinVerifyWaySelector.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseActivity.java
- android/app/src/main/res/drawable/selector_btn_small_round.xml
- android/app/src/main/res/drawable/shape_bg_wallet_coin_select.xml
- android/app/src/main/res/drawable/shape_btn_small_round_disable.xml
- android/app/src/main/res/drawable/shape_btn_small_round_normal.xml
- android/app/src/main/res/layout/activity_create_local_main_wallet.xml
- android/app/src/main/res/layout/item_create_wallet_select_coin.xml
- android/app/src/main/res/layout/item_create_wallet_select_token.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/strings.xml
- android/gradle.properties
+ 删除创建账户相关的无用代码
+ 创建主钱包时可选择创建的币种
+ 将 annotationProcessor 切换成 kapt
Local test
…
> Android:Wallet add to create the main wallet select currency

- .pre-commit-config.yaml
- electrum_gui/android/console.py
Add flake8 check for electrum_gui
…
…
…
> Add flake8 check for electrum_gui

- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/SelectChainCoinFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createfasthd/CreateFastHDSoftWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createfasthd/CreateFastHDSoftWalletProvider.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createsoft/CreateSoftWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/walletprocess/createsoft/CreateSoftWalletProvider.java
- android/app/src/main/res/layout/activity_export_private.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ Content optimization
+ Unrestrict ETH
OneKeyHQ/TaskHub#800
…
…
> Android:Wallet content optimization & unrestrict ETH

- electrum/eth_wallet.py
1. 修改缓存逻辑，仅缓存10s
https://github.com/OneKeyHQ/TaskHub/issues/779
…
…
> ETH - Fix cache logic of get_all_balance

- electrum_gui/android/console.py
1. 支持 ETH 余额回调
https://github.com/OneKeyHQ/TaskHub/issues/779
…
…
> ETH - Supports balance callback

- android/app/build.gradle
- android/app/src/main/java/org/haobtc/onekey/business/chain/bitcoin/BitcoinService.kt
- android/app/src/main/java/org/haobtc/onekey/business/chain/ethereum/EthService.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionListFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/status/LoadErrorGoBrowserState.kt
- android/app/src/main/java/org/haobtc/onekey/ui/status/LoadProgressState.kt
- android/app/src/main/java/org/haobtc/onekey/ui/status/NoRecordState.kt
- android/app/src/main/res/layout/fragment_transaction_list.xml
- android/app/src/main/res/layout/state_load_error_go_to_browser.xml
- android/app/src/main/res/layout/state_load_progress.xml
- android/app/src/main/res/layout/state_no_transfer_record.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ Failed to optimize transaction record
OneKeyHQ/TaskHub#804
…
…
> Android:Wallet failed to optimize transaction record

- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/asynctask/BusinessAsyncTask.java
- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/manager/BleManager.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/request/ConnectRequest.java
- electrum/locale/messages.pot
open ble auto connect feature
local
> open ble auto connect feature

- android/app/src/main/java/org/haobtc/onekey/asynctask/BusinessAsyncTask.java
- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/constant/PyConstant.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendEthActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/CreatePersonalWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/adapter/RecoveryWalletInfoAdapter.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/SelectAddressTypeDialog.java
- android/app/src/main/java/org/haobtc/onekey/utils/CoinUtils.java
通过硬件创建ETH
1.签名
2.恢复派生
3.show_address
OneKeyHQ/TaskHub##184
…
…
> add hardware create Eth

- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceSettingHome/OKDeviceSettingsViewController.m
iOS feature: Device bootloader mode redirects to update.
…
…
…
> iOS feature: Device bootloader mode redirects to update.

- android/app/src/main/java/org/haobtc/onekey/activities/SupportActivity.java
修复部分手机(三星,ViVO)打开工单列表页面闪烁，打不开
OneKeyHQ/TaskHub#766
…
…
> Zendesk PageListActivity Display abnormal

- ios/CustomCode/Modules/Restore/Controller/OKFindFollowingWalletController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKMineViewController.m
iOS fix：Fixed language interface bugs
OneKeyHQ/TaskHub#808
…
…
> iOS fix：Fixed language interface bugs

- electrum_gui/android/console.py
1.删除未使用代码
2.修复恢复eth钱包时的报错问题
…
…
> Fixes to restore eth wallet

- android/app/src/main/java/org/haobtc/onekey/bean/BalabceBroadcastEventBean.kt
- android/app/src/main/java/org/haobtc/onekey/business/wallet/BalanceManager.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
+ Optimize ETH balance refresh
OneKeyHQ/TaskHub#779
…
…
> Android:Wallet optimize ETH balance refresh

- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceSettingHome/OKDeviceSettingsViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKResetDeviceWarningViewController.m
- ios/Support/OneKey.xcodeproj/project.pbxproj
iOS fix: Device removal issues.
…
…
…
> iOS fix: Device removal issues.

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/CreateLocalMainWalletActivity.kt
+ create the main wallet is fully enabled by default
OneKeyHQ/TaskHub#814
…
…
> Android:Wallet create the main wallet is fully enabled by default

- android/app/src/main/java/org/haobtc/onekey/asynctask/BusinessAsyncTask.java
- android/app/src/main/java/org/haobtc/onekey/constant/PyConstant.java
- android/app/src/main/java/org/haobtc/onekey/exception/HardWareExceptions.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dialog/recovery/RecoveryChooseWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/PinVerifyWaySelector.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/RecoveryHardwareOnceWallet.java
- android/app/src/main/java/org/haobtc/onekey/ui/adapter/RecoveryWalletDerivedInfoAdapter.java
- android/app/src/main/java/org/haobtc/onekey/ui/adapter/RecoveryWalletInfoAdapter.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseFragment.java
- android/app/src/main/res/layout/activity_recovery_choose_wallet.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
- electrum_gui/android/console.py
HW恢复钱包和特殊设备恢复钱包问题
OneKeyHQ/TaskHub#805
…
…
> HW Recovery Wallet and Special Equipment Recovery Wallet problems

- ios/CustomCode/Categories/NSArray+OKAdd.h
- ios/CustomCode/Categories/NSString+OKAdd.h
- ios/CustomCode/Categories/NSString+OKAdd.m
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.h
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Restore/Controller/OKFindFollowingWalletController.m
- ios/CustomCode/Modules/Tools/OKTools.h
- ios/CustomCode/Modules/Tools/OKTools.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS feature： Bluetooth version update prompt
…
…
> iOS feature： Bluetooth version update prompt

- ios/CustomCode/Modules/Hardware/Controller/Hardware.storyboard
- ios/CustomCode/Modules/Hardware/Controller/OKPINCodeViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS feature：Remove the digit limit for PIN codes
> iOS feature：Remove the digit limit for PIN codes

- android/app/src/main/java/org/haobtc/onekey/business/blockBrowser/BlockBrowserBTCMain.kt
- android/app/src/main/java/org/haobtc/onekey/business/blockBrowser/BlockBrowserEthMain.kt
> Android:Wallet add OKEx Block Browser

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
Disable ETH hardware signature
…
…
…
> Android:Wallet disable ETH hardware signature

- android/app/src/main/java/org/haobtc/onekey/ui/fragment/DevicePINFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/widget/AsteriskPasswordTransformationMethod.java
- android/app/src/main/res/layout/fragment_set_device_pass.xml
在App上输入PIN码为9位
OneKeyHQ/TaskHub#819
…
…
> modify pin input mode

- electrum_gui/android/console.py
Fix price push
OneKeyHQ/TaskHub#779
…
…
> Python:ETH fix price push

- electrum/plugins/trezor/clientbase.py
- electrum/util.py
- electrum_gui/android/console.py
> Support for 1-9 digit passwords

- android/app/src/main/java/org/haobtc/onekey/constant/Constant.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/PinNewActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/VerifyPinActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/DevicePINFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/widget/AsteriskPasswordTransformationMethod.java
- android/app/src/main/res/layout/fragment_set_device_pass.xml
- android/app/src/main/res/layout/input_pin_activity.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
Hardware supports nine-digit passwords
OneKeyHQ/TaskHub#819
…
…
> Android:Wallet hardware supports nine-digit passwords

- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ Fixed hardware input password prompt
…
…
…
> Android:Wallet fixed hardware input password prompt

- ios/CustomCode/Modules/Bluetooth/OKBlueManager.h
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceList/OKDevicesManager.h
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceList/OKDevicesManager.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateInstallController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateViewController.h
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKDeviceChangePINController.m
- ios/Support/podfile
> iOS feature: DFU.

- electrum/eth_servers.json
- electrum/eth_wallet.py
- electrum/pywalib.py
- electrum/wallet.py
- electrum_gui/android/console.py
- electrum_gui/common/explorer/clients/eth/etherscan.py
- electrum_gui/common/explorer/clients/eth/geth.py
- electrum_gui/common/explorer/clients/eth/trezor.py
- electrum_gui/common/explorer/data/interfaces.py
- electrum_gui/common/explorer/data/objects.py
1. 支持 BSC 和 HECO，已测过 BSC 测试网的收发
…
…
目前剩法币价格的获取有问题，我会后面新提个 PR
> Supports Heco and BSC

- ios/CustomCode/Modules/Bluetooth/OKBlueManager.h
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Manager/OKUserSettingManager.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKMineViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS feature：Hardware Bluetooth low version compatible
> iOS feature：Hardware Bluetooth low version compatible

- ios/CustomCode/Modules/Hardware/Controller/Hardware.storyboard
- ios/CustomCode/Modules/Restore/Controller/OKFindFollowingWalletController.m
- ios/CustomCode/Modules/Restore/Controller/OKWordImportVC.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletDetailViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
修改文案
https://github.com/OneKeyHQ/TaskHub/issues/671
…
…
> iOS fix: Revise the text.

- electrum/eth_servers.json
先紧急去除 BSC/Heco 相关配置，因为目前 ETH/BSC/Heco 共用了同一个 pywalib 实例，原本仅支持 ETH 时候只需要在入口处设置一次币种相关配置，但现在支持多币种后就需要在每次使用 pywalib 前都确保 pywalib 内配置的币种信息是想操作币种的。
因为调用地方太多，先去除 BSC/Heco 配置，等处理好后再加上
…
…
…
> Delete BSC/Heco related config

- android/app/src/main/java/org/haobtc/onekey/asynctask/BusinessAsyncTask.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/ReceiveHDActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/CreatePersonalWalletActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
1. Add hardware validation ETH address
2. Enter the hardware password and the phone will return directly, and the hardware state will be reset
3. Phone input hardware password input error, exception handling
OneKeyHQ/TaskHub#826
…
…
…
> Android:Wallet fixed some bugs

- ios/CustomCode/Modules/Hardware/Controller/Hardware.storyboard
- ios/CustomCode/Modules/Hardware/Controller/OKDeviceIdInconsistentViewController.h
- ios/CustomCode/Modules/Hardware/Controller/OKDeviceIdInconsistentViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKDeviceSuccessViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
- ios/Support/OneKey.xcodeproj/project.pbxproj
iOS fix：Pairing prompt for pattern mismatch
OneKeyHQ/TaskHub#807
OneKeyHQ/TaskHub#786
OneKeyHQ/TaskHub#775
OneKeyHQ/TaskHub#743
OneKeyHQ/TaskHub#754
OneKeyHQ/TaskHub#679
> iOS fix：Pairing prompt for pattern mismatch

- ios/CustomCode/Modules/Bluetooth/OKBlueManager.h
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Signature/Controller/OKSignatureViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKReceiveCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTransferCompleteController.m
iOS fix：Delayed viewing of transaction records
OneKeyHQ/TaskHub#806
…
…
> iOS fix：Delayed viewing of transaction records

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/DeleteWalletTipsDialog.java
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ Optimized ETH delete account ANR issue
OneKeyHQ/TaskHub#847
…
…
> Android:Wallet optimized ETH delete account ANR issue

- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKDeviceInfoViewController.m
- ios/CustomCode/Modules/Web/Proxy/OKURLSchemeHandler.m
iOS fix: disable device name changing.
…
…
…
> iOS fix: disable device name changing.

- android/app/src/main/res/layout/fragment_set_device_pass.xml
- android/app/src/main/res/values-zh/strings.xml
> Android:Wallet fixed activation device PIN prompt

- ios/CustomCode/Categories/UIBarButtonItem+CustomBarButtonItem.h
- ios/CustomCode/Categories/UIBarButtonItem+CustomBarButtonItem.m
- ios/CustomCode/Modules/Tab_Wallet/OKReceiveCoinViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS feature: QRCode save.
…
…
…
> iOS feature: QRCode save.

- ios/CustomCode/Modules/Hardware/Model/OKDeviceInfoModel.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/HardwareSetting.storyboard
- ios/CustomCode/Modules/Tools/OKTools.h
- ios/CustomCode/Modules/Tools/OKTools.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS fix: Hardware wallet update version issue.
修复升级版本显示错误问题，增加升级提示。
https://github.com/OneKeyHQ/TaskHub/issues/783
…
…
> iOS fix: Hardware wallet update version issue.

- ios/CustomCode/Modules/Bluetooth/OKBlueManager.h
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
iOS feature：Firmware strength increased to 2.0.4
…
…
> iOS feature：Firmware strength increased to 2.0.4

- ios/CustomCode/Modules/Common/OKVersion.h
- ios/CustomCode/Modules/Common/OKVersion.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceSettingHome/OKDeviceSettingsViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS feature: Version restrictions on certain operations.
…
…
…
> iOS feature: Version restrictions on certain operations.

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
+ Fixed delete wallet error 
None
…
…
> Android:Wallet fixed delete wallet error

- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/utils/Utils.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/BleLog.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/model/BleDevice.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/proxy/RequestImpl.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/request/NotifyRequest.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/request/ReadRequest.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/request/ReadRssiRequest.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/request/WriteRequest.java
+ bluetooth module to add log information
+ add Activity stack management
OneKeyHQ/TaskHub#846
…
…
> Android:Wallet optimization bluetooth

- electrum/eth_wallet.py
- electrum/plugins/trezor/trezor.py
- electrum/wallet.py
- electrum/wallet_db.py
- electrum_gui/android/console.py
Collate sing_message and verify_message interface
Python
…
> Collate sing_message and verify_message interface

- android/app/src/main/java/org/haobtc/onekey/bean/BalabceBroadcastEventBean.kt
- android/app/src/main/java/org/haobtc/onekey/bean/WalletBalanceFiatVo.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.java
+ Fixed network failure fiat balance not displayed
None
…
…
> Android:Wallet fixed network failure fiat balance not displayed

- .gitignore
- contrib/requirements/requirements.txt
- electrum_gui/android/console.py
- electrum_gui/common/basic/orm/database.py
- electrum_gui/common/basic/orm/exceptions.py
- electrum_gui/common/basic/orm/migrate/manager.py
- electrum_gui/common/basic/orm/migrate/models.py
- electrum_gui/common/basic/orm/models.py
- electrum_gui/common/conf/settings.py
- electrum_gui/common/conf/utils.py
- electrum_gui/common/the_begging.py
1. 加入 Settings，并支持 local_seetings.py 自定义替换配置
2. 加入 Logger
3. 加入 peewee ORM，
- 最终选用 peewee 是后面发现它更加轻量化而且主要代码都是 python 实现，仅两个**可选**功能是 c 实现，不会影响正常运行
- peewee 实现了类 django API，使用起来更加方便
- peewee 支持 migrate 机制
4. 实现类 django 的 DB 迁移机制
…
…
1. 新增了 peewee，目前添加到了 `contrib/requirements/requirements.txt`，还需要额外添加到哪个 requirements 下吗？ @danielsocials  
2. 最近我会把 ORM 相关的使用文档补全
> Set up Settings, Logger and DB ORM

- android/app/src/main/java/org/haobtc/onekey/adapter/HdWalletAssetAdapter.kt
- android/app/src/main/java/org/haobtc/onekey/bean/BalanceCoinInfo.java
- android/app/src/main/java/org/haobtc/onekey/business/wallet/BalanceManager.java
- android/app/src/main/java/org/haobtc/onekey/business/wallet/bean/WalletBalanceBean.kt
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/mindmenu/AllAssetsActivity.java
- android/app/src/main/res/layout/all_assets_item.xml
资产页面点击条目进入资产详情页面，前端已添加字段，待python添加字段返回
OneKeyHQ/TaskHub#822
…
…
> Click on the asset page to enter the asset details

- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
- android/app/src/main/java/org/haobtc/onekey/adapter/HdWalletAssetAdapter.kt
- android/app/src/main/java/org/haobtc/onekey/business/wallet/BalanceManager.java
- android/app/src/main/java/org/haobtc/onekey/business/wallet/bean/WalletBalanceBean.kt
- android/app/src/main/java/org/haobtc/onekey/utils/Daemon.java
- contrib/deterministic-build/requirements.txt
紧急修复App打开崩溃
添加资产页面跳转资产详情
修复硬件签名完成崩溃问题
OneKeyHQ/TaskHub#868
OneKeyHQ/TaskHub#822
…
…
> Open crash problem fixes

- android/app/src/main/java/org/haobtc/onekey/activities/base/ApplicationObserver.java
修复设备意外断开连接问题
+ 曾经可能会导致激活设备流程执行一半中断。
+ 曾经可能会导致升级设备过程中意外断开。
+ 曾经可能会导致激活设备时提示 send failure。
OneKeyHQ/TaskHub#846
OneKeyHQ/TaskHub#854
…
…
> Android:Wallet fixed Bluetooth disconnect timing

- ios/CustomCode/Modules/ImportWallet/ViewController/OKMnemonicImportViewController.h
- ios/CustomCode/Modules/ImportWallet/ViewController/OKMnemonicImportViewController.m
- ios/CustomCode/Modules/ImportWallet/ViewController/OKPrivateImportViewController.h
- ios/CustomCode/Modules/ImportWallet/ViewController/OKPrivateImportViewController.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Manager/OKWalletManager.h
- ios/CustomCode/Modules/WalletList/ViewController/OKBTCAddressTypeSelectController.h
- ios/CustomCode/Modules/WalletList/ViewController/OKBTCAddressTypeSelectController.m
- ios/CustomCode/Modules/WalletList/ViewController/OKSelectCoinTypeViewController.m
- ios/CustomCode/Modules/WalletList/ViewController/OKSelectImportTypeViewController.h
- ios/CustomCode/Modules/WalletList/ViewController/OKSelectImportTypeViewController.m
- ios/CustomCode/Modules/WalletList/ViewController/OKSetWalletNameViewController.h
- ios/CustomCode/Modules/WalletList/ViewController/OKSetWalletNameViewController.m
- ios/CustomCode/Modules/WalletList/ViewController/WalletList.storyboard
- ios/Resources/zh-Hans.lproj/Localizable.strings
- ios/Support/OneKey.xcodeproj/project.pbxproj
- ios/Support/OneKey.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ios/Support/podfile
iOS feature: support btc address types.
https://github.com/OneKeyHQ/TaskHub/issues/430
…
…
> iOS feature: support btc address types.

- ios/CustomCode/AppDelegate.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateInstallController.m
- ios/Support/OneKey.xcodeproj/project.pbxproj
- ios/setup.py
iOS: support jpush, etc.
…
…
…
> iOS: support jpush, etc.

- ios/Support/OneKey.entitlements
- ios/Support/OneKey.xcodeproj/project.pbxproj
iOS fix: embed entitlement.
…
…
…
> iOS fix: embed entitlement.

- ios/CustomCode/AppDelegate.m
- ios/CustomCode/OneKeyDefine.h
iOS improvement: update predefined.
…
…
…
> iOS improvement: update predefined

- ios/Support/podfile
https://github.com/OneKeyHQ/electrum/pull/499
add missing cocoapods dependency
https://github.com/OneKeyHQ/electrum/pull/499
> iOS fix: add dependency for Zendesk SDK

- android/app/src/main/java/org/haobtc/onekey/activities/sign/SignActivity.java
- android/app/src/main/res/layout/activity_about.xml
Modify the about ui
OneKeyHQ/TaskHub#863
…
…
> Modify the about ui

- electrum/pywalib.py
1. 加上 api key，减少频次受限相关报错
…
…
…
> Add API_KEY for etherscan ropsten explorer

- electrum/eth_servers.json
- electrum/pywalib.py
1. 当前的 Coinbase 和 Bixin 渠道无法获取 BNB 和 HT 的价格，所以加上 CMC 渠道
…
…
…
> add CMC price channel

- ios/CustomCode/Modules/Appreance/UIColor+OKAppreance.h
- ios/CustomCode/Modules/Appreance/UIColor+OKAppreance.m
- ios/CustomCode/Modules/Appreance/UIFont+OKAppreance.h
- ios/CustomCode/Modules/Appreance/UIFont+OKAppreance.m
- ios/CustomCode/Modules/Base/BaseViewController.h
- ios/CustomCode/Modules/Base/BaseViewController.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.h
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/ScanQR/OKWalletScanVC.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Token/Management/OKTokenManagementController.h
- ios/CustomCode/Modules/Token/Management/OKTokenManagementController.m
- ios/CustomCode/Modules/Token/Management/View/OKTokenCell.h
- ios/CustomCode/Modules/Token/Management/View/OKTokenCell.m
- ios/CustomCode/Modules/Token/Management/View/OKTokenSectionCell.h
- ios/CustomCode/Modules/Token/Management/View/OKTokenSectionCell.m
- ios/CustomCode/Modules/Token/Model/OKToken.h
- ios/CustomCode/Modules/Token/Model/OKToken.m
- ios/CustomCode/Modules/Token/Tokens.storyboard
- ios/CustomCode/Modules/Web/WebViewVC.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
- ios/Support/OneKey.xcodeproj/project.pbxproj
iOS improvement: base view controller refactor.
…
…
…
> iOS improvement: base view controller refactor.

- electrum_gui/common/coin/codes.py
- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/coins.json
- electrum_gui/common/coin/configs/testnet_chains.json
- electrum_gui/common/coin/configs/testnet_coins.json
- electrum_gui/common/coin/data.py
- electrum_gui/common/coin/exceptions.py
- electrum_gui/common/coin/manager.py
- electrum_gui/common/coin/registry.py
- electrum_gui/common/conf/settings.py
实现 coin manager，方便后续更好的管理币种
…
…
…
> coin manager

- electrum_gui/android/console.py
> Fixing recovery bugs

- electrum/eth_wallet.py
- electrum_gui/android/console.py
> balance of tokens callback supporting

- android/app/src/main/java/org/haobtc/onekey/ui/activity/RecoveryHardwareOnceWallet.java
- electrum_gui/android/console.py
fix  recovery bug when cancel by user, the followed recovery operation will be abnormal
no
local
> fix recovery bug

- ios/CustomCode/Modules/Bluetooth/OKBlueManager.h
- ios/CustomCode/Modules/Bluetooth/OKBlueManager.m
- ios/CustomCode/Modules/Hardware/Controller/OKHWRestoreViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.h
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Restore/Controller/OKWordImportVC.m
- ios/CustomCode/Modules/Signature/Controller/OKSignatureViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKReceiveCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/WalletList/ViewController/OKSetWalletNameViewController.m
- ios/CustomCode/OneKeyImport.h
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS fix：scan to device duplicate
OneKeyHQ/TaskHub#892
OneKeyHQ/TaskHub#885
OneKeyHQ/TaskHub#887
OneKeyHQ/TaskHub#769
…
…
> iOS fix：scan to device duplicate

- electrum/eth_wallet.py
- electrum_gui/android/console.py
> save the infomation of contracts

- ios/CustomCode/Modules/Appreance/UIColor+OKAppreance.h
- ios/CustomCode/Modules/Appreance/UIColor+OKAppreance.m
- ios/CustomCode/Modules/Base/BaseViewController.m
- ios/CustomCode/Modules/Token/Management/OKTokenManModel.h
- ios/CustomCode/Modules/Token/Management/OKTokenManModel.m
- ios/CustomCode/Modules/Token/Management/OKTokenManagementController.m
- ios/CustomCode/Modules/Token/Management/View/OKIndexView.h
- ios/CustomCode/Modules/Token/Management/View/OKIndexView.m
- ios/CustomCode/Modules/Token/Management/View/OKTokenSectionCell.h
- ios/CustomCode/Modules/Token/Management/View/OKTokenSectionCell.m
- ios/CustomCode/Modules/Token/Tokens.storyboard
- ios/CustomCode/OneKeyImport.h
- ios/Support/OneKey.xcodeproj/project.pbxproj
iOS feature: erc20 management.
…
…
…
> iOS feature: erc20 management.

- .gitignore
- ios/.gitignore
- ios/iOS/OneKey.xcodeproj/project.pbxproj
- ios/iOS/OneKey.xcodeproj/project.pbxprojoriginal1
- ios/iOS/OneKey.xcodeproj/project.pbxprojoriginal2
- ios/iOS/OneKey.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ios/make_ios_project.sh
iOS improv: trace Xcode project files.
…
…
…
> iOS improv: trace xcode project files.

- electrum/eth_servers.json
- electrum/eth_wallet.py
- electrum/pywalib.py
- electrum_gui/android/console.py
1. 新增通过 coingecko 获取 erc20 价格
2. 价格定时任务改成 5 分钟获取一次
3. 统一 erc20 余额相关字段，并按法币从大到小排序，如果法币价格相同就按币数量排序
…
…
…
> get token price from coingecko

- electrum_gui/common/provider/clients/eth/blockbook.py
- electrum_gui/common/provider/configs/providers.json
1. 修改配置，ETH主网新增 https://api.etherscan.io，ETH 测试网新增 https://ropsten1.trezor.io
…
…
…
> adjust configs of eth provider

- electrum/eth_wallet.py
- electrum/pywalib.py
- electrum_gui/android/console.py
- electrum_gui/common/provider/clients/eth/blockbook.py
- electrum_gui/common/provider/clients/eth/etherscan.py
- electrum_gui/common/provider/clients/eth/geth.py
- electrum_gui/common/provider/data.py
1. 调整 Transaction 的结构，同时兼容 UTXO 和 Account 类型
2. 支持获取 ERC20 交易历史
…
…
…
> supports erc20 tx history

- electrum_gui/android/console.py
- electrum_gui/common/provider/clients/eth/blockbook.py
> fix erc20 history

- android/app/src/main/java/org/haobtc/onekey/activities/base/MyApplication.java
- android/app/src/main/java/org/haobtc/onekey/bean/Assets.kt
- android/app/src/main/java/org/haobtc/onekey/bean/MainSweepcodeBean.java
- android/app/src/main/java/org/haobtc/onekey/bean/TransactionSummaryVo.kt
- android/app/src/main/java/org/haobtc/onekey/business/chain/bitcoin/BitcoinService.kt
- android/app/src/main/java/org/haobtc/onekey/business/chain/ethereum/EthService.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/DetailETHTransactionActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/DetailTransactionActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionCompletion.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionListFragment.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/OnekeyScanQrActivity.kt
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/SelectAccountBottomSheetDialog.kt
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.kt
+ 部分余额不展示问题
+ 优化交易详情展示，修复部分不展示问题
+ 首页扫码部分情况下不展示结果页的问题
+ 首页扫码崩溃的问题
+ 首页扫码切换账户失败问题
+ 修复首页没有钱包可以刷新的问题
OneKeyHQ/TaskHub#937
OneKeyHQ/TaskHub#938
OneKeyHQ/TaskHub#935
OneKeyHQ/TaskHub#932
OneKeyHQ/TaskHub#928
…
…
> Android:Wallet Fix bugs

- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceList/OKDeviceListViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceSettingHome/OKDeviceSettingsViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateInstallController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceVerify/OKDeviceVerifyController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceVerify/OKDeviceVerifyResultController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKDeviceChangePINController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKDeviceDeleteController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKDeviceInfoViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKDeviceLanguageViewController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKDeviceOffController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKDeviceShowXPUBController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/OKResetDeviceWarningViewController.m
Replace with regex:
`MyLocalizedString\(@"([\w.\s]+)"\s*,\s*nil\)
@"$1".localized`
…
…
…
> iOS improv: refactor.

- android/app/src/main/java/org/haobtc/onekey/adapter/WalletAssetAccountAdapter.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionDetailWalletActivity.java
+ 修复全部资产页面跳转到资产详情币种展示错误
OneKeyHQ/TaskHub#931
OneKeyHQ/TaskHub#944
…
…
> Android:Wallet fix details of all assets jump currency

- ios/CustomCode/Modules/Manager/OKPyCommandsManager.h
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTransferCompleteController.h
- ios/CustomCode/Modules/Tab_Wallet/OKTransferCompleteController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tab_Wallet/Tab_Wallet.storyboard
- ios/CustomCode/OneKeyImport.h
- ios/Resources/zh-Hans.lproj/Localizable.strings
- ios/iOS/podfile
iOS feature:Home page to add refresh and Token entry
…
…
…
> iOS feature:Home page to add refresh and Token entry

- electrum/eth_wallet.py
- electrum_gui/android/console.py
解决了 eth转账时报错问题
https://github.com/OneKeyHQ/TaskHub/issues/945
…
> Fix eth wallet transfer error reporting

- ios/CustomCode/Modules/Manager/OKPyCommandsManager.h
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.m
iOS feature：Switch the wallet interface for replacement
…
…
> iOS feature：Switch the wallet interface for replacement

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendEthActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/CustomCenterDialog.java
- android/app/src/main/res/layout/center_dialog_tip.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
添加：转账页面 扫码识别账户类型提示弹框
OneKeyHQ/TaskHub#929
…
…
> fix scan wrong address

- ios/CustomCode/Modules/Appreance/UIColor+OKAppreance.h
- ios/CustomCode/Modules/Appreance/UIColor+OKAppreance.m
- ios/CustomCode/Modules/Base/BaseViewController.h
- ios/CustomCode/Modules/Base/BaseViewController.m
iOS feature: auto show/hide navbar separator.
…
…
<@张效良> <@ios>
> iOS feature: auto show/hide navbar separator.

- android/app/src/main/java/org/haobtc/onekey/adapter/SelectTokenAdapter.kt
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/SelectTokenActivity.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/TokenManagerActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendEthActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseActivity.java
修复硬件转账失败
修复代币展示精度
修复转账代币单位错误
ETH钱包没有ETH余额为0，有代币仍可以转账bug修复
代币列表页字母索引不准确修复
OneKeyHQ/TaskHub#934
OneKeyHQ/TaskHub#925
OneKeyHQ/TaskHub#941
OneKeyHQ/TaskHub#930
…
…
> fix transfer error

- electrum/eth_wallet.py
删除合约地址前先把合约地址转换成 checksum 格式，因为添加时也是已 checksum 格式添加
…
…
…
> fix bug - delete_token

- electrum_gui/android/console.py
> sort wallets by fait of per wallet

- electrum/eth_token_list.json
修改tokenlist中的热门token跟coingecko的保持一致
…
…
…
> Sorted by popularity

- android/app/src/main/java/org/haobtc/onekey/constant/PyConstant.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
1.  fix hardware wallet sign verify always failed bug
2. update submodule python-trezor index
3. change button request code
OneKeyHQ/TaskHub/issues/911
local
> fix hardware wallet sign verify always failed bug

- android/app/src/main/java/org/haobtc/onekey/ui/dialog/TransactionConfirmDialog.java
- android/app/src/main/res/layout/send_confirm_dialog.xml
修复Eth转账最多18位，确认交易框显示的数量折行显示问题
OneKeyHQ/TaskHub#952
…
…
> fix transfer account show problem

- electrum/eth_token_list.json
> Replace the icon with a clearer one

- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Manager/OKHwNotiManager.h
- ios/CustomCode/Modules/Manager/OKWalletManager.h
- ios/CustomCode/Modules/SelectAssetType/Controller/SelectAssetType.storyboard
- ios/CustomCode/Modules/Tab_Wallet/Model/OKWalletInputFeeViewCallBackModel.h
- ios/CustomCode/Modules/Tab_Wallet/Model/OKWalletInputFeeViewCallBackModel.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tab_Wallet/View/OKWalletInputFeeView.h
- ios/CustomCode/Modules/Tab_Wallet/View/OKWalletInputFeeView.m
- ios/CustomCode/Modules/Tab_Wallet/View/OKWalletInputFeeView.xib
- ios/Resources/zh-Hans.lproj/Localizable.strings
- ios/iOS/OneKey.xcodeproj/project.pbxproj
iOS Feature :ETH custom transfer
…
…
> IOS Feature :ETH custom transfer

- electrum/pywalib.py
修复 https://github.com/OneKeyHQ/TaskHub/issues/940
…
…
…
> fix get_eth_tx_info

- electrum_gui/android/console.py
调整排序规则
有资金钱包放前面，按资金量倒序；无资金钱包放后面，按时间倒序
https://github.com/OneKeyHQ/TaskHub/issues/930
…
…
> adjust sorting rule at get_all_wallet_balance

- ios/CustomCode/Modules/Appreance/UITableView+OKRoundSection.h
- ios/CustomCode/Modules/Appreance/UITableView+OKRoundSection.m
- ios/CustomCode/Modules/Base/BaseViewController.h
- ios/CustomCode/Modules/Base/BaseViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKAllAssetsViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKTokenSelectController.h
- ios/CustomCode/Modules/Tab_Mine/Controller/OKTokenSelectController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/Tab_Mine.storyboard
- ios/CustomCode/Modules/Tab_Mine/Model/OKAllAssetsCellModel.h
- ios/CustomCode/Modules/Tab_Mine/View/OKAllAssetsTableViewCell.m
- ios/CustomCode/Modules/Token/Model/OKTokenManModel.m
- ios/CustomCode/Modules/Token/Model/OKTokenManager.h
- ios/CustomCode/Modules/Token/Model/OKTokenManager.m
- ios/iOS/OneKey.xcodeproj/project.pbxproj
iOS feature: ERC 20 select.
…
…
…
> iOS feature: ERC 20 select.

- android/app/src/main/java/org/haobtc/onekey/business/wallet/TokenManager.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/TokenManagerActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletListActivity.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.kt
+ 修复自定义添加 ERC20 首页不展示的问题
+ ERC20 TokenManager 添加软引用缓存，提升首页加载性能。
+ 优化资产缓存的刷新方式
…
…
…
> Android:Wallet Fix custom erc20 issues

- ios/CustomCode/Modules/Hardware/Controller/Hardware.storyboard
- ios/CustomCode/Modules/Hardware/Controller/OKDeviceSuccessViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Restore/Model/OKFindWalletTableViewCellModel.m
- ios/CustomCode/Modules/Signature/Controller/OKSignatureViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tab_Wallet/Tab_Wallet.storyboard
- ios/Resources/zh-Hans.lproj/Localizable.strings
- ios/iOS/OneKey.xcodeproj/project.pbxproj
iOS fix:Solve the problem of continuous click signature
…
…
> iOS fix:Solve the problem of continuous click signature

- android/app/src/main/res/layout/active_successful_fragment.xml
- android/app/src/main/res/layout/confirm_on_hardware_activity.xml
- android/app/src/main/res/layout/fragment_update_pin_confirm.xml
- android/app/src/main/res/layout/input_on_hardware.xml
- electrum/wallet.py
修复连接硬件相关页面在屏幕高度低的手机上的适配问题
提交python 改动代码
OneKeyHQ/TaskHub#950
…
…
> fix ui show

- ios/make_ios_project.sh
> iOS fix: CI

- android/app/src/main/java/org/haobtc/onekey/ui/dialog/SelectAccountBottomSheetDialog.kt
扫描弹出的账户列表添加当前钱包类型：BTC 或者 ETH 账户
…
…
> Scan account pop-up to add a clear account name

- electrum_gui/android/console.py
将 eth 交易的 data 字段解析成字节码, 硬件交互需要
…
…
…
> convert eth tx data to bytes

- electrum/pywalib.py
如果发送地址是自己就展示收款地址，否则展示发送地址
…
…
…
> fix address filed

- electrum_gui/android/hardware.py
根据前端需求　开放Initialize硬件功能给前端
…
- [] Bugfix
python
…
> Open hardware initialization interface

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendEthActivity.java
> fix Select Token to monitor token balance when transferring money

- ios/CustomCode/Categories/NSString+OKAdd.h
- ios/CustomCode/Categories/NSString+OKAdd.m
- ios/CustomCode/Modules/ImportWallet/ViewController/OKObserveImportViewController.m
- ios/CustomCode/Modules/ImportWallet/ViewController/OKPrivateImportViewController.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.h
- ios/CustomCode/Modules/Manager/OKWalletManager.h
- ios/CustomCode/Modules/Manager/OKWalletManager.m
- ios/CustomCode/Modules/PassWord/OKWalletInfoModel.h
- ios/CustomCode/Modules/PassWord/OKWalletInfoModel.m
- ios/CustomCode/Modules/ScanQR/OKQRScanResultController.h
- ios/CustomCode/Modules/ScanQR/OKQRScanResultController.m
- ios/CustomCode/Modules/ScanQR/OKWalletScanVC.h
- ios/CustomCode/Modules/ScanQR/OKWalletScanVC.m
- ios/CustomCode/Modules/ScanQR/Scan.storyboard
- ios/CustomCode/Modules/Signature/Controller/OKSignatureViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Token/Management/View/OKTokenCell.m
- ios/CustomCode/Modules/Token/Model/OKTokenManModel.m
- ios/CustomCode/Modules/Token/Model/OKTokenManager.m
- ios/CustomCode/Modules/WalletList/ChangeWallet/OKChangeWalletCell.h
- ios/CustomCode/Modules/WalletList/ChangeWallet/OKChangeWalletCell.m
- ios/CustomCode/Modules/WalletList/ChangeWallet/OKChangeWalletController.h
- ios/CustomCode/Modules/WalletList/ChangeWallet/OKChangeWalletController.m
- ios/CustomCode/Modules/WalletList/ViewController/WalletList.storyboard
- ios/Resources/en.lproj/Localizable.strings
- ios/Resources/zh-Hans.lproj/Localizable.strings
- ios/iOS/OneKey.xcodeproj/project.pbxproj
iOS feature: wallet change.
…
…
…
> iOS feature: wallet change.

- ios/CustomCode/Modules/ImportWallet/ViewController/OKKeystoreImportViewController.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.h
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Manager/OKWalletManager.h
- ios/CustomCode/Modules/Manager/OKWalletManager.m
- ios/CustomCode/Modules/Signature/Controller/OKSignatureViewController.m
- ios/CustomCode/Modules/Tab_Wallet/Model/OKAssetTableViewCellModel.h
- ios/CustomCode/Modules/Tab_Wallet/OKPrivateKeyExportViewController.h
- ios/CustomCode/Modules/Tab_Wallet/OKPrivateKeyExportViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTransferCompleteController.h
- ios/CustomCode/Modules/Tab_Wallet/OKTransferCompleteController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxDetailViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxListViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxViewController.h
- ios/CustomCode/Modules/Tab_Wallet/OKTxViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletDetailViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tab_Wallet/Tab_Wallet.storyboard
- ios/CustomCode/Modules/Tab_Wallet/View/OKTxTableViewCell.m
- ios/CustomCode/Modules/Tab_Wallet/View/OKWalletInputFeeView.m
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
- ios/iOS/OneKey.xcodeproj/project.pbxproj
iOS feature:Erc20 transfer
…
…
> iOS feature:Erc20 transfer

- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendEthActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/CustomEthFeeDialog.java
- android/app/src/main/res/layout/custom_fee_eth.xml
修复硬件转token 错误
修改 自定义费率 输入gas_price 和 gas_limmit 时校验方式
…
…
…
> fix hardware transfer token

- ios/CustomCode/Modules/Tab_Mine/Controller/OKTokenSelectController.h
- ios/CustomCode/Modules/Tab_Mine/Controller/OKTokenSelectController.m
- ios/CustomCode/Modules/Tab_Mine/Model/OKAllAssetsCellModel.h
- ios/CustomCode/Modules/Tab_Mine/View/OKAllAssetsTableViewCell.m
- ios/CustomCode/Modules/Tab_Wallet/OKSendCoinViewController.m
iOS feature: token select support native token.
…
…
…
> iOS feature: token select support native token.

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendEthActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/CustomEthFeeDialog.java
- android/app/src/main/java/org/haobtc/onekey/utils/CoinDisplayUtils.kt
- android/app/src/main/res/layout/custom_fee_eth.xml
修改ETH自定义费率
硬件转token 显示单位错误
OneKeyHQ/TaskHub#994
…
…
> when custom fee add judge account balance

- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Manager/OKWalletManager.h
- ios/CustomCode/Modules/Manager/OKWalletManager.m
- ios/CustomCode/Modules/Signature/Controller/OKVerifySignatureViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKHDWalletViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletDetailViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/WalletList/Model/OKWalletListTableViewCellModel.h
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.m
iOS feature:Wallet list sorting
…
…
> iOS feature:Wallet list sorting

- android/app/src/main/java/org/haobtc/onekey/adapter/HotTokenAdapter.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/TokenManagerActivity.java
> fix token list add error

- electrum/pywalib.py
> raise exception if transaction send fail

- electrum/eth_wallet.py
- electrum/plugins/trezor/trezor.py
- electrum/pywalib.py
- electrum/wallet.py
- electrum_gui/android/console.py
dapp 支持
1. 新增 dapp_eth_rpc_info，返回当前币种的 RPC 链接和 chain_id (支持 ETH/BSC/HECO)
```
ac.dapp_eth_rpc_info()
> {"rpc": "https://ropsten.infura.io/v3/f001ce716b6e4a33a557f74df6fe8eff", "chain_id": 3}
```
2. 新增 dapp_eth_sign_tx 接口（因为入参和返回数据跟 sign_eth_tx 不同，不能复用）：
```
ac.dapp_eth_sign_tx({"from": "0x9858EfFD232B4033E47d90003D41EC34EcaEda94", "to": "0x995E409d0c6230bF2405C925baF3A0FCCe674A55", "value": 1}, password="123", path=None)
> {"raw": "0xf8646b8504a817c80082520894995e409d0c6230bf2405c925baf3a0fcce674a5501802aa04919d4c1f83639fd07b7a9a5d5c21be0909e25d1a6dcd7a55389c9e783a8bc17a01ee9bd3546fd4d4a52ab54ebb3bb37e70fb783958c4ecac6b532de9258980699", "tx": {"nonce": "0x6b", "gasPrice": "0x4a817c800", "gas": "0x5208", "value": "0x1", "to": "0x995e409d0c6230bf2405c925baf3a0fcce674a55", "data": "0x", …
```
> supports eth dapp

- electrum_gui/common/provider/clients/eth/geth.py
> get_balance of geth supports token

- electrum_gui/android/console.py
- electrum_gui/common/coin/daos.py
- electrum_gui/common/coin/data.py
- electrum_gui/common/coin/manager.py
- electrum_gui/common/coin/migrations/0001_create_coin_model.py
- electrum_gui/common/coin/models.py
- electrum_gui/common/conf/settings.py
> save token in db

- electrum/daemon.py
- electrum/eth_wallet.py
- electrum/wallet.py
- electrum_gui/android/console.py
- electrum_gui/android/helpers.py
- electrum_gui/android/wallet_context.py
主要目的是后面的几个commit，整理原来的`create()`方法，将钱包创建的逻辑归类到对应的钱包类中去。
前面是一些铺垫和辅助方法的整理。
解决了一个不同链上可能产生相同地址故而造成文件名相同的问题。解决办法是用链+地址来生成哈希值。
后续会根据前面几个commit引入的辅助方法/属性来整理`console.py`中的其他地方。
目前`create()`方法还是过于复杂（虽然已经减少到21个分支...），后面再考虑是否需要按照币种分割该方法。
N/A
…
基于 #522，#522 未合并前review需要跳过前面的几个
> Console split

- android/app/src/main/java/org/haobtc/onekey/manager/BleManager.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/ConnectDeviceDialog.kt
- electrum/pywalib.py
> Android:Wallet fixed build error

- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Token/Management/OKTokenManagementController.m
- ios/CustomCode/Modules/Token/Management/View/OKTokenCell.h
- ios/CustomCode/Modules/Token/Management/View/OKTokenCell.m
- ios/CustomCode/Modules/Token/Model/OKTokenManager.m
iOS fix: sync tokens selection.
…
…
…
> iOS fix: sync tokens selection.

- electrum_gui/android/console.py
因为 iOS 没有 keccak 哈希方法，需要向上层暴露 keccak @CivelXu 
…
…
…
> export keccak function as interface

- android/app/src/main/java/org/haobtc/onekey/business/wallet/DeviceManager.kt
- android/app/src/main/java/org/haobtc/onekey/exception/PyEnvException.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/Web3View.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/ConnectDeviceDialog.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappBrowserFragment.kt
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ 修复部分情况下， Dapp 网页加载成功，却展示连接失败。
+ 添加 Dapp 连接硬件时，检查强制更新，并提示去更新。
…
…
…
> Fix dapp error

- electrum_gui/android/hardware.py
> Default passphrase is not available when activated

- electrum_gui/android/console.py
1.删除所有没用的日志信息
2.根据前端需要 恢复钱包时如果没有查找到有交易记录的文件 要给前端返回每个币种第一个钱包的钱包名
Android
…
> Delete print log and fix bug

- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.h
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Manager/OKUserSettingManager.h
- ios/CustomCode/Modules/Manager/OKUserSettingManager.m
- ios/CustomCode/Modules/SelectAssetType/Controller/OKSelectAssetTypeController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKNetworkViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/Tab_Mine.storyboard
- ios/CustomCode/Modules/Tab_Mine/NetSeting/NetSeting.storyboard
- ios/CustomCode/Modules/Tab_Mine/NetSeting/OKBrowserETHTableViewController.h
- ios/CustomCode/Modules/Tab_Mine/NetSeting/OKBrowserETHTableViewController.m
- ios/CustomCode/Modules/Tab_Mine/NetSeting/OKNetTableViewCell.m
- ios/CustomCode/Modules/Tab_Mine/NetSeting/OKNetTableViewCellModel.h
- ios/CustomCode/Modules/Tab_Wallet/OKReceiveCoinViewController.h
- ios/CustomCode/Modules/Tab_Wallet/OKReceiveCoinViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxDetailViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKTxListViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tab_Wallet/Tab_Wallet.storyboard
- ios/CustomCode/Notification.h
- ios/Resources/ETHBrowser.plist
- ios/Resources/zh-Hans.lproj/Localizable.strings
- ios/iOS/OneKey.xcodeproj/project.pbxproj
iOS feature：ETH Block Browser
…
…
> iOS feature：ETH Block Browser

- android/app/src/main/java/org/haobtc/onekey/activities/settings/BlockChooseActivity.java
- android/app/src/main/java/org/haobtc/onekey/extensions/String.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/Web3View.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappBrowserFragment.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappSettingSheetDialog.kt
- android/app/src/main/res/layout/activity_block_choose.xml
- android/app/src/main/res/layout/dialog_dapp_setting_sheet.xml
- android/app/src/main/res/layout/view_block_browser_hint.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
+ 修改 Dapp 浏览器账户展示名称为地址后四位
+ 修改设置 ETH 区块浏览器，名称展示错误问题
+ 关闭 Dapp 浏览器可以缩放网页的功能
…
…
…
> Fix dapp UI

- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappBrowserFragment.kt
> Android:Wallet modify Dapp browser title

- electrum_gui/common/basic/functional/signal.py
- electrum_gui/common/basic/functional/timing.py
- electrum_gui/common/basic/ticker/__init__.py
- electrum_gui/common/basic/ticker/signals.py
- electrum_gui/common/basic/ticker/ticker.py
- electrum_gui/common/basic/ticker/utils.py
- electrum_gui/common/the_begging.py
1. timing logger
2. ticker signal
…
…
…
> timing logger and ticker signal

- electrum/bsc_token_list.json
- electrum/eth_servers.json
- electrum/eth_wallet.py
- electrum/heco_token_list.json
- electrum/tbsc_token_list.json
- electrum/theco_token_list.json
- electrum/util.py
- electrum/wallet_db.py
- electrum_gui/android/console.py
- electrum_gui/android/wallet_context.py
- electrum_gui/common/coin/configs/testnet_chains.json
- electrum_gui/common/provider/configs/providers.json
1. 加入 bsc 和 heco 的配置
2. HD 钱包支持 bsc 和 heco
3. 加入 token list
…
…
…
> Fix support for bsc and heco

- electrum_gui/common/coin/codes.py
- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/coins.json
- electrum_gui/common/coin/daos.py
- electrum_gui/common/coin/manager.py
- electrum_gui/common/conf/settings.py
- electrum_gui/common/price/channels/coingecko.py
- electrum_gui/common/price/daos.py
- electrum_gui/common/price/data.py
- electrum_gui/common/price/interfaces.py
- electrum_gui/common/price/manager.py
- electrum_gui/common/price/migrations/0001_create_price.py
- electrum_gui/common/price/models.py
- electrum_gui/common/the_begging.py
price manager，方便获取价格
依赖 https://github.com/OneKeyHQ/electrum/pull/574
后续我还会实现定时触发机制
…
…
…
> price manager

- android/app/src/main/java/org/haobtc/onekey/adapter/OnekeyTxListAdapter.java
fix transaction log with 0 removed plus and minus sign
OneKeyHQ/TaskHub#1028
…
…
> Fixed transaction log with 0 removed plus and minus sign

- .github/workflows/ios-app-lint.yml
iOS fix:Update xcode version
…
…
> iOS fix:Update xcode version

- ios/CustomCode/Modules/Tab_Mine/Controller/OKMineViewController.m
- ios/iOS/podfile
> fix bug:change password

- ios/Resources/zh-Hans.lproj/Localizable.strings
- ios/iOS/podfile
> iOS fix: text revise.

- ios/CustomCode/Modules/Tab_Mine/Controller/OKDeleteWalletTipsViewController.m
- ios/iOS/podfile
iOS improv: disable biometrics while deleting HD wallet.
https://github.com/OneKeyHQ/TaskHub/issues/876
…
…
> iOS improv: disable biometrics while deleting HD wallet.

- .github/workflows/ios-app-build.yml
iOS fix: CI Xcode version update.
…
…
…
> iOS fix: CI xcode version update.

- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceVerify/OKDeviceVerifyController.m
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceVerify/OKDeviceVerifyResultController.h
- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceVerify/OKDeviceVerifyResultController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS improv: HW verify network error prompt.
https://github.com/OneKeyHQ/TaskHub/issues/923
…
…
> iOS improv: HW verify network error prompt.

- electrum/eth_servers.json
- electrum_gui/common/provider/configs/providers.json
> replace rpc of theco

- electrum_gui/common/provider/clients/eth/blockbook.py
这个接口有时返回的数据里某些 token 没有 balance 字段
…
…
…
> fixed the error of getting balance from blockbook

- ios/CustomCode/Modules/Base/BaseNavigationController.h
- ios/CustomCode/Modules/Base/BaseNavigationController.m
- ios/CustomCode/Modules/Base/BaseViewController.h
- ios/CustomCode/Modules/Base/BaseViewController.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKAllAssetsViewController.m
- ios/CustomCode/Modules/Tab_Mine/Controller/OKTokenSelectController.m
- ios/CustomCode/Modules/Token/Management/OKTokenManagementController.m
> iOS improv: UI related.

- ios/CustomCode/Modules/Base/BaseViewController.h
- ios/CustomCode/Modules/Base/BaseViewController.m
iOS fix: nav appearance
iOS fix: nav appreance
…
…
> iOS fix: nav appearance

- electrum/pywalib.py
修复并发问题
复现：
先调用 get_all_wallet_balance，在网络查询期间调用 switch_wallet，等 get_all_wallet_balance 执行完后
发现最终的配置不是 switch_wallet 指定的配置
…
…
…
> fix concurrency issue in override_server

- ios/CustomCode/Modules/Manager/OKUserSettingManager.h
- ios/CustomCode/Modules/Manager/OKUserSettingManager.m
- ios/CustomCode/Modules/Tab_Wallet/Model/OKNotiAssetModel.m
- ios/CustomCode/Modules/Tab_Wallet/Model/OKSwitchWalletModel.h
- ios/CustomCode/Modules/Tab_Wallet/Model/OKSwitchWalletModel.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tab_Wallet/View/OKAssetTableViewCell.m
- ios/iOS/OneKey.xcodeproj/project.pbxproj
iOS feature:Optimize the front page data structure
> iOS feature:Optimize the front page data structure

- android/app/src/main/java/org/haobtc/onekey/ui/dialog/custom/CustomEthFeeDialog.java
- android/app/src/main/java/org/haobtc/onekey/viewmodel/AppWalletViewModel.kt
修复BSC/HECO 首页展示为：HT/BNB
修复 BSC/HECO 自定义费率的单位
调整自定义费率gas_price 最低 从  0.4 调整为1.0 
…
…
…
> fix heco/bsc display name

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/HdWalletDetailActivity.java
修复ETH 链 (HECO/BSC) 不应该支持导出助记词
OneKeyHQ/TaskHub#1054
…
…
> fix bsc/heco wallet details page

- android/app/src/main/java/org/haobtc/onekey/business/chain/ethereum/EthService.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/DetailETHTransactionActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionCompletion.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/TransactionListFragment.kt
- android/app/src/main/java/org/haobtc/onekey/utils/NavUtils.java
+ 修复 heco、bsc 转账详情页无法跳转到区块浏览器的问题
OneKeyHQ/TaskHub#1057
…
…
> Android:Wallet fix heco、bsc Block Browser jump

- electrum/eth_servers.json
- electrum/eth_wallet.py
- electrum/pywalib.py
- electrum_gui/android/console.py
- electrum_gui/common/basic/functional/wraps.py
- electrum_gui/common/coin/codes.py
- electrum_gui/common/coin/configs/testnet_chains.json
- electrum_gui/common/coin/configs/testnet_coins.json
- electrum_gui/common/coin/daos.py
- electrum_gui/common/coin/manager.py
- electrum_gui/common/conf/settings.py
- electrum_gui/common/price/manager.py
1. 前置 coin manager 新增 tbtc
2. 新增 cache_it
3. 替换 eth wallet 获取币价方式
…
…
后续我再改 btc wallet 的
> migrate the way to get the price of eth wallet

- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendEthActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/process/SendHdActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/CustomizeFeeDialog.java
- 修复BTC 转账本地保存的自定义费率错误
- 修复转账发送方显示的是Chain Name
- 修改蓝牙连接后获取版本方法
OneKeyHQ/TaskHub#1011
…
…
> fix BTC custome fee show

- electrum_gui/android/console.py
修复 https://github.com/OneKeyHQ/electrum/pull/619 原本打算引入，但后来删除的 wallet 的 chain_code 字段 
https://github.com/OneKeyHQ/TaskHub/issues/1067
…
…
> fix chain_code field not exist

- android/app/src/main/java/org/haobtc/onekey/ui/activity/CreatePersonalWalletActivity.java
修复硬件创建BSC/HECO 类型为eth
no issue
…
…
> fix hardware add heco/bsc error parameter

- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Token/Management/OKTokenManagementController.m
- ios/CustomCode/Modules/WalletList/ViewController/OKSetWalletNameViewController.m
- ios/CustomCode/Notification.h
iOS feature：Add Token Notification
…
…
> iOS feature：Add Token Notification

- android/app/src/main/java/org/haobtc/onekey/asynctask/BusinessAsyncTask.java
- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/HardwareUpgradeActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SearchDevicesActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/fragment/HardwareUpgradingFragment.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/Ble.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/proxy/RequestImpl.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/proxy/RequestLisenter.java
- android/blelibrary/src/main/java/cn/com/heaton/blelibrary/ble/request/ConnectRequest.java
1. fix firmware update page display error
2. fix ble library `disconnectAll` method's bug(concurrent modify)
3. concurrent protect bug which would cause app into a unnormal state
4. delete device_id protect logic when ble direct connect by mac
OneKeyHQ/TaskHub/issues/1061
local
nil
> fix some known issue

- electrum/address_synchronizer.py
- electrum/eth_wallet.py
- electrum/wallet.py
- electrum_gui/android/console.py
- 修复 #557 中从seed创建钱包整理代码引入的错误
- BTC支持展示详细的输入输出信息（地址和金额）
https://github.com/OneKeyHQ/TaskHub/issues/629
Python
…
> Details input and output

- android/app/src/main/java/org/haobtc/onekey/manager/PyEnv.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/bean/Web3Transaction.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappActionSheetDialog.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappBrowserFragment.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappFeeCustomSheetDialog.kt
- android/app/src/main/java/org/haobtc/onekey/ui/widget/CustomFeeSelectionView.kt
- android/app/src/main/java/org/haobtc/onekey/ui/widget/FeeSelectionView.kt
- android/app/src/main/java/org/haobtc/onekey/utils/ToastUtils.java
- android/app/src/main/res/drawable/laft_gray_top_tuo.xml
- android/app/src/main/res/layout/activity_agent_server.xml
- android/app/src/main/res/layout/dialog_dapp_action_sheet.xml
- android/app/src/main/res/layout/dialog_dapp_fee_custom_sheet.xml
- android/app/src/main/res/layout/view_fee_custom_selection.xml
- android/app/src/main/res/layout/view_fee_selection.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/values/styles.xml
+ Dapp 自定义手续费
+ OneKeyHQ/TaskHub#988
…
…
> Android:Wallet add dapp fee custom

- electrum/eth_wallet.py
> Fix the problem of ETH signature verification failure

- ios/CustomCode/Modules/Tab_Mine/HardwareSetting/DeviceUpdate/OKDeviceUpdateViewController.m
iOS fix: device update vc back button.
…
…
…
> iOS fix: device update vc back button.

- ios/CustomCode/Modules/Tab_Mine/Controller/OKNetworkViewController.m
- ios/CustomCode/Modules/Tab_Mine/NetSeting/OKBrowserBTCTableViewController.m
iOS fix:eth browser refresh
OneKeyHQ/TaskHub#1078
…
…
> iOS fix:eth browser refresh

- ios/CustomCode/Categories/NSString+OKAdd.h
- ios/CustomCode/Categories/NSString+OKAdd.m
- ios/CustomCode/Modules/PassWord/OKWalletInfoModel.h
- ios/CustomCode/Modules/PassWord/OKWalletInfoModel.m
- ios/CustomCode/Modules/Tab_Discover/DAppBrowser/DAppWebManage.swift
- ios/CustomCode/Modules/Tab_Discover/OKDAppWebViewController.swift
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/WalletList/ChangeWallet/OKChangeWalletCell.h
- ios/CustomCode/Modules/WalletList/ChangeWallet/OKChangeWalletCell.m
- ios/CustomCode/Modules/WalletList/ChangeWallet/OKChangeWalletController.h
- ios/CustomCode/Modules/WalletList/ChangeWallet/OKChangeWalletController.m
- ios/CustomCode/Modules/WalletList/ViewController/WalletList.storyboard
iOS feature: Change wallet support BSC/HECO.
…
…
…
> iOS feature: Change wallet support BSC/HECO.

- ios/CustomCode/Modules/PassWord/OKWalletInfoModel.m
- ios/CustomCode/Modules/Tab_Mine/View/OKAllAssetsTableViewCell.m
- ios/CustomCode/Modules/Token/Model/OKTokenManager.m
- ios/CustomCode/Modules/WalletList/ChangeWallet/OKChangeWalletCell.m
iOS feature: Support BSC/HECO tokens.
…
…
…
> iOS feature: Support BSC/HECO tokens.

- ios/CustomCode/AppDelegate.m
- ios/CustomCode/Modules/Manager/OKWalletManager.h
- ios/CustomCode/Modules/Manager/OKWalletManager.m
- ios/CustomCode/Modules/Tab_Mine/NetSeting/NetSeting.storyboard
- ios/CustomCode/Modules/Tab_Wallet/OKTxDetailViewController.m
- ios/CustomCode/OneKey-Bridging-Header.h
- ios/CustomCode/OneKeyImport.h
- ios/iOS/podfile
> iOS feature:bugly add

- electrum_gui/common/provider/clients/eth/blockbook.py
- electrum_gui/common/provider/clients/eth/etherscan.py
- electrum_gui/common/provider/clients/eth/geth.py
- electrum_gui/common/provider/data.py
- electrum_gui/common/provider/interfaces.py
https://github.com/OneKeyHQ/electrum/pull/610 依赖，搜索交易列表支持分页
…
…
…
> supports paging

- ios/CustomCode/Categories/NSString+OKAdd.h
- ios/CustomCode/Categories/NSString+OKAdd.m
- ios/CustomCode/Modules/Tab_Mine/NetSeting/OKProxyServerTableViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS fix:Add IP address validation
OneKeyHQ/TaskHub#1090
…
…
> iOS fix:Add IP address validation

- android/app/src/main/java/org/haobtc/onekey/activities/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/extensions/Dialog.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/BaseAlertBottomDialog.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/ConnectDeviceDialog.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappActionSheetDialog.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappBrowserFragment.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappFeeCustomSheetDialog.kt
- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappSettingSheetDialog.kt
- android/app/src/main/java/org/haobtc/onekey/ui/activity/HardwarePinDialog.kt
- android/app/src/main/java/org/haobtc/onekey/ui/activity/SoftPassDialog.kt
- android/app/src/main/java/org/haobtc/onekey/ui/base/BaseActivity.java
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/SelectAccountBottomSheetDialog.kt
- android/app/src/main/res/layout/activity_find_device_no_backup.xml
- android/app/src/main/res/layout/dialog_dapp_action_sheet.xml
- android/app/src/main/res/values/styles.xml
+ 隐藏共管账户
+ 没有钱包账户也可以查看 Dapp
+ 适配部分 UI，兼容高版本系统底部 Bar 的颜色。
…
…
…
> Optimize dapp show

- android/app/src/main/java/org/haobtc/onekey/activities/AboutActivity.java
- android/app/src/main/java/org/haobtc/onekey/manager/MainFragmentFactory.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/HomeOneKeyActivity.java
- android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/MineFragment.java
- android/app/src/main/res/drawable/vector_headset.xml
- android/app/src/main/res/layout/activity_about.xml
- android/app/src/main/res/layout/activity_home_onekey.xml
- android/app/src/main/res/layout/fragment_mind.xml
- android/app/src/main/res/layout/fragment_tab_find.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/strings.xml
我的页面添加客服入口
OneKeyHQ/TaskHub#837
…
…
> add customer service entrance

- electrum/pywalib.py
- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/testnet_chains.json
- electrum_gui/common/coin/daos.py
- electrum_gui/common/coin/data.py
- electrum_gui/common/coin/registry.py
- electrum_gui/common/conf/settings.py
- electrum_gui/common/provider/clients/eth/blockbook.py
- electrum_gui/common/provider/clients/eth/etherscan.py
- electrum_gui/common/provider/clients/eth/geth.py
- electrum_gui/common/provider/data.py
- electrum_gui/common/transaction/daos.py
- electrum_gui/common/transaction/data.py
- electrum_gui/common/transaction/manager.py
- electrum_gui/common/transaction/migrations/0001_create_txaction.py
- electrum_gui/common/transaction/models.py
1. 前置调整 provider 模块，字段变更，新增字段，地址统一消息
2. 前置调整 coin 模块，新增字段，新增接口
3. 新增 transaction manager，同步交易，获取交易
…
…
接收 signal 自动触发机制后续加
> transaction manager

- ios/CustomCode/Categories/NSString+OKAdd.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/Manager/OKWalletManager.h
- ios/CustomCode/Modules/Manager/OKWalletManager.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.m
iOS fix:The case where the wallet list call failed
OneKeyHQ/TaskHub#1052
…
…
> iOS fix:The case where the wallet list call failed

- ios/CustomCode/CommonView/PanBottomAlertViewController.swift
- ios/CustomCode/CommonView/PanBottomAlertViewController.xib
- ios/CustomCode/Modules/Tab_Discover/OKDAppMenuSheetController.swift
- ios/CustomCode/Modules/Tab_Discover/OKTradeFeeViewController.swift
- ios/CustomCode/Modules/Tab_Discover/Tab_Discover.storyboard
- ios/Resources/en.lproj/Localizable.strings
- ios/Resources/zh-Hans.lproj/Localizable.strings
fix dapp custom transaction fees and ui display
…
…
…
> iOS: fix dapp custom transaction fees and ui display

- electrum_gui/android/console.py
- 清理掉update_interfaces
- 清理掉ticker_action和update_wallet，只留下update_status
- 清理掉一个Status Enum
N/A
N/A
No
> 清理部分console.py

- ios/CustomCode/Modules/Hardware/Controller/OKHWRestoreViewController.m
- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Hardware/Model/OKDeviceInfoModel.m
- ios/CustomCode/Modules/Manager/OKPyCommandsManager.m
- ios/CustomCode/Modules/PassWord/OKCreateResultModel.m
- ios/CustomCode/Modules/Restore/Model/OKFindWalletTableViewCellModel.h
- ios/CustomCode/Modules/Restore/View/OKFindWalletTableViewCell.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS feature:Remove DeviceID validation
…
…
> iOS feature:Remove DeviceID validation

- ios/CustomCode/Modules/Hardware/Controller/OKMatchingInCirclesViewController.m
- ios/CustomCode/Modules/Tab_Wallet/OKWalletViewController.mm
- ios/CustomCode/Modules/Tools/OKTools.h
- ios/CustomCode/Modules/Tools/OKTools.m
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.h
- ios/CustomCode/Modules/WalletList/ViewController/OKWalletListViewController.m
- ios/Resources/zh-Hans.lproj/Localizable.strings
iOS fix:In the connection tips
…
…
> iOS fix:In the connection tips

- electrum/pywalib.py
> fix 'TransactionFee' object has no attribute 'usage'

- android/app/src/main/java/org/haobtc/onekey/onekeys/dappbrowser/ui/DappFeeCustomSheetDialog.kt
- android/app/src/main/java/org/haobtc/onekey/ui/activity/OnekeyScanQrActivity.kt
- android/app/src/main/java/org/haobtc/onekey/ui/dialog/SelectAccountBottomSheetDialog.kt
- android/app/src/main/res/layout/dialog_dapp_fee_custom_sheet.xml
- android/app/src/main/res/values-zh/strings.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/strings.xml
+ 优化 Dapp 自定义手续费交互体验
+ 使用临时方案优化 ETH 系币种扫码转账体验
+ OneKeyHQ/TaskHub#915
…
…
> Optimize custom fee hint

- .gitmodules
update  project structure
local
none
> update electrum project structure

- electrum/pywalib.py
群里讨论的那两个用户的问题都是因为缺失 557 这行代码导致的，仅保留跟用户相关的行为
…
…
…
> filter action by address

- electrum/eth_wallet.py
- electrum_gui/android/console.py
经过跟前端和设计同学讨论 Eth fork链钱包首页展示的主币信息为主币symbol
…
…
…
> Eth fork chain master coin name display symbol

- electrum_gui/android/console.py
> migrate the way to get the price of btc wallet

- electrum_gui/android/console.py
需求变更 将主钱包名称由COIN-1修改为COIN(例如BTC-1修改为BTC)
…
…
…
> Master wallet name changed from COIN-1 to COIN

- electrum_gui/android/console.py
- electrum_gui/android/wallet_context.py
调整 token 相关接口的实现
https://github.com/OneKeyHQ/TaskHub/issues/1100
…
…
> adjust token related interfaces

- electrum_gui/android/console.py
- electrum_gui/common/transaction/manager.py
https://github.com/OneKeyHQ/electrum/pull/690 有遗漏，provider_manager 有部分调用忘记加上 chain_code
…
…
…
> missing chain_code

- electrum/bsc_token_list.json
- electrum/eth_wallet.py
- electrum_gui/android/console.py
- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/testnet_chains.json
commit1：跟前端讨论 显示资金的接口返回主币和token的icon信息
commit2：返回前端的balance按照指定精度返回 （https://github.com/OneKeyHQ/TaskHub/issues/415）
commit3：前期因为bsc的icon特别模糊 所以请产品同事设计了一套bsc 的icon放到了我们自己的服务器上，这个commit就是修改对应的icon路径
…
python
…
> Return icon information

- electrum/plugins/trezor/clientbase.py
- electrum/util.py
- electrum_gui/android/console.py
- electrum_gui/android/derived_info.py
- electrum_gui/android/hardware.py
- electrum_gui/android/wallet_context.py
1.  remove  redundant hardware request like `get-features` or` get-xpub` when recovery wallet
2. update get-features comments 
local
none
> optimize hardware wallets' recovery process

- electrum/MutiBase.py
- electrum/eth_wallet.py
- electrum/keystore.py
- electrum/util.py
- electrum/wallet.py
- electrum_gui/android/console.py
- electrum_gui/android/derived_info.py
- electrum_gui/android/helpers.py
- electrum_gui/android/wallet_context.py
钱包支持自定义path（https://github.com/OneKeyHQ/TaskHub/issues/966）
…
Python
…
> Support for custom path

- electrum/pywalib.py
- electrum_gui/common/provider/chains/eth/clients/blockbook.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
- electrum_gui/common/provider/chains/eth/clients/utils.py
- electrum_gui/common/provider/data.py
识别特定广播异常
https://github.com/OneKeyHQ/TaskHub/issues/1038
https://github.com/OneKeyHQ/TaskHub/issues/1050
…
…
> recognize specific broadcast errors

- contrib/make_locale
- electrum/locale/messages.pot
> fix translation script

- electrum/eth_wallet.py
- electrum/keystore.py
- electrum/wallet.py
- electrum_gui/android/console.py
修复自定义path的eth钱包导出私钥错误问题
https://github.com/OneKeyHQ/TaskHub/issues/1229
Python
…
> Fix an error reported for exporting private keys

- electrum/eth_wallet.py
- electrum/keystore.py
- electrum/wallet.py
- electrum_gui/android/console.py
- electrum_gui/android/derived_info.py
commit1:解决联调过程中发现的创建hd钱包错误
commit2:修改上周五讨论的精度问题，目前python端返回准确的精度 并且根据前端页面修改 增加了BTC资产和coin类型的支持
commit3:由于前端页面改动 需要给前端返回判断文件是否存在的接口，这个commit就是支持这个功能
https://github.com/OneKeyHQ/TaskHub/issues/1210
https://github.com/OneKeyHQ/TaskHub/issues/1224
https://github.com/OneKeyHQ/TaskHub/issues/1225
https://github.com/OneKeyHQ/TaskHub/issues/1238
Python端测试通过
…
> Format return value for verify legality and fix bug

- electrum/bsc_token_list.json
- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/testnet_chains.json
更新图标链接地址为onekey子域名
No
N/A
@loatheb heco的图标找不到，需要你帮助处理下
> coin config: update link addresses of icons

- electrum/pywalib.py
如果预估费率失败主动报错。
中文翻译（未添加）：`获取费率失败，请重试`
…
…
…
> raise exception if error in estimating gas

- contrib/make_locale
> Fixing a source file generation failure

- electrum_gui/android/console.py
> Fixing parameter name definition irregularities

- electrum_gui/common/provider/chains/eth/clients/blockbook.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
通过最新区块时间来确认 is_ready 字段，超过两分钟算是服务失能
…
…
…
> Calculate is_ready by the latest blocktime

- electrum_gui/android/console.py
移除地址二维码的币种前缀
https://github.com/OneKeyHQ/TaskHub/issues/1254
…
…
> remove coin prefix of showing address

- electrum_gui/common/coin/configs/chains.json
给 BSC 和 HECO 分别新增官方节点和浏览器支持
…
…
…
> Add client fallback for bsc and heco

- electrum_gui/common/basic/orm/test_utils.py
- electrum_gui/common/conf/settings.py
- electrum_gui/common/secret/bip32/__init__.py
- electrum_gui/common/secret/bip32/base.py
- electrum_gui/common/secret/bip32/ed25519.py
- electrum_gui/common/secret/bip32/secp256k1.py
- electrum_gui/common/secret/bip32/secp256r1.py
- electrum_gui/common/secret/daos.py
- electrum_gui/common/secret/data.py
- electrum_gui/common/secret/encrypt.py
- electrum_gui/common/secret/exceptions.py
- electrum_gui/common/secret/interfaces.py
- electrum_gui/common/secret/keys/__init__.py
- electrum_gui/common/secret/keys/base.py
- electrum_gui/common/secret/keys/ed25519.py
- electrum_gui/common/secret/keys/secp256k1.py
- electrum_gui/common/secret/keys/secp256r1.py
- electrum_gui/common/secret/manager.py
- electrum_gui/common/secret/migrations/0001_create_keys.py
- electrum_gui/common/secret/models.py
- electrum_gui/common/secret/registry.py
- electrum_gui/common/secret/test_bip32.py
- electrum_gui/common/secret/test_keys.py
- electrum_gui/common/secret/test_manager.py
- electrum_gui/common/secret/utils.py
1. 支持多种签名算法
2. 支持多签名算法 bip32 
3. secret manager
4. peewee ORM 测试用 decorator
5. 测试 secret manager
…
…
…
> secret manager

- electrum/eth_wallet.py
- electrum/wallet.py
- electrum_gui/android/console.py
commit1：支持新需求 https://github.com/OneKeyHQ/TaskHub/issues/1287#issuecomment-823813772
commit2：解决通过xpub导入创建钱包时报错问题
https://github.com/OneKeyHQ/TaskHub/issues/1313
Python and Android
…
> Importing a private key to create a wallet only supports displaying the address type

- electrum/eth_wallet.py
- electrum/wallet.py
- electrum_gui/android/console.py
> Revert "Fix bug"

- electrum/eth_servers.json
- electrum/eth_wallet.py
- electrum/pywalib.py
- electrum_gui/android/console.py
- electrum_gui/common/provider/chains/eth/clients/blockbook.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
- electrum_gui/common/provider/data.py
- electrum_gui/common/provider/interfaces.py
- electrum_gui/common/provider/manager.py
> Revert "Chainlist 支持2 - 清理pywalib以合并配置文件"

- electrum/eth_wallet.py
- electrum/wallet.py
- electrum_gui/android/console.py
由于今天发版 昨天晚上 有一个未经测试部门测试过的pr merge进去 这个pr就是将代码回滚到测试部门已经测试到的版本   
…
…
…
> Fix bug back

- electrum_gui/android/console.py
修复恢复出错bug
https://github.com/OneKeyHQ/TaskHub/issues/1371
…
…
> Fix recovery bug:true every time after reversed

- electrum/eth_servers.json
- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/testnet_chains.json
> Modify okt's rpc node information

- electrum_gui/android/console.py
- electrum_gui/android/wallet_context.py
> Support for user-defined wallet locations

- electrum_gui/android/console.py
lite卡片需要增加对助记词进行编解码的接口
…
Python
…
> Codec for mnemonic words

- electrum_gui/android/console.py
hot fix verify_legality bug
local
none
> hot fix verify_legality bug

- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/testnet_chains.json
更新okt图标的URL，svg -> png
N/A
No
No
> configs: update okt icon url

- electrum_gui/android/console.py
- electrum_gui/common/basic/exceptions.py
异常统一迁移 先实现了verify_legality接口的迁移 
…
Python
…
> Modify the return value of the verify_legality interface

- electrum_gui/common/wallet/manager.py
refresh_assets 这块更新后返回的逻辑之前有问题。
之前是返回需要更新的列表，应该是返回完整列表
…
…
…
> fix refresh_assets

- electrum_gui/android/console.py
修改OKT钱包的展示名称为OEC
https://github.com/OneKeyHQ/TaskHub/issues/1608
Python
…
> Modify the display name of OKT to OEC

- electrum_gui/android/console.py
为了支持新架构同时简化逻辑，去除原来的 elif 分支
…
…
…
> adjust list_wallets

- electrum/ecc.py
- electrum/ecc_fast.py
commit1：切换ecc库到 secp256k1的c实现
commit2：增加ios环境下加载库的路径
https://github.com/OneKeyHQ/TaskHub/issues/1419
Android
…
> Switching encryption library to c implementation

- electrum_gui/common/provider/chains/eth/provider.py
- electrum_gui/common/provider/chains/eth/test_provider.py
仅在 fee_limit 为空时候填充
https://github.com/OneKeyHQ/TaskHub/issues/1564
…
…
> fill fee_limit only if nonce

- electrum_gui/common/secret/keys/ed25519.py
revert pull request #758 due to ios support trouble.
this revert may effect android
local
none
> Revert "Merge pull request #758 from liyanhrxy/bixin_dev"

- electrum/ecc_fast.py
- electrum_gui/common/secret/keys/ed25519.py
1. fix secp256k1 shared lib loading bug
2. revert #774
local
none
> fix secp256k1 shared lib loading bug and revert #774

- electrum/eth_wallet.py
- electrum/keystore.py
- electrum_gui/android/console.py
修复了关于eth类钱包 密码报错问题
https://github.com/OneKeyHQ/TaskHub/issues/1614
https://github.com/OneKeyHQ/TaskHub/issues/1664
python
…
> Fix the password problem of eth wallet

- electrum_gui/common/price/channels/uniswap.py
没有汇率需要获取或者全部已经处理完毕，直接返回就好了
No
Android
Found while debugging.
> uniswap: avoid calling contracts if not needed

- electrum_gui/android/console.py
- electrum_gui/android/wallet_context.py
尝试修复主网报错问题，如果正常方式报错 就尝试从配置文件中获取
https://github.com/OneKeyHQ/TaskHub/issues/1593
…
…
> Fix error about keyerror:coin and keyerror:wallet_type when load_wallet

- electrum_gui/android/console.py
- electrum_gui/android/migrating.py
switch_wallet 补充 GeneralWallet 支持
…
…
…
> GeneralWallet supports switch_wallet

- electrum_gui/android/console.py
ETH 默认 gas limit 改成 21000
…
…
…
> set default eth gas_limit to 21000

- electrum_gui/android/console.py
- electrum_gui/common/basic/exceptions.py
统一异常修改
1.在调用的接口中增加api_version参数
2.在接口的返回值中增加api_version字段
…
python
…
> Uniform exception

- electrum_gui/android/console.py
> Fix create_and_check_wallet

- electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
- electrum_gui/common/provider/chains/stc/provider.py
对齐产品定义的gas 相关数值
https://github.com/OneKeyHQ/TaskHub/issues/1692
…
…
> fix stc gasPrice,gasLimit 

- electrum_gui/common/tests/unit/basic/functional/test_text.py
简单修复一下测试用例里的问题，照顾下不同时区合作的情况
No
`tox -ecover`
No
> test_text: use utcfromtimestamp

- electrum_gui/common/tests/unit/provider/chains/stc/test_provider.py
修复 #793 引起的测试错误
No
No
@dydysy 注意要跑tox -ecover，cc @shuaiLiWang
> 修复 #793 引起的测试错误

- electrum_gui/android/console.py
- electrum_gui/common/tests/unit/wallet/test_manager.py
- electrum_gui/common/wallet/daos/account.py
- electrum_gui/common/wallet/manager.py
> GeneralWallet supports get_default_show_path

- electrum_gui/android/console.py
- electrum_gui/android/migrating.py
- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/testnet_chains.json
- electrum_gui/common/provider/chains/stc/provider.py
- electrum_gui/common/tests/unit/provider/chains/stc/test_provider.py
- electrum_gui/common/tests/unit/wallet/test_manager.py
- electrum_gui/common/wallet/manager.py
stc 需要提供 ReceiptIdentifier 地址
…
…
> support encoding address

- electrum_gui/android/console.py
- electrum_gui/android/migrating.py
- electrum_gui/common/basic/exceptions.py
- electrum_gui/common/secret/manager.py
1. GeneralWallet 支持 check_password, 直接用了 wallet_manager 的 update_wallet_password 方法做判断，
因为这个方法里面会先检查, 不想加新接口了
2. GeneralWallet 支持 get_all_tx_list，先走 provider，非本地缓存 （原 PR：https://github.com/OneKeyHQ/electrum/pull/797 ）
3. GeneralWallet 支持 verify_legality （原 PR：https://github.com/OneKeyHQ/electrum/pull/796 ）
4. get_default_show_path 返回值有误
…
…
> Fix GeneralWallet supporting

- electrum_gui/android/console.py
修复swap的approve功能对应的参数value类型为str
https://github.com/OneKeyHQ/TaskHub/issues/1843
python
…
> Modify the parameter type of the approve interface to str

- electrum_gui/common/provider/chains/stc/provider.py
- electrum_gui/common/tests/unit/provider/chains/stc/test_provider.py
- chain_id 需要 进行类型转换
- ReceiptIdentifier 类型接收地址，需要提取出地址。
…
…
> fix stc fill_unsigned_tx

- electrum/eth_wallet.py
修复不能通过public key创建eth钱包的问题
https://github.com/OneKeyHQ/TaskHub/issues/1807
Python
…
> Fix the bug that eth can not support creating wallet by public key

- electrum_gui/android/migrating.py
- electrum_gui/common/secret/interfaces.py
- electrum_gui/common/secret/keys/base.py
- electrum_gui/common/secret/keys/ed25519.py
- electrum_gui/common/secret/manager.py
- electrum_gui/common/tests/unit/secret/test_keys.py
- electrum_gui/common/wallet/manager.py
> GeneralWallet supports export_private_key

- electrum_gui/android/helpers.py
给 EthSoftwareSigner 添加 https://github.com/OneKeyHQ/electrum/pull/804 引入的接口 get_prvkey
…
…
…
> Fix EthSoftwareSigner

- electrum_gui/android/console.py
功能：支持指定钱包获取交易历史功能 
https://github.com/OneKeyHQ/TaskHub/issues/1923
这个是此issue中的一部分 因为前端一直再催这个接口 所以 先摘出来了实现了 
https://github.com/OneKeyHQ/TaskHub/issues/1660
python
…
> Support specified wallets to get transaction history

- electrum/bsc_token_list.json
更改个BSC上的token名，BUSD-T -> USDT
OneKeyHQ/TaskHub#2009
No
No
> bsc_token_list: change token name BUSD-T -> USDT

- electrum_gui/android/console.py
> Fix the unconfirmed status returned by BTC

- electrum_gui/common/provider/chains/eth/provider.py
- electrum_gui/common/tests/unit/provider/chains/eth/test_provider.py
处理给普通地址转 ETH 同时带上 data 的情况
…
…
…
> Fix eth fill_unsigned_tx

- electrum_gui/android/console.py
- electrum_gui/android/migrating.py
- electrum_gui/common/secret/daos.py
- electrum_gui/common/secret/manager.py
- electrum_gui/common/tests/unit/secret/test_manager.py
- electrum_gui/common/tests/unit/wallet/test_manager.py
- electrum_gui/common/wallet/daos/account.py
- electrum_gui/common/wallet/daos/asset.py
- electrum_gui/common/wallet/daos/wallet.py
- electrum_gui/common/wallet/manager.py
> GeneralWallet supports delete_wallet

- electrum_gui/common/provider/chains/stc/provider.py
- electrum_gui/common/tests/unit/provider/chains/stc/test_provider.py
调整 stc 默认 gas_limit
https://github.com/OneKeyHQ/TaskHub/issues/1904#issuecomment-866587824
…
…
> stc: adjust default gas_limit value

- electrum_gui/android/console.py
合约地址normalize一下避免返回的历史记录中的地址和输入的内容有差异
No
No
No
> 修复查询历史记录时合约地址的大小写问题

- electrum_gui/android/migrating.py
- electrum_gui/common/coin/configs/chains.json
- electrum_gui/common/coin/configs/testnet_chains.json
- electrum_gui/common/provider/chains/__init__.py
- electrum_gui/common/provider/chains/cfx/__init__.py
- electrum_gui/common/provider/chains/cfx/conflux.py
- electrum_gui/common/provider/chains/cfx/provider.py
- electrum_gui/common/provider/chains/cfx/sdk/cfx_account/__init__.py
- electrum_gui/common/provider/chains/cfx/sdk/cfx_account/_utils/signing.py
- electrum_gui/common/provider/chains/cfx/sdk/cfx_account/_utils/transactions.py
- electrum_gui/common/provider/chains/cfx/sdk/cfx_address/__init__.py
- electrum_gui/common/provider/chains/cfx/sdk/cfx_address/address.py
- electrum_gui/common/provider/chains/cfx/sdk/cfx_address/base32.py
- electrum_gui/common/provider/chains/cfx/sdk/cfx_address/utils.py
- electrum_gui/common/provider/chains/cfx/sdk/consts.py
- electrum_gui/common/provider/chains/cfx/sdk/types.py
- electrum_gui/common/tests/unit/provider/chains/cfx/test_provider.py
add conflux support
local
none
> feat: add conflux support

- electrum_gui/common/provider/chains/eth/clients/blockbook.py
解决测试网eth获取不到交易记录的问题
…
python
…
> Solve the problem that eth can't get transaction list in testnet

- electrum_gui/common/provider/chains/cfx/sdk/cfx_account/_utils/transactions.py
fix ios import error
local
none
> fix(cfx/sdk): fix ios import error

- electrum_gui/android/console.py
修复获取交易记录时显示问题
https://github.com/OneKeyHQ/TaskHub/issues/1867
python
…
> solved the problem of displaying scientific notation for amount

- electrum/util.py
- electrum_gui/android/console.py
- electrum_gui/android/hardware.py
- electrum_gui/common/basic/exceptions.py
返回值统一会分两个pr完成，这是第一个pr，将目前issue中存在异常问题的api优先处理
https://github.com/OneKeyHQ/TaskHub/issues/1630
https://github.com/OneKeyHQ/TaskHub/issues/1655
https://github.com/OneKeyHQ/TaskHub/issues/1512
https://github.com/OneKeyHQ/TaskHub/issues/1154
python
…
> Uniform interface return value---1

- electrum/servers.json
删除一些节点。
https://onekeyhq.atlassian.net/browse/OK-2464
https://github.com/trezor/electrum/commits/master/electrum/servers.json
…
…
> remove some electrum node

- electrum_gui/android/console.py
- electrum_gui/android/migrating.py
- electrum_gui/common/basic/functional/signal.py
- electrum_gui/common/basic/ticker/__init__.py
- electrum_gui/common/the_begging.py
- electrum_gui/common/transaction/daos.py
- electrum_gui/common/transaction/manager.py
- electrum_gui/common/wallet/manager.py
1. delete_wallet 需要判断 hd 然后清空所有主钱包
2. reset_wallet_info 支持清除 App 数据
…
…
> GeneralWallet supports delete_wallet and reset_wallet_info

- tox.ini
不想把太多东西往pip里装的时候这个有用，将需要的东西都限制在virtualenv里，本地的pip只需要装tox和virtualenv就好。
No
No
No
> tox: add pre-commit environment

- electrum_gui/android/console.py
支持btc的交易广播到blockbook节点
…
Python
> Support for btc transaction broadcast to blockbook node

- electrum_gui/android/console.py
在API入口/出口处才完成`json.dumps`的操作，从而内部方法可以不关注这个转换用回原生数据类型。
问题隐藏得有点深，之前 #820 修改之后`get_general_coin_tx_list`找不到历史时会直接返回`[]`，但实际上需要的是一个dumps过的字符串...
避免以后再容易出类似问题，统一对应内部的辅助方法就不先dump了，只在api入口的地方做这种处理。
No
iOS
No
> get_all_tx_list: dump to json string at the api level

- electrum_gui/android/console.py
- electrum_gui/android/migrating.py
- electrum_gui/common/provider/chains/cfx/conflux.py
- electrum_gui/common/provider/chains/eth/clients/blockbook.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
- electrum_gui/common/provider/chains/sol/clients/solana.py
- electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
- electrum_gui/common/provider/data.py
- electrum_gui/common/provider/manager.py
- electrum_gui/common/tests/unit/provider/chains/cfx/test_provider.py
- electrum_gui/common/tests/unit/provider/chains/eth/test_provider.py
- electrum_gui/common/tests/unit/provider/chains/sol/test_provider.py
- electrum_gui/common/tests/unit/provider/chains/stc/test_provider.py
- electrum_gui/common/tests/unit/wallet/test_manager.py
- electrum_gui/common/wallet/manager.py
返回多档费率的列表
OneKeyHQ/TaskHub#1782
[OK-238] 相关PR
[OK-144] 相关PR
[OK-2432] 相关PR
No
[OK-238]: https://onekeyhq.atlassian.net/browse/OK-238
[OK-144]: https://onekeyhq.atlassian.net/browse/OK-144
[OK-2432]: https://onekeyhq.atlassian.net/browse/OK-2432
> 支持返回多档费率列表，取代固定档位的DICT返回值

- electrum_gui/android/console.py
- electrum_gui/common/wallet/manager.py
支持get_devired_num，统计某个币种的当前主钱包个数
https://onekeyhq.atlassian.net/browse/OK-2575?focusedCommentId=10523
…
…
> GeneralWallet supports get_devired_num

- electrum/plugins/trezor/clientbase.py
- electrum_gui/android/hardware.py
- electrum_gui/common/basic/exceptions.py
optimize error tips when updating firmware
[OK-2568] [OK-2649]
- [] Bugfix
local
none
[OK-2568]: https://onekeyhq.atlassian.net/browse/OK-2568
[OK-2649]: https://onekeyhq.atlassian.net/browse/OK-2649
> OK-2568-optimize error tips when updating firmware

- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
补充 BlockHeader 的 block_time 字段
https://onekeyhq.atlassian.net/browse/OK-2691
…
…
> Fill BlockHeader for Geth and Etherscan

- electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
补充 BlockHeader 的 block_time 字段
https://onekeyhq.atlassian.net/browse/OK-2691
…
…
> Fill BlockHeader for stc jsonRPC

- electrum_gui/android/console.py
- electrum_gui/common/provider/chains/cfx/sdk/cfx_account/__init__.py
add dapp interface support for cfx
[OK-2683]
local
none
[OK-2683]: https://onekeyhq.atlassian.net/browse/OK-2683
> OK-2683 add dapp interface support for cfx

- electrum_gui/common/basic/functional/wraps.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/transaction/manager.py
- electrum_gui/common/transaction/migrations/0004_txaction_add_indexes.py
修复检索交易记录时因为并发请求而出现交易重复创建问题
https://onekeyhq.atlassian.net/browse/OK-2756
…
…
> Transaction - Fix concurrency issue

- electrum_gui/common/coin/daos.py
- electrum_gui/common/transaction/daos.py
bulk_create 的 batch_size 原来的 100 个对 App 的 python 环境来说太多了，改成 10 个，已经让荣强本地试过了，可行
https://onekeyhq.atlassian.net/browse/OK-2436
…
…
> decrease the value of batch_size

- electrum_gui/android/console.py
删除钱包后需要清理掉引用
[OK-2743]
N/A
No
[OK-2743]: https://onekeyhq.atlassian.net/browse/OK-2743
> OK-2743: console: clear wallet refs after deleting

- electrum_gui/common/provider/chains/cfx/conflux.py
状态判断有误
https://onekeyhq.atlassian.net/browse/OK-2806
…
…
> Fix get_transaction_by_txid of cfx

- electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
https://onekeyhq.atlassian.net/browse/OK-2838
stc 刚发出的交易，使用当前接口获取交易信息会失败，所以添加 txpool.pending_txn 请求获取未确认交易。
…
…
> stc: get unconfirmed tx from txpool

- electrum/plugins/trezor/clientbase.py
fix import error and reformat import style
[OK-2895]
local
none
[OK-2895]: https://onekeyhq.atlassian.net/browse/OK-2895
> OK-2895 fix(clientbase): fix import error and reformat import style

- electrum_gui/android/console.py
- electrum_gui/android/migrating.py
- electrum_gui/common/basic/bip44.py
- electrum_gui/common/coin/data.py
- electrum_gui/common/coin/loader.py
- electrum_gui/common/conf/settings.py
- electrum_gui/common/hardware/callbacks/__init__.py
- electrum_gui/common/hardware/callbacks/android.py
- electrum_gui/common/hardware/callbacks/base.py
- electrum_gui/common/hardware/callbacks/helper.py
- electrum_gui/common/hardware/callbacks/ios.py
- electrum_gui/common/hardware/callbacks/terminal.py
- electrum_gui/common/hardware/exceptions.py
- electrum_gui/common/hardware/interfaces.py
- electrum_gui/common/hardware/manager.py
- electrum_gui/common/hardware/proxy.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
- electrum_gui/common/provider/chains/eth/provider.py
- electrum_gui/common/provider/interfaces.py
- electrum_gui/common/provider/manager.py
- electrum_gui/common/tests/unit/basic/test_bip44.py
- electrum_gui/common/tests/unit/hardware/callbacks/test_helper.py
- electrum_gui/common/tests/unit/wallet/test_manager.py
- electrum_gui/common/wallet/daos/wallet.py
- electrum_gui/common/wallet/data.py
- electrum_gui/common/wallet/manager.py
- electrum_gui/common/wallet/migrations/0002_walletmodel_add_hardware_key_id.py
- electrum_gui/common/wallet/models.py
1. 整理下 provider.interfaces 的 import 方式
2. 将 bip44 移到 basic 模块
3. 将 ChainInfo 的枚举字段由字符串类型改成枚举类型，方便使用
4. 新增 hardware 模块，并补充目前真实用到的方法和实现
5. 新增 HardwareSupportingMixin，并为 ETH 添加实现
6. 整理下 wallet.manager 的 import 方式
7. wallet manager 增加硬件钱包支持
8. GeneralWallet 以及 console 增加对 migrated_coin 的硬件钱包支持
https://onekeyhq.atlassian.net/browse/OK-80
…
…
> Hardware related

- electrum_gui/android/console.py
删除临时文件
https://onekeyhq.atlassian.net/browse/OK-177
Python
…
> OK-177 Clean up temp files

- electrum/network.py
- electrum/util.py
- electrum_gui/android/console.py
- electrum_gui/android/hardware.py
- electrum_gui/common/basic/api.py
- electrum_gui/common/basic/exceptions.py
console.py中 所有接口返回值统一成V2版本
…
接口测试完成 
再在android下跑一遍基本流程（本地android环境有点儿问题 正在修复。。。）
…
> Uniform interface return value:2

- electrum/heco_token_list.json
新增个heco token，同 #861，希望快点不用维护这些数据。
[OK-2841]
No
No
[OK-2841]: https://onekeyhq.atlassian.net/browse/OK-2841
> OK-2841: heco: add coco token

- electrum_gui/common/coin/configs/chains.json
升级使用到的pancake swap。android端的动态化本周状态还不确定，所以先把这个补上
[OK-2796]
Python & iOS
No
[OK-2796]: https://onekeyhq.atlassian.net/browse/OK-2796
> OK-2796 config: update to pancake swap v2

- electrum_gui/android/console.py
Fix the rebase error on [here](https://github.com/OneKeyHQ/electrum/pull/830/files#diff-f72ab8def5890a07060c16da0d0ae4296a9220676543dde64d41e11814ef8ff8R819)
…
…
…
> Fix the rebase error of pr830

- electrum_gui/android/console.py
Turn off use change function
…
…
…
> Turn off use change function

- electrum_gui/common/basic/exceptions.py
update lokalise key for [here](https://github.com/OneKeyHQ/electrum/pull/830)
…
…
…
> update lokalise key

- electrum_gui/android/console.py
- electrum_gui/common/coin/daos.py
- electrum_gui/common/coin/manager.py
- electrum_gui/common/provider/chains/sol/clients/solana.py
- electrum_gui/common/tests/unit/coin/test_manager.py
1. remove lowercase processing of the contract address
2. fix sol transaction parse bug
3. fix coin module unit test
[OK-2598, OK-2603]
local
nil
> fix sol about bugs

- electrum_gui/common/provider/chains/eth/clients/utils.py
- electrum_gui/common/provider/exceptions.py
处理链上返回余额不足的情况
[OK-119]
No
No
[OK-119]: https://onekeyhq.atlassian.net/browse/OK-119
> OK-119 evm: raise specific exceptions for insufficient funds

- electrum_gui/android/console.py
`coin_manager.get_coins_by_chain`会返回主币种信息，所以需要额外判断`token_address`非空
#867 
No
No
> 修复PR #867中的错误

- electrum_gui/android/console.py
> Add api for app to get balance for main coin

- electrum_gui/android/console.py
- electrum_gui/common/basic/ticker/ticker.py
- electrum_gui/common/price/channels/coingecko.py
- electrum_gui/common/provider/loader.py
- electrum_gui/common/secret/manager.py
- electrum_gui/common/transaction/manager.py
修复`logging.exception`
No
No
No
> fix logging.exception mistakes

- prepare_env.py
加个脚本，用来做python代码运行前需要的准备工作，这样子不至于忘记有这么一步。
APP打包过程中可以直接运行这个脚本来保证python环境可用。
No
No
No
> add a prepare env script

- electrum_gui/android/console.py
- electrum_gui/android/hardware.py
- electrum_gui/android/migrating.py
- electrum_gui/common/coin/data.py
- electrum_gui/common/hardware/callbacks/terminal.py
- electrum_gui/common/hardware/manager.py
- electrum_gui/common/hardware/proxy.py
- electrum_gui/common/provider/chains/btc/provider.py
- electrum_gui/common/provider/manager.py
- electrum_gui/common/tests/unit/wallet/test_manager.py
- electrum_gui/common/wallet/manager.py
1. provider_manager 有个 Bug 修复下，对线上无影响
2. 简单为 BTCProvider 实现了 HardwareSupportingMixin，支持非转账的其他硬件操作
3. 硬件交互相关迁移，调整 hardware_manager 里方法的名字，更加明确用途
4. 优化 TerminalCallback，pin 和 passphrase 输入方式可控，方便调试
5. 优化 GeneralWallet 中 is_mine 的判断，统一转成 normalize address 来判断地址
https://onekeyhq.atlassian.net/browse/OK-2919
…
…
> OK-2919: Migrating Hardware 

- electrum_gui/common/coin/data.py
- electrum_gui/common/conf/chains.py
- electrum_gui/common/tests/unit/transaction/test_manager.py
- electrum_gui/common/transaction/daos.py
- electrum_gui/common/transaction/manager.py
RBF 后的交易确认后自动把被 RBF 的交易的状态改成 REPLACED
…
…
…
> OK-3159: Update RBF transactions status

- electrum_gui/common/provider/chains/eth/clients/blockbook.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
调整下最小手续费率，和MM一致。
[OK-3186]
No
No
[OK-3186]: https://onekeyhq.atlassian.net/browse/OK-3186
> OK-3186: evm: decrease minimum fee rate to 0.1 Gwei

- electrum/eth_wallet.py
- electrum/wallet.py
- electrum_gui/android/console.py
- electrum_gui/android/migrating.py
- electrum_gui/common/basic/exceptions.py
- electrum_gui/common/secret/manager.py
- electrum_gui/common/wallet/manager.py
- electrum_gui/common/wallet/utils.py
1. 添加对sollet、phantom 导出的私钥(keypair)的导入支持
2. 优化导入错误的错误提示
[OK-3431] [OK-3432]
local
none
[OK-3431]: https://onekeyhq.atlassian.net/browse/OK-3431
[OK-3432]: https://onekeyhq.atlassian.net/browse/OK-3432
> OK-3431 OK-3432 add sol three format import and fix import error tips

- electrum_gui/common/provider/chains/sol/clients/solana.py
> replace sol rpc method `getConfirmedTransaction`  with `getTransaction`

- electrum_gui/android/helpers.py
- electrum_gui/common/provider/exceptions.py
- 修复签名长度恢复出问题的错误
- 修复初始化InsufficientBalance异常的问题，虽然这个异常不需要从rpc返回解析出字符串，但是还是要和其它异常保持一致...
[OK-3539] [OK-3325]
No
No
[OK-3539]: https://onekeyhq.atlassian.net/browse/OK-3539
[OK-3325]: https://onekeyhq.atlassian.net/browse/OK-3325
> OK-3539 OK-3325 Fix a couple of problems

- electrum/eth_wallet.py
- electrum_gui/android/console.py
- electrum_gui/common/provider/chains/cfx/conflux.py
- electrum_gui/common/provider/chains/cfx/provider.py
- electrum_gui/common/provider/chains/eth/clients/blockbook.py
- electrum_gui/common/provider/chains/eth/clients/etherscan.py
- electrum_gui/common/provider/chains/eth/clients/geth.py
- electrum_gui/common/provider/chains/eth/clients/helper.py
- electrum_gui/common/provider/chains/eth/hardware_mixin.py
- electrum_gui/common/provider/chains/eth/message_mixin.py
- electrum_gui/common/provider/chains/eth/provider.py
- electrum_gui/common/provider/chains/eth/sdk/message.py
- electrum_gui/common/provider/chains/eth/sdk/solidity.py
- electrum_gui/common/provider/chains/eth/sdk/utils.py
- electrum_gui/common/provider/interfaces.py
- electrum_gui/common/provider/manager.py
- electrum_gui/common/secret/keys/base.py
- electrum_gui/common/tests/unit/provider/chains/eth/sdk/test_message.py
- electrum_gui/common/tests/unit/provider/chains/eth/test_message_mixin.py
- electrum_gui/common/tests/unit/wallet/test_manager.py
- electrum_gui/common/wallet/manager.py
1. 整理 ETHProvider，摘出硬件相关的单独成一个 Mixin 类，方便管理
2. ETHProvider 支持 MessageSupportingMixin
3. 迁移相关
4. CFXProvider 支持 MessageSupportingMixin
…
…
…
> OK-3248: ETHProvider supports MessageSupportingMixin

- electrum/MutiBase.py
- electrum/keystore.py
- electrum/wallet.py
- electrum/wallet_db.py
- electrum_gui/android/console.py
支持通过硬件创建的BTC自定义路径钱包转账
[OK-3059]
Python 
…
[OK-3059]: https://onekeyhq.atlassian.net/browse/OK-3059
> OK-3059 Support send for btc customized path wallet

- electrum_gui/android/console.py
- electrum_gui/common/hardware/callbacks/ios.py
- 修复ios的handler初始化，命名问题
- 去除tbtc的show_address workaround，改用hardware manager之后不需要了
No
IOS
No
> Hardware wallet fix

- electrum/eth_wallet.py
EVM系列的账户使用缓存中的余额替代0
[OK-3289]
No
No
[OK-3289]: https://onekeyhq.atlassian.net/browse/OK-3289
> OK-3289: eth_wallet: use cached balances instead of 0

- electrum_gui/android/console.py
- electrum_gui/common/provider/chains/cfx/conflux.py
conflux的交易记录时间现在全是0，需要补上...
No
No
No
> cfx: fill block timestamp & switching fix

- electrum/eth_wallet.py
- electrum_gui/android/console.py
修改验证接口适配sol keypair 导入
[OK-3432]
local
none
[OK-3432]: https://onekeyhq.atlassian.net/browse/OK-3432
> fix: modify method `verify_legality` to adapt sol private key import

- electrum_gui/android/console.py
iOS超过int64的数字需要变成str传进来，转换一下
[OK-3822] 相关
No
No
[OK-3822]: https://onekeyhq.atlassian.net/browse/OK-3822
> dapp_sign_eth_tx: convert value to int

- electrum_gui/android/console.py
在给前端的回调数据中增加chaincode字段
…
Python
…
> Add the chaincode field to the callback data

- electrum_gui/common/hardware/manager.py
- electrum_gui/common/hardware/proxy.py
修复硬件client缓存 在极端情况导致的bug
[OK-3821]
local
nil
[OK-3821]: https://onekeyhq.atlassian.net/browse/OK-3821
> OK-3821 fix: fix hardware client cache bug
